### ISSUE TITLE
Cannot find module "mapbox-gl/js/geo/transform"

### ISSUE THREAD

**Issue by hdrdavies** [uber/react-map-gl#100]
I'm getting this error as the transform API is required in the `map.react.js` file:

`var _transform = require('mapbox-gl/js/geo/transform');`

But as you say in the the comments of your source file:

>NOTE: Transform is not a public API so we should be careful to always lock
down mapbox-gl to a specific major, minor, and patch version.
import Transform from 'mapbox-gl/js/geo/transform';

So why is this included if it's not a public API?

The `geo/transform` directories don't seem to be included when I install `mapbox-gl` with npm 

How can I resolve this?

**Comment by hdrdavies** [comment]
Actually, it seems it is in there, but react-map-gl seems to go looking for it in the dist directory rather than the js directory. Baffling! 

Help welcome :)

**Comment by ibgreen** [comment]
@hdrdavies What bundler are you using? react-map-gl is tested with browserify only.

**Comment by hdrdavies** [comment]
webpack! 

It was caused by specifying an alias in my webpack config that I don't think I needed to. Even so I couldn't get it to work but I've moved onto another solution.

**Comment by gcwelborn** [comment]
hey @hdrdavies, havin the same issue - could you elaborate on the other solution?

**Comment by hdrdavies** [comment]
@gcwelborn I'm now just using the naked mapbox-gl-js api, not with the react-map-gl wrapper.
