### ISSUE TITLE
Got NO_TOKEN_WARNING with a valid access token in Chrome

### ISSUE THREAD

**Issue by sugia** [uber/react-map-gl#1002]
**mapbox-gl-js version**:
react-map-gl@5.1.5

**browser**:
Chrome (Version 79.0.3945.130 (Official Build) (64-bit))

### Description
The same token works well in:
Firefox (Version 72.0.1 (64-bit))
Safari (Version 13.0.4 (14608.4.9.1.4))
Yandex (Version 19.12.0.769 (64-bit))

but got NO_TOKEN_WARNING in:
Chrome (Version 79.0.3945.130 (Official Build) (64-bit))

### Expected Behavior
<img width="376" alt="Screen Shot 2020-01-20 at 8 30 09 AM" src="https://user-images.githubusercontent.com/2340878/72742683-1ba5bd00-3b5f-11ea-83f1-58feb0a461be.png">

### Actual Behavior
<img width="376" alt="Screen Shot 2020-01-20 at 8 29 53 AM" src="https://user-images.githubusercontent.com/2340878/72742701-23fdf800-3b5f-11ea-8786-49debdd2d588.png">

**Comment by Pessimistress** [comment]
This is unlikely an error originated in react-map-gl. You should check if you have any Chrome plugin that interferes with the request to Mapbox's server.

**Comment by sugia** [comment]
Ah yes, it's a plugin's issue. Thx for the help.

**Comment by Kaikeanaaina** [comment]
@sugia do you know what chrome plugin was causing the issue?
