### ISSUE TITLE
FlyToInterpolator after scroll

### ISSUE THREAD

**Issue by prrrcl** [uber/react-map-gl#1007]
Hi, I have: https://codesandbox.io/s/amazing-dust-z7n4z?fontsize=14&hidenavigation=1&theme=dark
When i do scroll and click on marker, flytointerpolator not work!

if i do click on controls (left) and click on marker, work fine...

**Comment by RobJacobson** [comment]
Have a look at this [camera-transition example](https://uber.github.io/react-map-gl/#/Examples/camera-transition), including the linked code.

Your current code defines a global FlyToInterpolator() with no parameters.  You use this as the initial state for viewport.  This doesn't work.

In the example code, a new FlyToInterpolator is created within _goToViewport.  In other words, you wait for the viewport to change.  Once the viewport is about to change, you create a new FlyToInterpolator to "smooth" the transition to the new state.  This should be created only when you're changing viewport, not as a global object.

I hope this helps!

**Comment by RobJacobson** [comment]
There's also a good example [here](https://uber.github.io/react-map-gl/#/Documentation/advanced/viewport-transition). Note how the FlyToInterpolator is created within _goToNYC, which is called in response to a user event (a button click).

**Comment by prrrcl** [comment]
Its work! and i changed transitionDuration: 800 to 'auto'

Thanks!
