### ISSUE TITLE
are Markers a features? 

### ISSUE THREAD

**Issue by prrrcl** [uber/react-map-gl#1008]
I tried get how many markers are on viewport with querySourceFeatures('myMarkerId') but i cant. How can i get these markers?

**Comment by RobJacobson** [comment]
The <marker ... /> class is actually not a map feature.  I.e., markers are not added to the underlying mapbox-gl instance.  Instead, they are drawn on top as a completely-separate overlay using React.

You can see this by reading the rendered HTML using Developer Tools in your browser.  The map itself is rendered inside of a class "mapboxgl-map."  The overlays, including markers, are rendered in a separate div with the class "overlays" (which is inside of a div that begins with style="overflow....").

If you need to count the number of markers that are currently visible onscreen, have a look at the _getPosition() method inside the [Marker.js class](https://github.com/uber/react-map-gl/blob/master/src/components/marker.js), especially line 76.  This private method returns the pixel coordinates of the given marker.  You would need to iterate through each marker and test if 0 < x < viewport-width and if 0 < y < viewport-height.

I hope this helps.

**Comment by prrrcl** [comment]
That seems the solution. Thank you !

**Comment by prrrcl** [comment]
Hi again, i have the viewport and the markers position in pixel. How can i get viewport X and viewport Y? i only have these properties of viewport:
 `width: 1070
height: 440
latitude: 37.1048991844287
longitude: -5.795918470352118
zoom: 9.160957109310129
bearing: 0
pitch: 0
altitude: 1.5
maxZoom: 24
minZoom: 0
maxPitch: 60
minPitch: 0
transitionDuration: 0
transitionEasing: ƒ transitionEasing(t)
transitionInterpolator: ViewportFlyToInterpolator {propNames: Array(5), speed: undefined, props: {…}}
transitionInterruption: 1`
