### ISSUE TITLE
Markers only drawn after map is moved

### ISSUE THREAD

**Issue by NiallRees** [uber/react-map-gl#1028]
I've run into an issue where I'm trying to create a marker upon a right click, but it only appears one I move the map. Video attached demonstrates the issue. I wonder if there is a way to force a redraw after the marker has been added.

![ezgif-2-c5bc8a61c5eb](https://user-images.githubusercontent.com/23722609/74661994-f7a2bf00-5190-11ea-8815-b0d321a443a4.gif)

**Comment by dom-the-dev** [comment]
@NiallRees did you solve this problem? If yes, can you tell me how?
