### ISSUE TITLE
Popup on Marker while hovering it? 

### ISSUE THREAD

**Issue by DhanushkumarSivaji** [uber/react-map-gl#1031]
Hi,

Is any other way to add a hover option to marker. 

Thanks

**Comment by bilafish** [comment]
@DhanushkumarSivaji Have you tried adding an onMouseEnter or onMouseOver event listener and handler to the Marker component? From what I tried, that should work

**Comment by DhanushkumarSivaji** [comment]
@bilafish Thanks man..its working..really appreciate it.

**Comment by agustinclarity** [comment]
Guys @DhanushkumarSivaji @bilafish, could you please provide and example of how did you make this work? I am using react-map-gl with Marker component, so no deck.gl or other library. If I set the onMouseEnter to the Map component, nothing happens, and if I set onMouseOver, the retrieving event has so many properties that I have no idea how to make a distinction between a regular event in the map and actually being hovering a marker. Thanks a lot in advance!

**Comment by scsskid** [comment]
You can nest an component which listens for mouseEnter

```
<Marker>
  <div onMouseenter={handler}>
    <MarkerImage />
  </div>
</Marker>
```

**Comment by balaji-kyro** [comment]
@scsskid  Can anyone know to how to handle flicker effect? while using mouseEnter and mouseLeave event.
