### ISSUE TITLE
Error: AnimationLoop.onCreateContext - illegal context returned

### ISSUE THREAD

**Issue by hardysabs2** [uber/react-map-gl#1046]
I have had react-map-gl and deck-gl working in my code base with versions

"deck.gl": "^7.2.6"
"react-map-gl": "^5.0.10"

presenting the map and layers.

Now with the exact same code and data I am getting the following error. Can you possibly advise me the best way to debug this?

animation-loop.js:444 Uncaught (in promise) Error: AnimationLoop.onCreateContext - illegal context returned
at AnimationLoop._createWebGLContext (animation-loop.js:444)
at animation-loop.js:133
_createWebGLContext @ animation-loop.js:444
(anonymous) @ animation-loop.js:133
Promise.then (async)
start @ animation-loop.js:150
Deck @ deck.js:144
componentDidMount @ deckgl.js:40
commitLifeCycles @ react-dom.development.js:22079
commitLayoutEffects @ react-dom.development.js:25331
callCallback @ react-dom.development.js:337
invokeGuardedCallbackDev @ react-dom.development.js:386
invokeGuardedCallback @ react-dom.development.js:439
commitRootImpl @ react-dom.development.js:25069
unstable_runWithPriority @ scheduler.development.js:701
runWithPriority$2 @ react-dom.development.js:12231
commitRoot @ react-dom.development.js:24909
finishSyncRender @ react-dom.development.js:24304
performSyncWorkOnRoot @ react-dom.development.js:24284
(anonymous) @ react-dom.development.js:12285
unstable_runWithPriority @ scheduler.development.js:701
runWithPriority$2 @ react-dom.development.js:12231
flushSyncCallbackQueueImpl @ react-dom.development.js:12280
flushSyncCallbackQueue @ react-dom.development.js:12268
discreteUpdates$1 @ react-dom.development.js:24401
discreteUpdates @ react-dom.development.js:1439
dispatchDiscreteEvent @ react-dom.development.js:5914

**Comment by Pessimistress** [comment]
This error is from deck.gl, not react-map-gl. You can open an issue in the deck.gl repo.
