### ISSUE TITLE
[Bug] Marker <div> overlaying other Markers

### ISSUE THREAD

**Issue by pawelsas** [uber/react-map-gl#1050]
I have a map with many custom markers (100+). Like in the example, I am using a custom svg icon for the marker. In order to correctly position the marker it's necessary to transform/translate the svg, e.g. `transform: translate(${-SIZE / 2}px,${-SIZE}px)`. Due to that the hidden/containing div lays on top of all neighbor markers and makes them not clickable.

Actually, the given example is even buggy: https://uber.github.io/react-map-gl/examples/controls

<img width="667" alt="1" src="https://user-images.githubusercontent.com/15066762/76633965-db066680-6545-11ea-86eb-ec069e79d99a.png">
<img width="716" alt="2" src="https://user-images.githubusercontent.com/15066762/76633968-dc379380-6545-11ea-8934-7c16e34021e2.png">

**Comment by bounouidarhamza** [comment]
Hello Pawel,
Can i make a pull-request to see if i can ifure out what's going on :)

**Comment by pawelsas** [comment]
Hey, the code is publicly available in the docs: https://github.com/uber/react-map-gl/tree/5.2-release/examples/controls

**Comment by pawelsas** [comment]
So I think I found an adequate solution for this issue. Just applied `offsetLeft` and `offsetTop` on the Marker/Pin instead of Popup. I suggest to update the example accordingly.
