### ISSUE TITLE
How do I access renderWorldCopies?

### ISSUE THREAD

**Issue by hardysabs2** [uber/react-map-gl#1056]
I cannot seem to find a way in react-map-gl to access the mapbox-gl renderWorldCopies to disable it.  I can see some access to this mapbox-gl and some access to that underlying feature in react-mapbox-gl and react-map-gl-alt but cannot find it in react-map-gl.

As an alternative I am limiting zoom out with minZoom but cannot seem to find the right (non linear) relationship between pageWidth and minZoom.

Please can you help.

Thanks.

**Comment by Pessimistress** [comment]
[mapOptions](https://uber.github.io/react-map-gl/docs/api-reference/static-map#mapoptions)
