### ISSUE TITLE
Setting width/height in viewport to vh/vw calculates pixel values to put in css

### ISSUE THREAD

**Issue by axleun** [uber/react-map-gl#1066]
When I used "width:100vw" in  ReactMapGL component (in the viewport), after compiling the css, the div that is wrapping the map actually calculates the value in pixels (based on current viewport size) and puts the calculated "px in the css, but what I want is for the div wrapping the map to use "100vw" instead of the calculated px value... to further complicate the problem the div that's wrapping the map doesn't have a class so I can't just directly overwrite the property in my css. 

The reason I want to use 100vw is because when resizing the window, vw automatically resizes the map itself to fit the new viewport size. With the calculated px value, when resizing the window, the px value stays the same and so the map isn't "responsive"; it doesn't resize to fit the entire width of the new viewport size.

I did a "hack" which is wrapping all the divs generated by MapGL, giving it a class say "map-full-size", then in css referring to the specific wrapper as the "first child":

```css
.map-full-size > div:first-child > div:first-child {
width: 100vw;
}
```

Is there something I'm missing here? Maybe I just missed something, like there is a prop for this specific issue or something. 

Thanks!

**Comment by Pessimistress** [comment]
You can override the width like this: `<MapGL {...viewport} width="100vw" />`

**Comment by axleun** [comment]
> You can override the width like this: `<MapGL {...viewport} width="100vw" />`

That did the trick, thanks.
