### ISSUE TITLE
Allow zoom on wheel only when Ctrl or Alt key is held down

### ISSUE THREAD

**Issue by apakbaz** [uber/react-map-gl#1069]
I have been trying to use a few properties on the component to find out if I can stop the map from zooming on wheel scroll except when ctrl or alt key is down.
I used `onWheel` event with the following code: 
```
onWheel = { event => {
if (event.srcEvent.ctrlKey) {
  return;
}

if (event.srcEvent.metaKey) {
  return;
}

if (event.srcEvent.altKey) {
   return;
}

event.preventDefault();
} }
```

Setting `scrollZoom` to false and using above `onWheel` event won't solve the problem because when I hold down the ctrl key and scroll, it does zoom the browser as well.
Strangely enough, if I don't set the `scrollZoom` it works and has no effect on the browser zoom even when holding down the ctrl key, but unfortunately does not achieve what I am looking for because it still zoom the map on wheel scroll.

Thanks very much.

**Comment by Pessimistress** [comment]
You can achieve this by implementing a [custom map controller](https://uber.github.io/react-map-gl/docs/advanced/custom-map-controller).

**Comment by apakbaz** [comment]
I was able to achieve this using `onWheel` event as below:
```
onWheel = { event => {      
            if (event.srcEvent.ctrlKey) {             
              setSettings({...settings, scrollZoom: true});
              event.preventDefault();
            }
     }
}
```
and a hook to set settings:
```
const [settings, setSettings] = useState({
      dragPan: true,
      dragRotate: true,
      scrollZoom: false,
      touchZoom: true,
      touchRotate: true,
      keyboard: true,
      doubleClickZoom: true,
      minZoom: 0,
      maxZoom: 20,
      minPitch: 0,
      maxPitch: 85
  });
```
make sure you spread that setting object on your `ReactMapGL` component.

**Comment by chriszrc** [comment]
@Pessimistress I think you're right, the custom map controller is the way to go, and I have a working version of this:

```typescript
class MapScrollController extends MapController {
  handleEvent(event: any) {
    if (event.type === "wheel") {
      if (event.srcEvent.ctrlKey || event.srcEvent.metaKey) {
        return super.handleEvent(event);
      } else {
        return false;
      }
    } else {
      return super.handleEvent(event);
    }
  }
}
```

The map's configuration options are left alone, with scrollZoom left to default true, but bypass executing the scroll actions when the ctrl or cmd key is not also pressed. 

Then I added a custom overlay component to show a message when the user is trying to zoom, but isn't holding the keys down:

```typescript
export interface MapScrollOverlayProps {
  onWheelEvent: Partial<MjolnirEvent["srcEvent"]> | null;
  offsetPctLeft?: number;
  offsetPctTop?: number;
}

const MapScrollOverlay = React.memo<MapScrollOverlayProps>(
  ({onWheelEvent, offsetPctLeft = 50, offsetPctTop = 50}) => {
    const [isVisible, setIsVisible] = useState(false);
    const context = useContext(MapContext);
    const debouncedOnWheelEvent = useCallback(
      debounce(() => {
        setIsVisible(false);
      }, 400),
      [],
    );

    useEffect(() => {
      if (onWheelEvent) {
        if (!onWheelEvent.ctrlKey && !onWheelEvent.metaKey) {
          setIsVisible(true);
        }

        debouncedOnWheelEvent();
      }
    }, [onWheelEvent, debouncedOnWheelEvent]);

    return isVisible ? (
      <div className={styles.MapScrollOverlay} data-testid="MapScrollOverlay">
        <div className={styles.overlay}></div>
        <div
          className={styles.textWrapper}
          style={{left: offsetPctLeft + "%", top: offsetPctTop + "%"}}
        >
          Use ⌘ or Ctrl + scroll to zoom the map
        </div>
      </div>
    ) : null;
  },
);
```

However, to use this strategy, the MapScrollOverlay component still needs to get notified when there is an onWheel event, so I have to add a callback to the InteractiveMap object, and pass the event to the MapScrollOverlay component. This feels messy, and doesn't make this as much of a drop in solution. 

```typescript
const [onWheelEvent, setOnWheelEvent] = useState<Partial<MjolnirEvent["srcEvent"]> | null>(null);
  const onWheel = useCallback((event: MapEvent) => {
    setOnWheelEvent({
      ctrlKey: event.srcEvent.ctrlKey,
      metaKey: event.srcEvent.metaKey,
    });
  }, []);

return(
 <InteractiveMap
        {...viewport}
        onWheel={onWheel}
        controller={mapScrollController}
      >
      //etc
      </InteractiveMap>
)
```

The MapScrollOverlay has access to the MapContext, is there anything I can use in the MapController to pass information about the fact that there is a scroll event occurring (but without the modifier keys, which we already know how to check for) that is available in the MapContext? Or alternatively, any way to use something in the MapContext.EventManager to also register an event listener in the overlay component, so it can know when to make itself visible?
