### ISSUE TITLE
webpack parse error on overlays

### ISSUE THREAD

**Issue by Jinnified** [uber/react-map-gl#107]
Hi, 

i was able to run the basic map in my small webpack react boilerplate code, with the following web pack config:
`module: {
    // Loader required for JSX
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        query:{
          plugins: ['transform-decorators-legacy']
        },
        loader: 'babel'
      },
      {
        test: /\.js$/,
        include: path.resolve('node_modules/mapbox-gl-shaders/index.js'),
        loader: 'transform/cacheable?brfs'
      },
      {
        test: /\.js$/,
        include: path.resolve(__dirname, 'node_modules/webworkify/index.js'),
        loader: 'worker'
      },
      {
        test: /\.css$/,
        loader: "style-loader!css-loader"
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      }
    ],
    noParse: [/autoit\.js$/],
    postLoaders: [
      {
        include: /node_modules\/mapbox-gl-shaders/,
        loader: 'transform',
        query: 'brfs'
      }
    ]
  },
  resolve: {
    extensions: ['', '.js', '.jsx'],
    alias: {
      'webworkify': 'webworkify-webpack'
    }
  }`

with tags in react like this:

`<MapGL
          width={1550}
          height={600}
          latitude={20}
          longitude={110}
          zoom={11}
          mapboxApiAccessToken={MAP_BOX_TOKEN}
          mapStyle={'mapbox://styles/mapbox/basic-v9'}
        />`

however, after I tried to import ScatterplotOverlay into my module, webpack will throw a parsing error like this: 

`ERROR in ./~/react-map-gl/src/overlays/scatterplot.react.js
Module parse failed: /Users/tester/gl-map/node_modules/react-map-gl/src/overlays/scatterplot.react.js Unexpected token (108:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (108:6)
    at Parser.pp$4.raise (/Users/tester/gl-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/tester/gl-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/tester/gl-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/tester/gl-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/tester/gl-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/tester/gl-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/tester/gl-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/tester/gl-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/tester/gl-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (/Users/tester/gl-map/node_modules/webpack/node_modules/acorn/dist/acorn.js:1796:19)
 @ ./src/coms/Map2.js 29:19-73
`

I had a look at the line 108 in the scatterplot module, it is pointing at `<canvas...`, can anyone please shade some light on this? thanks

**Comment by Jinnified** [comment]
solved by adding this to webpack: externals: ['canvas'],

**Comment by jwarning** [comment]
This may be due to how you are importing the overlay. Are you importing the overlay with:

```import MapGL, {SVGOverlay, CanvasOverlay} from 'react-map-gl'``` 

If you're importing it directly from the src directory it won't have been correctly transpiled yet.

**Comment by Jinnified** [comment]
i did import ScatterplotOverlay from 'react-map-gl/src/overlays/scatterplot.react' after 
import MapGL, {SVGOverlay, CanvasOverlay} from 'react-map-gl'

still getting the same error

**Comment by garrettqmartin8** [comment]
@jwarning I'm trying to import the `ScatterPlotOverlay` with that import syntax, but `ScatterPlotOverlay` is returning undefined.

**Comment by ibgreen** [comment]
@garrettqmartin8  as @jwarning says, your app should be importing from the transpiled `dist` directory, but your logs clearly show that your app is using overlays from the `src` directory. This is a recent change in react-map-gl, see [CHANGELOG](https://github.com/uber/react-map-gl/blob/master/CHANGELOG.md#breaking-change-layer-imports). If you have updated all your overlay imports (maybe you have more than one of them?) then perhaps something in your webpack config?

**Comment by ibgreen** [comment]
@garrettqmartin8 - On a second look, I think this is a separate issue. This could be related to the way babel transpiles default exports (it puts the exported data in a `default` field on the returned object which confuses non-babel apps).

To confirm this, you could try and see if referencing `ScatterPlotOverlay.default` works for you. Are you using react-map-gl v1.2.0? If so you are welcome to open a separate issue on this (Issue with ES6 default exports on overlays).

Closing as the original issue was solved.

**Comment by Jinnified** [comment]
thanks for the reply guys,  using @jwarning 's answer fixed it

import MapGL, {SVGOverlay, CanvasOverlay} from 'react-map-gl'
