### ISSUE TITLE
Error: Layer type changed

### ISSUE THREAD

**Issue by Khangng7** [uber/react-map-gl#1075]
Please help me to solve this problem. First, my map will display cluster but I want to add heatmap. So I add a button to handle when to show heatmap. However, there is an error as the title. My heatmap style and cluster style is the same as the demo.
Here is my code: 
`if (!this.state.showHeatmap) {
        return (
          <Source
            type="geojson"
            data={this.state.dataGeo}
            cluster={true}
            clusterMaxZoom={14}
            clusterRadius={60}
            ref={this._sourceRef}
          >  
            <Layer {...clusterLayer} />
            <Layer {...clusterCountLayer} />
            <Layer {...unclusteredPointLayer} />
          </Source>
        )
      } else {
        return (
          <Source
            type="geojson"
            data={this.state.dataGeo}
            ref={this._sourceRef}
          >  
            <Layer {...heatmapLayer} />
          </Source>
        )
      }`

**Comment by Khangng7** [comment]
My solution is just simply moving cluster and heatmap into two files and importing into main file.

**Comment by Pessimistress** [comment]
Use the [key](https://reactjs.org/docs/lists-and-keys.html#keys) prop.
