### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by gazpachu** [uber/react-map-gl#110]
I'm not sure if this is a react-map-gl, mapbox-gl or webworkify issue, but I'm stuck. In the webworkify repo they say it's a mapbox-gl version issue but I'm not sure: https://github.com/borisirota/webworkify-webpack/issues/18

<img width="793" alt="screen shot 2016-08-15 at 14 21 56" src="https://cloud.githubusercontent.com/assets/1721288/17665549/92d5433e-62f3-11e6-931c-a81db0fb8f81.png">

**Comment by borisirota** [comment]
@gazpachu can you show the line of the error (in non minified node) ?

**Comment by gazpachu** [comment]
With v1.1.7:

<img width="752" alt="screen shot 2016-08-15 at 14 46 38" src="https://cloud.githubusercontent.com/assets/1721288/17666224/1c7422ec-62f7-11e6-8545-e97b18cbda66.png">

With v1.1.3:

<img width="840" alt="screen shot 2016-08-15 at 14 50 56" src="https://cloud.githubusercontent.com/assets/1721288/17666316/9f421b84-62f7-11e6-925c-31bc3764ea98.png">

**Comment by gazpachu** [comment]
The thing is, with v1.1.3, the map seems to be loading (at least I can see a grey placeholder) but with v1.1.7, it doesn't load anything

**Comment by borisirota** [comment]
@gazpachu check my comment [here](https://github.com/borisirota/webworkify-webpack/issues/18#issuecomment-239811448).

**Comment by gazpachu** [comment]
Ok, fixed when removed devtool: 'eval',

**Comment by jpdevries** [comment]
I'm running into this when using `create-react-app`. I'm not sure if it possible to change the `devtool` config without ejecting.

**Comment by Apercu** [comment]
CRA is intended to be 0 config. Since mapbox requires some changes in the webpack config, you won't be able to use it without ejecting.
