### ISSUE TITLE
Create example that bundles react-map-gl using webpack

### ISSUE THREAD

**Issue by ibgreen** [uber/react-map-gl#112]
react-map-gl is only tested using browserify, and unfortunately it appears to be non trivial getting react-map-gl and mapbox-gl-js working with webpack.

While we are not ready to commit to formal support for webpack, it would be great to have an example that could serve as a starting point for webpack users.

**Comment by owap** [comment]
FYI, Mapbox has posted their official Webpack config that contains all the loaders needed to get Mapbox GL JS working in Webpack:

https://github.com/mapbox/mapbox-gl-js/blob/master/webpack.config.example.js

I was getting errors on the page before adjusting my config to match theirs.  No errors anymore, but also no tiles.  Going to see if setting my `access_token` makes a difference 😉

**Comment by ibgreen** [comment]
@owap - Awesome, I have added this info to the README file.

**Comment by mvaivre** [comment]
So yeah, MapBox officially ditched the webpack support: https://github.com/mapbox/mapbox-gl-js/pull/3235

Now, we are supposed to require directly the .js file: https://github.com/mapbox/mapbox-gl-js#using-mapbox-gl-js-with-other-module-systems

What would be the best solution to integrate `react-map-gl` now?

**Comment by contra** [comment]
I think the solution is to have react-map-gl import `mapbox-gl/dist/mapbox-gl` instead of `mapbox-gl` - I'll test it on a fork and send a PR if it works out.

**Comment by cammanderson** [comment]
Hi @contra, 
I've had a play and there are some issues. You'll need two aliases for the geo/transform source. There are bigger issues though, moving from 0.25.0 webpack/mapbox uses dist which could create version mismatch issues

**Comment by contra** [comment]
@cammanderson Just sent this in which should fix the webworkify issue - https://github.com/borisirota/webworkify-webpack/pull/21

**Comment by contra** [comment]
Alright, definitive answer -

You can still use the old way! Update webworkify-webpack once https://github.com/borisirota/webworkify-webpack/pull/21 is published and your existing stuff should work fine.

Alternatively, you can remove all of the old hacks and set up an alias which should work in most cases:

```js
resolve: {
  alias: {
    'mapbox-gl/js/mapbox-gl.js': 'mapbox-gl/dist/mapbox-gl.js'
  }
}
```

**Comment by davidhampgonsalves** [comment]
Has anyone gotten @contra 's alias method working(I tried and failed with 1.7)? Transforming `brfs` and `webworkerify-webpack` would still be required correct, are there specific dependancy versions as well?

**Comment by contra** [comment]
@davidhampgonsalves Aliasing should work fine with no other hacks - it's two separate methods.

**Comment by davidhampgonsalves** [comment]
Thanks @contra. I couldn't get that working but was able to with
```
    alias: {
      'mapbox-gl/js/geo/transform': path.join(__dirname, "mapbox-gl/js/geo/transform"),
      'mapbox-gl': path.join(__dirname, "mapbox-gl/dist/mapbox-gl.js")
    }
```
I added the transform alias to handle https://github.com/uber/react-map-gl/blob/master/src/utils/transform.js#L23

**Comment by gaving** [comment]
my head is spinning with this stuff, I've tried aliasing the above to get react-map-gl going with webpack, but all I'm getting is:-

     index.js:9 Uncaught TypeError: Cannot convert undefined or null to object

From `webpack:///./~/mapbox-gl/~/webworkify/index.js?`. My hunting has then led me to https://github.com/borisirota/webworkify-webpack/issues/18 (where the author has posted a recent update regarding v2).

Does the webworkify dependency need to be bumped now? Has anyone got an up-to-date gist or something of this working?

😄 🔫

**Comment by davidhampgonsalves** [comment]
@gaving If you are getting that error then `webworkify` is probably being bundled which in my experience is a sign that the `mapbox-gl-js` src is being used rather then the prebuild dist. To debug I deleted the contents of `node_modules/mapbox-gl/js/` since most of that isn't needed and then followed those errors. Using just the above aliases is currently working for me (you would probably need to adjust your paths) on 1.7.0.

**Comment by gaving** [comment]
@davidhampgonsalves 👍 Thanks for the tip, this got things working.

Turns out the paths weren't resolving correctly (I'm using nwb and had stripped out __dirname thinking substituting './node_modules' would do it, but it turns out you need the full absolute path). Paths didn't need adjusted.

Thanks again for the heads up, been a good couple of hours getting to the bottom of that!

**Comment by cpietsch** [comment]
worked for me
`alias: {
      'mapbox-gl/js/geo/transform': path.join(__dirname, "/node_modules/mapbox-gl/js/geo/transform"),
      'mapbox-gl': path.join(__dirname, "/node_modules/mapbox-gl/dist/mapbox-gl.js")
    }`

**Comment by kachkaev** [comment]
@cpietsch which version of `mapbox-gl` were you using? I've tried your solution got this:

```
ERROR in ./~/mapbox-gl/js/util/util.js
Module parse failed: /home/lhrazk/-/projects/wb/1611-civitas-portal/web/node_modules/mapbox-gl/js/util/util.js Unexpected token (15:35)
You may need an appropriate loader to handle this file type.
|  * @private
|  */

| exports.easeCubicInOut = function(t: number): number {
|     if (t <= 0) return 0;
|     if (t >= 1) return 1;
 @ ./~/mapbox-gl/js/geo/transform.js 6:11-34
 @ ./~/react-map-gl/dist/utils/transform.js
 @ ./~/react-map-gl/dist/map.react.js
 @ ./~/react-map-gl/dist/index.js
 @ ./~/react-map-gl/index.js
```

This may be caused [by the introduction of flow](https://github.com/mapbox/mapbox-gl-js/commit/b1e23e6b99c8461c17d7d66af7912f572f7a9797) in `mapbox-gl`. Any thoughts?

**Comment by Apercu** [comment]
For all the folks that followed this issue, please note that a [working webpack example](https://github.com/uber/deck.gl/tree/master/exhibits/webpack) can be found in the deck.gl repo. I will land a PR soon to reference this in the Readme.

Sorry for the wait! 😁

**Comment by Shadowman4205** [comment]
I am trying use this package but i get this error 

> Error: Cannot find module 'gl'
, i searched in issues but cannot get it solved
I try use it with react starter kit

**Comment by ibgreen** [comment]
> Error: Cannot find module 'gl'

You should not see this error in the browser. If you are trying to run mapbox-gl in node, it will try to load `gl` (headless-gl, a webgl implementation for Node.js). Just `yarn add gl` or `npm install --save gl` and try again (you may also need to install `jsdom` and `sinon`).

**Comment by abmai** [comment]
@Shadowman4205 what version of `react-map-gl` are you installing?

**Comment by G2Jose** [comment]
@Apercu That link seems to be broken - https://github.com/uber/deck.gl/tree/master/exhibits/webpack

**Comment by Apercu** [comment]
@G2Jose Thanks, link updated

**Comment by Shadowman4205** [comment]
@ibgreen My brain is going to explode. I tried ur solution but i get errors on installing gl i am getting this  [error](https://github.com/stackgl/headless-gl/issues/96).
Then i tried using this approach in my application
```
class Map extends React.Component {
    render() {
        var MapGL = require('react-map-gl');
        if (process.env.BROWSER) {
            return (
                <div>Browser</div>
            )
        }
        else { return <div>Test</div> }
    }
}
```

@abmai  i installed last version.

**Comment by abmai** [comment]
@Shadowman4205 last version being `v3-alpha` or `v2.0.3`? 

The `webpackJsonp` seems like a webpack-related issue, are you building your whole application using webpack?

FWIW - you should try the following, in order to get around requiring `gl` because of server-side rendering (if you're doing any of that).

```js
const isBrowser = require('is-browser'); // npm package

var MapGL = 'div';
if (isBrowser) {
  MapGL = require('react-map-gl);
}

class Map extends React.Component {
  render() {
    return (
       <MapGL ... />
    )
  }
}
```

**Comment by Shadowman4205** [comment]
@abmai 
I am using 2.0.3 version.
Yeah i am using webpack for more specific i have used react starter kit. 
I tried this package "is-browser" but still same with >process.env.BROWSER

**Comment by Apercu** [comment]
`is-browser` is browserify specific and won't work in webpack. You need to use something else, like  the `BROWSER` env maybe if you use the [webpack define plugin](https://webpack.js.org/plugins/define-plugin/) (but be careful of the real `BROWSER` variable), or check `window` (also be careful if you intent to mock it with something like jsdom for the tests)

**Comment by calocan** [comment]
I'm trying to use the react-map-gl module with Webpack 2 but without babel (to avoid debugging wiht sourcemaps). I followed the instructions and have 

`alias: {
            'mapbox-gl$': resolve('./node_modules/mapbox-gl/dist/mapbox-gl.js'),
  },`

in my webpack.config.js. When I start webpack I get the following error:

`ERROR` in ./node_modules/mapbox-gl/js/geo/coordinate.js
Module parse failed: /Users/andy/code/rescape_ramble/node_modules/mapbox-gl/js/geo/coordinate.js Unexpected token (14:10)
You may need an appropriate loader to handle this file type.
|  */
| class Coordinate {
|     column: number;
|     row: number;
|     zoom: number;
 @ ./node_modules/mapbox-gl/js/geo/transform.js 5:17-40
 @ ./node_modules/react-map-gl/dist/utils/transform.js
 @ ./node_modules/react-map-gl/dist/map.react.js
 @ ./node_modules/react-map-gl/dist/index.js
 @ `./node_modules/react-map-gl/index.js`

Does anyone know why react-map-gl's import of mapbox-gl is not aliasing to ./node_modules/mapbox-gl/dist/mapbox-gl.js? It seems like webpack should correctly process the import and avoid using the mabox source with the typescript in it. Thanks.

**Comment by ibgreen** [comment]
@calocan Looks like you are using react-map-gl v2. This has been fixed in v3.

**Comment by calocan** [comment]
Thanks, I missed that update. That fixed it.
