### ISSUE TITLE
use diffSyles from the mapbox-gl-style-spec

### ISSUE THREAD

**Issue by vicapow** [uber/react-map-gl#116]
Replace the existing style diff mechanism with `diffStyles` from [mapbox-gl-style-spec](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/API.md#diffstylesbefore-after). This should improve style update performance and prevent the "flicker" that can sometimes happen.

**Comment by vicapow** [comment]
https://github.com/mapbox/mapbox-gl-style-spec/issues/486 should probably land before moving forward with this

**Comment by abmai** [comment]
@vicapow is this still an outstanding thing you'd like to see done?

**Comment by vicapow** [comment]
Yep

**Comment by Pessimistress** [comment]
Tracked by https://github.com/uber/react-map-gl/issues/561
