### ISSUE TITLE
Overlay imports fail in v1.4.2 (Webpack, ES6)

### ISSUE THREAD

**Issue by davidkell** [uber/react-map-gl#120]
I'm using the react-map-gl framework with webpack.
I've successfully configured webpack to load the map and can see it in the browser.

However none of the overlays import successfull- and weirdly they fail for two separate reasons-

ScatterplotOverlay fails:

```
ERROR in ./~/react-map-gl/src/overlays/scatterplot.react.js
Module parse failed: <dir>/node_modules/react-map-gl/src/overlays/scatterplot.react.js Unexpected token (112:6)
You may need an appropriate loader to handle this file type.
```

Line 112 refers to `<canvas>` jsx tag.
Not sure where this tag is coming from?

SVGOverlay fails:

```
ERROR in ./~/react-map-gl/src/overlays/svg.react.js
Module parse failed: <dir>/node_modules/react-map-gl/src/overlays/svg.react.js Unexpected token (42:6)
You may need an appropriate loader to handle this file type.
```

Line 42: `...this.props.style`
Perhaps the triple dot ES6 syntax is the issue here?

It may be I haven't configure ES6 support properly or something- I would really really appreciate any help with this! Thanks!

Update: when I clone the repo and do `npm install; npm start` all the examples work.
Suggests this is a webpack issue, but the error messages are quite unusual?

**Comment by davidkell** [comment]
Update: if I clone and

**Comment by ibgreen** [comment]
>none of the overlays import successfully

@davidkell See [CHANGELOG](https://github.com/uber/react-map-gl/blob/master/CHANGELOG.md#breaking-change-layer-imports).

**Comment by ibgreen** [comment]
> That solves it- thanks. Please can you update the readme.md accordingly? That's what lead me astray.

@davidkell - README updated. Thanks for catching!
