### ISSUE TITLE
Interactivity (dragging, zooming, etc) broken when bearing≠0 and pitch=0

### ISSUE THREAD

**Issue by mike-marcacci** [uber/react-map-gl#123]
It appears that while the `react-map-gl` component accepts a `bearing` and renders the map correctly, the interactivity layer doesn't take it into account.

A bearing of 180, for example completely inverts the controls. Hopefully a simple fix!

**Comment by ibgreen** [comment]
> A bearing of 180, for example completely inverts the controls

@mike-marcacci We haven't seen any issues with bearing, would need more information on this issue to be able to help.

- Running npm start in the repo, the top example is perspective enabled. I can rotate it many times (by holding command key and sweeping left or right multiple times) without issue. Also, its starting state is bearing 180.

- Just to check expectations: The perspective controls are intended to be very simple - dragging up/down increases the pitch, and dragging left/right does the same to the bearing. The direction of the controls are not dependent on current pitch and bearing.

**Comment by mike-marcacci** [comment]
I can reproduce this behavior in the example, but it looks like the pitch must be set to 0 for the issue to appear:

![vid](https://cloud.githubusercontent.com/assets/690517/18492277/422730a4-79bf-11e6-9d69-60a8e6cb1ff0.gif)

**Comment by shaojingli** [comment]
@mike-marcacci @ibgreen I can't reproduce this issue... is this still an issue in our newly refactored event handling?

**Comment by mike-marcacci** [comment]
Hi @shaojingli! Thanks for the followup – I actually moved to using MapboxGL directly from a custom component, since we needed direct access to several of its API methods anyhow, so I don't have a current setup to test this.

I'm happy closing this, and someone else can reopen if they discover the issue with the refactored event handling.

Cheers!
