### ISSUE TITLE
touchend event triggered for incorrect position

### ISSUE THREAD

**Issue by forrert** [uber/react-map-gl#139]
I believe the `touchend` event handler should be using the `changedTouches` property on the `event` rather than the `touches` property. 

I noticed that the `onTouchTap` handler is always called with position 0 / 0 because the `touches` property is always an empty array during the `touchend` event (compare: [The `touchend` event](https://www.w3.org/TR/touch-events/#dfn-touchend)). I think the [`_onTouchEnd`](https://github.com/uber/react-map-gl/blob/master/src/map-interactions.react.js#L183-L192) handler should use the `changedTouches` property instead to find the coordinates of the tap.

Note that this bug does not seem to manifest when tested on android devices, since there are (correct) mouse events triggered following the (incorrect) touch events.

**Comment by abmai** [comment]
@forrert did you come up with a solution for this? Can you open a PR if so?
