### ISSUE TITLE
Toggling the onChangeViewport removes map from dom

### ISSUE THREAD

**Issue by Vednus** [uber/react-map-gl#143]
It would be nice to be able to enable and disable interactivity, but when I either remove the onChangeViewport attribute or set it to null, the map disappears from the dom, although the overlay I'm using stays.

**Comment by cammanderson** [comment]
Could you swap to a blank map style?

**Comment by Vednus** [comment]
If I switch styles by changing the style url saved in my state, then the map also disappears. Is that what you mean? I just want to be able to toggle the interactivity on and off.

**Comment by Apercu** [comment]
@Vednus same thing using a noop callback?

**Comment by Vednus** [comment]
using noop worked once I updated to the latest version. Thanks for the advice.

**Comment by Apercu** [comment]
np

**Comment by Vednus** [comment]
spoke too soon. Noop callback stops the interaction, but the map is still hijacking the scroll event. It's better, but not ideal since the whole point of disabling interaction is often to enable scrolling of the page.

**Comment by Apercu** [comment]
Have you tried using `null` against the newer version?

**Comment by Vednus** [comment]
If I use null, the same thing happens as before, the map disappears and the overlay stays

**Comment by shaojingli** [comment]
I believe setting onChangeViewport to null works now after the recent refactoring.
