### ISSUE TITLE
Add props for onDragStart and onDragEnd for DraggablePointsOverlay 

### ISSUE THREAD

**Issue by yangshun** [uber/react-map-gl#149]
Hi there, I realized that `onDragStart` and `onDragEnd` events are not exposed for `DraggablePointsOverlay`. Would you all be open to receiving a PR that adds in these two props? 😄 

Reference: https://github.com/uber/react-map-gl/blob/master/src/overlays/draggable-points.react.js#L78-L101

**Comment by abmai** [comment]
hey @yangshun - we'd love a PR for this if you already have it implemented somewhere.

**Comment by shaojingli** [comment]
While this is a good feature to have, we plan to move all overlays from core features to examples

**Comment by ibgreen** [comment]
DraggablePointsOverlay has been moved to examples. We could still accept a PR.
