### ISSUE TITLE
Bug: map.react.js _onMouseDrag is passing an array as LngLat to transform.js when it is expecting an object.  Dragging the map causes an Exception. 

### ISSUE THREAD

**Issue by xinghengwang** [uber/react-map-gl#168]
The map loads fine, and my data (locations) are rendered overlay on the map fine. Zoom works fine. However, when I drag it it result in an exception: 

Error: Invalid LngLat object: (NaN, NaN) at new LngLat (http://localhost:3001/dist/main-e23bee3c125c3849e1f6.js:232721:20) at Transform.coordinateLocation (http://localhost:3001/dist/main-e23bee3c125c3849e1f6.js:232369:21) at Transform.setLocationAtPoint (http://localhost:3001/dist/main-e23bee3c125c3849e1f6.js:232319:33) at MapGL._onMouseDrag (http://localhost:3001/dist/main-e23bee3c125c3849e1f6.js:227384:18) at MapInteractions._onMouseDrag (http://localhost:3001/dist/main-e23bee3c125c3849e1f6.js:231615:21)

The code is almost exact at one of the examples 
[scatter plot example ](https://github.com/uber/react-map-gl/blob/master/example/examples/scatterplot.react.js)

In my  component: 

```

  constructor(props) {
    super(props);

    this.state = {
      viewport: Object.assign({
        zoom: 7,
        startDragLngLat: null,
        isDragging: false
      }, props)
    };
    this._onChangeViewport = this._onChangeViewport.bind(this);
  }

  _onChangeViewport(opt) {
    const { viewport } = this.state;
    if (!opt.isDragging) { 
        // snip
        // I do my own data updates based on viewport
        // I only want to do data updates once user stopped dragging. 
        // or else I assume it is possible it may result in too many fetches. 
    }

    // here I decided to use prevState => newState 
    // approach in case of race condition.
    this.setState(prevState => ({
      viewport: Object.assign(
        prevState.viewport,
        {
          latitude: opt.latitude,
          longitude: opt.longitude, 
          zoom: opt.zoom,
          startDragLngLat: opt.startDragLngLat,
          isDragging: opt.isDragging
        })
    }));
  }

  render() {
    const { viewport, data } = this.state;

    const locations = processData(data) || []; 
    // I put a breakpoint here. the data all seems correct. 

    return (
      <MapGL { ...viewport } onChangeViewport={this._onChangeViewport}>
        <ScatterplotOverlay
            { ...viewport }
            locations={ locations }
            dotRadius={ 2 }
            globalOpacity={ 1 }
            compositeOperation='screen'/>
      </MapGL>
    )
  }

```

Any idea why this is the case?

**Comment by ibgreen** [comment]
@xinghengwang 
You have added asynchronous `setState` updates, plus an override when `isDragging` === false - things we have not tested. It seems like it would be pretty easy for you to disable these one by one and see which one causes the issue?

Also, if neither of those works, try to just hold on to, and pass back the entire viewport object you receive in onChangeViewport, rather than selectively picking fields. It can contain "extra" keys (mainly if you use perspective mode, which you don't, but worth trying if you have problems after disabling the above steps).

**Comment by xinghengwang** [comment]
I stripped down to bare minimum. 

```
  _onChangeViewport(opt) {
    const { viewport } = this.state;
    this.setState({
      viewport: Object.assign(viewport, opt)
    });
  }

  render() {
    const { viewport } = this.state;

    
    const locations = [];
    // I am not even using any data anymore. 

    return (
      <MapGL { ...viewport } onChangeViewport={this._onChangeViewport}>
        <ScatterplotOverlay
            { ...viewport }
            locations={ locations }
            dotRadius={ 2 }
            globalOpacity={ 1 }
            compositeOperation='screen'/>
      </MapGL>
    )
  }
```

Still the issue still happens, not sure what I could be doing wrong.

**Comment by xinghengwang** [comment]
So I think this is causing the issue: 

In map.react.js for _onMouseDrag()
You try to call transform.setLocationAtPoint(this.props.startDragLngLat, pos)
As you can see, the LngLat you are passing in is an array with two elements. 
<img width="1156" alt="screen shot 2017-01-05 at 11 19 27 pm" src="https://cloud.githubusercontent.com/assets/6666687/21710444/882bbe52-d39d-11e6-9ede-fef8aa7d4c8f.png">

I believe that Transform.js is expecting the LngLat argument to be an object instead. (It is expecting an object with a lng and lat keys. )

See here:: in transform.js setLocationAtPoint(LngLat, point)
<img width="1163" alt="screen shot 2017-01-05 at 11 26 00 pm" src="https://cloud.githubusercontent.com/assets/6666687/21710548/5c428e32-d39e-11e6-8bfd-da01f170a6ef.png">

it calls this.locationCoordinate(lnglat) and pass in the argument that is passed in by _onMouseDrag()
but in that function, it is trying to extract the lng and lat out as keys. since the argument passed in is an array, so it turns into NaN. 

<img width="1162" alt="screen shot 2017-01-05 at 11 27 48 pm" src="https://cloud.githubusercontent.com/assets/6666687/21710604/bcbb2f08-d39e-11e6-9d78-e3086fdb4e51.png">

Since I believe onMouseDrag is part of react-map-gl, 
I think this is an bug with it.

Why have no one reported/encountered this issue? 
This is my react-map-gl version:    "react-map-gl": "^1.7.2",

Thanks,

**Comment by abmai** [comment]
@xinghengwang I'm seeing this issue when I'm updating to mapbox-gl-js `0.29.0` - can you do an `npm ls mapbox-gl` and make sure you're still on `0.26.0`?

I'm working on a fix alongside w/ updating the library to use version `0.29.0`

**Comment by abmai** [comment]
This should be fixed along with an official support for `0.29.0` in #171 - will update again once we cut a release.

**Comment by kingshitonly** [comment]
U guys r the worst people ever u guys r not slick u nigga need to get a life and fuck all of u guys

**Comment by kingshitonly** [comment]
U guys r so lame
