### ISSUE TITLE
Dev branch examples not compat with react <= 0.14.0

### ISSUE THREAD

**Issue by amilajack** [uber/react-map-gl#180]
[The examples use `ReactDOM.render()` directly instead of checking for compatibility first](https://github.com/uber/react-map-gl/blob/dev/examples/choropleth-overlay/app.js#L45)

Maybe [a backwards compat solution, like this example](https://github.com/amilajack/react-vis/blob/refactor-doc-examples/src/example/legends/app.js#L73-L89), should be used. I can make a PR for this

**Comment by abmai** [comment]
@ibgreen any thoughts on making this backwards compatible with react 0.14 and under?

**Comment by amilajack** [comment]
Here's an example from another repo:

https://github.com/uber/react-vis/blob/master/src/example/main.js#L283-L292

**Comment by Apercu** [comment]
I don't get the point of using old react versions in our examples, we control the versions, it's not part of the library.

**Comment by ibgreen** [comment]
> any thoughts on making this backwards compatible with react 0.14 and under?

@abmai @amilajack @apercu We don't have an official support statement for `react-map-gl`, but here's my take:
- I think that supporting the previous major version of react, at least for a while, is a reasonable goal, which currently means 0.14.x and 15.x, although we are now far enough into the 15.x cycle that the value of 0.14 support is becoming debatable.
- That goes for the `react-map-gl` component itself. The examples do not need to be written to support old react versions. Examples are intended to get people off to a good start and should generally use the latest components available.
- That said, how can we be sure that `react-map-gl` supports an old version of react, if all our apps and examples are using the latest version?
- Maybe we should keep one example on the previous release? Now that we have a unique package.json for every example it seems feasible.

Does this sound reasonable?

**Comment by abmai** [comment]
I am open to keeping one example purely to demonstrate that this would work with React v0.14 (for now) - but you're both right that our examples are to demonstrate the library and we don't have any obligation there to use anything but the latest version of React.

I also don't think we should make 0.14 compatibility a focus for `dev` and future releases of `react-map-gl` after that. At this point in time, `0.14.0` is almost a year old (and most likely will be when `dev` becomes `master`). I'd rather us only "officially" support React >= v15.0.0 going forward. With the way that development is happening on React, who knows when the next "major" release is going to be.

Thoughts? Our react layer is pretty thin anyway so chances are things will work well with `0.14.0` even if we don't go out of our way to optimize for it.

**Comment by amilajack** [comment]
Didn't know that `0.14.0` isnt officially supported. Thanks for clarifying.
