### ISSUE TITLE
v2.0.0 dist folder missing

### ISSUE THREAD

**Issue by olafurr** [uber/react-map-gl#184]
I installed the latest 2.0.0 release from npm and the dist folder seems to be missing.

Am I missing something obvious or is it possible ?

PS. Love your lib, job very well done!

**Comment by abmai** [comment]
Seems like something went wrong with our publish process. Working to fix now, sorry!

**Comment by abmai** [comment]
@olafurr what version of node + npm are you using?

**Comment by Apercu** [comment]
Could you please give us your versions and the way you installed it (it there was something special about it)?

**Comment by olafurr** [comment]
node v7.4.0
npm v4.0.5

Thank you

**Comment by Apercu** [comment]
Don't have any issue with these, did you do something special while installing?

**Comment by olafurr** [comment]
Seems to work now. Strange...

Sorry for the inconvenience.

**Comment by abmai** [comment]
No worries! Thanks for confirming!
