### ISSUE TITLE
[Bug] Markers not appearing in their places and randomly sliding through the map instead

### ISSUE THREAD

**Issue by xijdk** [uber/react-map-gl#1845]
### Description

When I'm trying to render a marker on the map, they appear in random places and start randomly sliding through the map as I scroll it. Video demonstrates how it looks.

https://user-images.githubusercontent.com/46359576/165318758-79ac4a08-a572-46ab-9ce0-2b42346b6771.mov

### Expected Behavior

Markers appearing in places they should.

### Steps to Reproduce

https://codesandbox.io/s/condescending-resonance-4lhujv

### Environment

- Framework version: react-map-gl@7.0.11
- Map library: maplibre-gl@2.1.9
- Browser: Safari 15.4
- OS: macOS 12.3.1

**Comment by Pessimistress** [comment]
> The current mapbox-gl release requires its stylesheet be included at all times. The marker, popup and navigation components in react-map-gl also need the stylesheet to work properly.

https://visgl.github.io/react-map-gl/docs/get-started/get-started
