### ISSUE TITLE
linking `mapbox-gl/dist/mapbox-gl` causes build errors

### ISSUE THREAD

**Issue by glan** [uber/react-map-gl#194]
Version 0.15.0 converted from importing `mapbox-gl` to `mapbox-gl/dist/mapbox-gl`. I'm seeing build (browserify) errors when the later is used, for example: `Cannot find module './program_configuration'`

**Comment by abmai** [comment]
@glan can you elaborate more on what you're doing / your build process? What version of `react-map-gl` are you using?

**Comment by glan** [comment]
@abmai my apologies I'm in the wrong project, this is a `react-mapbox-gl` issue.
