### ISSUE TITLE
Add property to control mapbox classes

### ISSUE THREAD

**Issue by ibgreen** [uber/react-map-gl#196]
We now use styles with themes defined by classes. It would be great to be able to control the theme selection using a prop, i.e. without having to get the map ref and calling the underlying mapbox api. @abmai @Pessimistress 

Current code:
```
_setMapTheme(theme) {
    const map = this.refs.mapbox._getMap();
   map.setClasses([theme]);
}
```
Desired API:
```
<MapGL classes={[theme]} ...>
```

**Comment by Pessimistress** [comment]
Mapbox is planning to deprecate this API in An upcoming version. Our cartography team is in touch with them, for all our internal map styles utilize classes, so this won't happen immediately.

**Comment by abmai** [comment]
It looks like Mapbox is planning to deprecate style classes.

https://www.mapbox.com/mapbox-gl-js/style-spec/#layer-paint.*

**Comment by abmai** [comment]
Gonna close this because I don't think we should add native support for a feature that's going to be deprecated.
