### ISSUE TITLE
API consistency: onClick available, but no onMouseMove

### ISSUE THREAD

**Issue by dcposch** [uber/react-map-gl#199]
I just read through the code. It looks like it would be easy to expose mouse events. Users could then specify optional props for `onMouseMove` and other mouse events to implement picking and hovering.

**Comment by abmai** [comment]
Thanks for creating the issue, @dcposch! Are you just looking to get to the regular `event` object for `onMouseMove`? We do have a `onHoverFeatures` prop you can pass in that will be called with queried features as you move the mouse cursor.

**Comment by dcposch** [comment]
I think it should be symmetric with `onClick`, which calls back with a `latLng` object `{lat:..., lng:...}`.

This is different from `onHoverFeatures`, which returns *map features*. I want to be able to do the picking myself, using `onHover` for hover and `onClick` for select.

I don't want to pick mapbox features - I want to pick my own features from layers rendered on top of mapbox.

**Comment by abmai** [comment]
Ah. That makes sense! Can you please make a PR with the changes you think should happen and we can continue from there.

**Comment by abmai** [comment]
@dcposch `v3` (master branch) now has a generic `onHover` prop. Does that work for you here?

**Comment by dcposch** [comment]
👍

**Comment by abmai** [comment]
Awesome. Thanks!
