### ISSUE TITLE
Can't build project from dev branch: restricted access to internal uber npm repo

### ISSUE THREAD

**Issue by stepankuzmin** [uber/react-map-gl#200]
Hi there! Then I'm trying to build project from dev branch I'm getting an unexpected error: 

```
"https://unpm.uberinternal.com/buble/-/buble-0.15.2.tgz: Request failed \"401 Unauthorized\"".
```

Although I'm not sure is this issue should belong here.

**Comment by stepankuzmin** [comment]
Mea culpa, it seems that this issue occurs only when using yarn.

**Comment by Apercu** [comment]
No, you were right, it was an issue. It's fixed now, you can use yarn.
Thanks for the report

**Comment by ibgreen** [comment]
@apercu In deck.gl I have tried to detect this before we check in by using something like
```
    "lint": "eslint src test examples && npm run lint-yarn",
    "lint-yarn": "!(find . -name yarn.lock -exec grep -l unpm.u {} \\; | egrep '.*')",
```
Haven't done a lot of testing. Would be good to verify that this works and add to all our repos to make sure we don't check in `yarn.lock` files that don't work for external folks.

**Comment by Apercu** [comment]
I would say adding a script that does

```
perl -pi -e 's/unpm\.uberinternal\.com/registry\.yarnpkg\.com/g' `find . -name yarn.lock`
```

and running it after the build / before the publish seems better to me

**Comment by ibgreen** [comment]
>  [perl script] seems better to me

That sounds fine. I have no strong opinions on the script itself, the more platform independent it is, the better (it is great if the script doesn't break on Windows, etc). My main goal is that we verify that it catches the errors it is supposed to, and we adopt it across our major open source repos.

> and running it after the build / before the publish seems better to me

Yep, fine, as long as the broken lock files don't end up on github we are good. That said, the issue doesn't have a strong relation to the `publish` step (the yarn.lock files aren't published) - it seems to me that it is more a `precommit`/`prepush` thing.

**Comment by Apercu** [comment]
Oh yeah yeah pre-commit indeed. Will adapt it so it does nothing on Windows (we don't have any internals on it anyway) and send it back to you
