### ISSUE TITLE
Missing dependency global

### ISSUE THREAD

**Issue by jdeerhake** [uber/react-map-gl#203]
Working on the latest version (3.0.0-alpha.4, ref `17d05fd`) I'm getting an error trying to compile in webpack:

```
ERROR in ./~/react-map-gl/dist/utils/event-manager.js
Module not found: Error: Can't resolve 'global/document' in '/Users/jdeerhake/project/frontend-web/node_modules/react-map-gl/dist/utils'
 @ ./~/react-map-gl/dist/utils/event-manager.js 34:16-42
 @ ./~/react-map-gl/dist/components/map-controls.js
 @ ./~/react-map-gl/dist/index.js
 @ ./components/map.jsx
 @ ./containers/map-container.jsx
 @ ./containers/search.jsx
 @ ./app.jsx
```

Seems it's just a missing dependency 'global' in the package.json.  Would be happy to PR, but I assume it's not worth the overhead.

**Comment by ibgreen** [comment]
Whoops... We are trying to minimize external dependencies, in particular remove micro modules like `global`. We have an internal replacement, I clearly forgot to update `import 'global'` in all places. 

For now you can just install it yourself in your app and react-map-gl should be able to find it during bundling.

I'll open a PR. Just be aware that v3 is still a buggy alpha release.

**Comment by ibgreen** [comment]
alpha.5 is out. Enjoy!
