### ISSUE TITLE
Examples fail to run on master with a 'buble-loader' error

### ISSUE THREAD

**Issue by chrismanderson** [uber/react-map-gl#207]
Having a problem running the examples on the master branch.

`npm install` and `npm test` both succeed (or appear to, still a bit of a npm newbie.

But when I run `npm start`, I get the error

```
ERROR in multi (webpack)-dev-server/client?http://localhost:8082 webpack/hot/dev-server ./app.js
Module not found: Error: Can't resolve 'buble-loader' in '/Users/chris/code/react-map-gl/examples/custom-interactions'
 @ multi (webpack)-dev-server/client?http://localhost:8082 webpack/hot/dev-server ./app.js
```

Happy to provide any other debug information as needed!

**Comment by ericsoco** [comment]
`npm start` from the root isn't currently set up to install dependencies (to run `npm install`) inside the example it's trying to run. Two ways to fix it:

```
cd examples/custom-interactions
npm i
```

Or just pull master after we merge #208 -- I just updated the root `npm start` script to do that for you.

Sorry about that!
