### ISSUE TITLE
[Bug] Circle Layer changes size when zooming in and out

### ISSUE THREAD

**Issue by MRL-00** [uber/react-map-gl#2075]
### Description

I have a basic Source with a Layer inside of it rendering a circle on the screen.
When I zoom into the map, the circle also changes size. Is there a way to make it so the circle dimensions are static and do not change?

Zoomed Out you can see the area inside the circle
![image](https://user-images.githubusercontent.com/2846782/207490570-3296adfc-0827-4da9-adc5-69691a91d25e.png)

When I zoom in, you can see the area inside the circle has changed meaning the circle radius is potentially being updated when zoomed in?
![image](https://user-images.githubusercontent.com/2846782/207490670-7a54472a-b0e5-4e1f-8a6b-ef1e90886a3f.png)

### Steps to Reproduce

The code below is what I am using

```
'use client'
import * as React from 'react';
import 'mapbox-gl/dist/mapbox-gl.css';
import {Map, Source, Layer, Marker, GeolocateControl, NavigationControl} from 'react-map-gl';
import {seedData} from "../../core/constants/seed";

const geojson = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [174.753476, -36.873301]
      }
    }
  ]
};

export default function MapBoxV2() {
  return <Map
      mapboxAccessToken={process.env.MAPBOX_KEY}
      initialViewState={{
        latitude: -36.91,
        longitude: 174.7,
        zoom: 10
      }}
      style={{width: '100%', height: '100%'}}
      mapStyle="mapbox://styles/mapbox/streets-v9">
    
    <Source maxzoom={0} id="my-data" type="geojson" data={geojson}>
      <Layer type='circle' id='point' paint={{
        'circle-radius': 100,
        'circle-opacity': 0.5,
        'circle-color': '#007cbf',
      }}/>
    </Source>
    <GeolocateControl/>
    <NavigationControl showZoom={true} position='bottom-left'/>
  </Map>
}
```

### Environment

- Framework version: react-map-gl - 7.0.0
- Map library: react-map-gl
- Browser: Chrome
- OS: Windows 10

**Comment by MattL-NZ** [comment]
Ah apologies, will post there now.
