### ISSUE TITLE
Building in webpack throws error

### ISSUE THREAD

**Issue by KyleAMathews** [uber/react-map-gl#21]
```
ERROR in ./~/glify/index.js
Module not found: Error: Cannot resolve module 'fs' in /root/RelateRocket/webapp/node_modules/glify
 @ ./~/glify/index.js 5:9-22
```

**Comment by KyleAMathews** [comment]
The answer apparently is to add some configuration to my webpack config file. It'd be nice if this was documented.

**Comment by gnavvy** [comment]
Known issue: https://github.com/mapbox/mapbox-gl-js/issues/1649

**Comment by shanecav** [comment]
@KyleAMathews What configuration did you add to webpack to make it work? I'm having the same issue.

The fix suggested at mapbox/mapbox-gl-js#1649 (adding `node: { fs: "empty" }` to my webpack config) allowed it to be bundled without errors, but when I view the app in browser I get "Uncaught TypeError: fs.readFileSync is not a function".

**Comment by KyleAMathews** [comment]
Shane, I didn't ever get it to work actually :-)

**Comment by imgettingdeported** [comment]
has anyone been able to build successfully with webpack?

**Comment by lafin** [comment]
I was able.
Need add to webpack config
```
{
  test: /\.json$/,
  loader: 'json-loader'
},
{
  test: /\.js$/,
  include: path.resolve(__dirname, 'node_modules/mapbox-gl/js/render/shaders.js'),
  loader: 'transform/cacheable?brfs'
},
{
  test: /\.js$/,
  include: path.resolve(__dirname, 'node_modules/webworkify/index.js'),
  loader: 'worker'
}
```
and add to package.json 
```
"brfs": "^1.4.3",
"json-loader": "^0.5.4",
"transform-loader": "^0.2.3",
 "worker-loader": "^0.7.0"
```

**Comment by yuvadm** [comment]
@lafin do you have a complete example for that? I've added the config, but I'm still stuck with the `fs.readFileSync` problem.

**Comment by lafin** [comment]
@yuvadm you can see example https://github.com/lafin/frontend-boilerplate all changes https://github.com/lafin/frontend-boilerplate/commit/c75a3f43b0aa322fddce9a8cee90e758db8b8b04 (react-map-gl + heatmap overlay)
For heatmap use forked webgl-heatmap because pull request not apply yet https://github.com/vicapow/webgl-heatmap/pull/1

**Comment by yuvadm** [comment]
thanks for the repo @lafin! unfortunately I can't see any hints as to why this error is still popping up. Any idea where exactly this call is made to the `fs` module?

**Comment by yuvadm** [comment]
It's unclear why despite using

```js
{
  test: /\.js$/,
  include: path.resolve(__dirname, 'node_modules/mapbox-gl/js/render/shaders.js'),
  loader: 'transform/cacheable?brfs'
},
```

I'm still getting

```
ERROR in ./~/react-map-gl/~/mapbox-gl/js/render/shaders.js
Module not found: Error: Cannot resolve module 'fs' in .../node_modules/react-map-gl/node_modules/mapbox-gl/js/render
 @ ./~/react-map-gl/~/mapbox-gl/js/render/shaders.js 3:9-22
```

**Comment by lafin** [comment]
@yuvadm Strange path. Try use
```
{
  test: /\.js$/,
  loader: 'transform/cacheable?brfs'
},
```

**Comment by yuvadm** [comment]
@lafin Yeah I see the problem, react-map-gl is bringing in mapbox-gl as a subdependency, so the paths aren't matching.

**Comment by lafin** [comment]
I updated demo https://github.com/lafin/talks-on-map/tree/dev

**Comment by vicapow** [comment]
Hey @lafin, I tried to run the demo, but I'm getting some errors. Did you miss some deps?

````
Module build failed: ReferenceError: Promise is not defined
````

**Comment by yuvadm** [comment]
@vicapow there might be some polyfill package missing, maybe `es6-promise` or `babel-polyfill`?

**Comment by lafin** [comment]
Maybe. I think, @vicapow has an older version node.

**Comment by lafin** [comment]
I applied travis https://travis-ci.org/lafin/talks-on-map and saw that to build failed for node.js <0.12

**Comment by cezary** [comment]
@shanecav @imgettingdeported @KyleAMathews  @yuvadm I was able to get it working with webpack by replacing mapbox-gl with a webpack-compatible fork I made:

Install cezary/mapbox-gl-js#webpack, worker-loader, shader-loader and json-loader.
In your webpack config file set resolve.alias to
```
{
  'mapbox-gl/js/geo/transform': path.resolve('./node_modules/mapbox-gl/js/geo/transform'),
  'mapbox-gl': path.resolve('./node_modules/mapbox-gl')
}
```
and add
```
{ test: /\.worker.js$/, loader: 'worker', query: { inline: true }},
{ test: /\.glsl$/, loader: 'shader' },
{ test: /\.json$/, loader: 'json' }
```
to your loaders.

The fork hasn't been kept in sync with original, but you can probably replicate the changes I made [here](https://github.com/cezary/mapbox-gl-js/commit/f4f7794454edeba3fa6a255cd4bc96c7f5a254c9).

**Comment by Splact** [comment]
@cezary I tried your solution but with no results. Now I get this message when I execute webpack:
```
ERROR in multi app
Module not found: Error: Cannot resolve 'file' or 'directory' PROJECTROOT\app in PROJECTROOT
 @ multi app
```

Any ideas?

**Comment by joewood** [comment]
Not sure if this was solved, but I'm building with webpack successfully. The config part of interest is:
```javascript
var path = require("path");
var webpack = require("webpack");
var transform = require("transform-loader");

module.exports = {
::  ::
  resolve: {
   ::                ::
        alias: {
            webworkify: 'webworkify-webpack'
        }
    },
    module: {
        loaders: [
            {
                test: /render[\/\\]shaders\.js$/,
                loader: 'transform/cacheable',
                query: "brfs"
            },
            {
                test: /[\/\\]webworkify[\/\\]index.js\.js$/,
                loader: 'worker'
            },
```

I also had to pull in a bunch of dev dependencies:
```json
    "babel-core": "^6.7.6",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "bootstrap-webpack": "^0.0.5",
    "transform-loader": "^0.2.3",
    "webworkify-webpack": "^1.0.6"
```

**Comment by ankitduseja** [comment]
@joewood I followed your webpack config but now I am getting this:
`Error: Cannot find module 'gl'
[1]     at Function.Module._resolveFilename (module.js:438:15)
[1]     at Function._module3.default._resolveFilename (/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:403:34)
[1]     at Function.module._load (/node_modules/piping/lib/launcher.js:24:23)
[1]     at Module.require (module.js:466:17)
[1]     at require (internal/module.js:20:19)
[1]     at Object.<anonymous> (/node_modules/mapbox-gl/js/util/canvas.js:6:10)
[1]     at Module._compile (module.js:541:32)
[1]     at Module._extensions..js (module.js:550:10)
[1]     at require.extensions.(anonymous function) (/node_modules/babel-register/lib/node.js:166:7)
[1]     at Object._module3.default._extensions.(anonymous function) [as .js] (/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:250:71)
`

I see a similar error here: https://github.com/mapbox/mapbox-gl-js/issues/828#issuecomment-77459404

**Comment by tsemerad** [comment]
@ankitduseja I'm getting the same `Cannot resolve module 'gl'` but also `Cannot resolve module 'autobind-decorator'`:

```
ERROR in ./~/react-map-gl/dist/map.react.js
Module not found: Error: Cannot resolve module 'autobind-decorator' in /Users/tanner/Projects/electron-react-boilerplate/node_modules/react-map-gl/dist
 @ ./~/react-map-gl/dist/map.react.js 45:25-54

ERROR in ./~/react-map-gl/dist/overlays/draggable-points.react.js
Module not found: Error: Cannot resolve module 'autobind-decorator' in /Users/tanner/Projects/electron-react-boilerplate/node_modules/react-map-gl/dist/overlays
 @ ./~/react-map-gl/dist/overlays/draggable-points.react.js 36:25-54

ERROR in ./~/react-map-gl/dist/map-interactions.react.js
Module not found: Error: Cannot resolve module 'autobind-decorator' in /Users/tanner/Projects/electron-react-boilerplate/node_modules/react-map-gl/dist
 @ ./~/react-map-gl/dist/map-interactions.react.js 34:25-54

ERROR in ./~/mapbox-gl/js/util/canvas.js
Module not found: Error: Cannot resolve module 'gl' in /Users/tanner/Projects/electron-react-boilerplate/node_modules/mapbox-gl/js/util
 @ ./~/mapbox-gl/js/util/canvas.js 6:9-22
```

**Comment by shanecav** [comment]
@tsemerad I'm also getting the `Cannot resolve module 'autobind-decorator'` error. I had to `npm install --save autobind-decorator` to get it to work.

However I'm not getting the `Cannot resolve module 'gl'` error. See my [comment](https://github.com/mapbox/mapbox-gl-js/issues/1649#issuecomment-221439353) in the corresponding mapbox-gl-js issue.

**Comment by tiagocpontesp** [comment]
Also had to `jspm install npm:autobind-decorator`.

**Comment by tsemerad** [comment]
@shanecav I solved the `Cannot resolve module 'gl'` issue. It turns out my webpack config was setting some of the dependencies that Mapbox GL cares about as `externals`. Updating my `externals` to just a few explicit packages (rather than a function that was auto-generating a list of packages to add to `externals`) fixed it.

**Comment by infacq** [comment]
@tsemerad do you mind sharing your webpack.config

**Comment by calebthebrewer** [comment]
In case any of you are seeing `Cannot read property "call" of undefined` or similar, try grabbing `webworkify-webpack@1.0.6`. This, in addition to Mapbox's own [steps for webpack](https://github.com/mapbox/mapbox-gl-js#using-mapbox-gl-js-with-webpack), did the trick for me. Thanks to [Mike Williamson's blog post](https://mikewilliamson.wordpress.com/2016/02/24/using-mapbox-gl-and-webpack-together/) and the comments therein for pointing it out.

For anyone interested, I only had to add the following to my `webpack.config`:
```js
module.exports = {
  resolve: {
    alias: {
      webworkify: 'webworkify-webpack'
    },
    ...
  },
  module: {
    loaders: [
      {
        test: /\.json$/,
        loader: 'json-loader'
      }, {
        test: /use_program\.js$/,
        loader: 'transform/cacheable?brfs'
      },
      ...
    ],
    postLoaders: [
      {
        include: /node_modules\/mapbox-gl/,
        loader: 'transform',
        query: 'brfs'
      }
    ]
  },
  ...
}
```
I also had to install `gl` as others have suggested.

**Comment by tsemerad** [comment]
@infacq Sorry for the delay. My webpack config is a bit convoluted, but I posted it in a gist here:
https://gist.github.com/tsemerad/41fd8d8c61762b3a48a50e42ce4256c0

**Comment by stupidisum** [comment]
I found myself the smallest change from a webpack config to go through this error, but I got this [sources.map is not a function](https://github.com/borisirota/webworkify-webpack/issues/6) error.
Anybody help me?
```
   resolve: {
+    alias: {
+      webworkify: 'webworkify-webpack'
+    }
   },
loaders = [{
+{
+  test: /mapbox-gl.+\.js$/,
+  loader: 'transform/cacheable?brfs'
+},
]
```

**Comment by kachkaev** [comment]
I've tried adding a simple react-map-gl into a new app using [react-boilerplate](https://github.com/mxstbr/react-boilerplate) but got stuck with an empty single-colour map in dev mode. MWE here: https://github.com/kachkaev/react-boilerplate-react-map-gl-mwe

Has anyone used the same boilerplate? Any ideas?

**Comment by ibgreen** [comment]
Given the new instructions from mapbox on how to build with webpack (see README for link) I will close this for now.

If there are react-map-gl specific issues with webpack, the best approach would be to open a PR with a small example, see #112

**Comment by Jinnified** [comment]
@ankitduseja could you please tell me how did you solve that Cannot find module 'gl' issue? it appears npm hangs when i am trying to install the gl module
