### ISSUE TITLE
Make project more contributor friendly

### ISSUE THREAD

**Issue by stereobooster** [uber/react-map-gl#213]
I want to do contribution. I cloned project. It took me a lot of time to figure out how actually start development server to test new component. I would suggest following steps to make contribution simpler:

- Fix [create-react-app issue](https://github.com/uber/react-map-gl/issues/176). Because it is so easy to setup and test some code with it, instead of spending time on webpack configuration.
- Switch to yarn instead of npm, because [it is faster](https://medium.com/@nikjohn/facebooks-yarn-vs-npm-is-yarn-really-better-1890b3ea6515). [There is an issue with it, but this is possible](https://github.com/yarnpkg/yarn/issues/521#issuecomment-297545407).
- Use [styleguidist](http://react-styleguidist.js.org/) instead of custom scripts in `gh-pages` and instead of custom scripts in `examples`. Consolidate examples code in one place.

The project itself supper good. I believe it has potential to be the best React map out there, because MapboxGL is the fastest client side renderer (from personal experience), and project acknowledges React declarative approach.

**Comment by Apercu** [comment]
Hi, thanks! Help is always appreciated 😃  Regarding your points:

- We're already using yarn, the error you're referencing to was a mistake done in our lockfile.
- The issue about create-app can't be done without adding what's necessary in the webpack configuration and that have been documented. The error is coming from our mapbox dependency anyway, so there isn't much we can do at this level.

Not sure if I understand the part about examples, `npm start` should be all you need after having installed dependencies. What's the problem with custom scripts? It's pretty lightweight.

**Comment by stereobooster** [comment]
> We're already using yarn

What about this line from package.json? 

```json
"start": "(cd examples/custom-interactions && (path-exists node_modules || npm i) && npm run start-local)",
```

1. it uses `npm`
2. it uses `path-exists`, which is undefined at least in Mac OS X. But this solvable with `[ -d \"node_modules\" ] || npm i`

> The error is coming from our mapbox dependency anyway

Is there an issue in MapboxGL repo? I can open it myself, but it would make more sense if it will be opened by someone who knows more context.

**Comment by stereobooster** [comment]
Other side note: [Interactivity page](https://uber.github.io/react-map-gl/#/interactivity) shows complete example. But this example not complete without [attribution component](https://github.com/uber/react-map-gl/blob/gh-pages/common/attribute.react.js).

It is possible to use alternative vector tiles to show full power of MapboxGL. See example [here](https://osm2vectortiles.tileserver.com/#v3/mapboxgl.code).

**Comment by stereobooster** [comment]
At first I thought that `examples` folder has something in common with development server, but it is not. So question boils down to: how to start development server e.g. web server with page where you can preview and debug new component which you are developing. Something like [styleguidist](https://github.com/styleguidist/react-styleguidist) or [storybook](https://github.com/storybooks/storybook) or scripts that leaves under `gh-pages`.

**Comment by ericsoco** [comment]
The `start` script uses `npm` but if we're requiring `yarn`, @Apercu, we could replace `npm` commands with `yarn` commands.

@stereobooster [`path-exists` is an npm module](https://www.npmjs.com/package/path-exists) and should have been installed when you `yarn`ed or `npm install`ed. We use that instead of the `bash` script you suggest for cross-platform compatibility.

**Comment by stereobooster** [comment]
Isn't that usage `path-exists` assumes global installation? And `yarn` (I use yarn) will install dependencies locally.

**Comment by ericsoco** [comment]
No, scripts in `package.json` first resolve to `node_modules/.bin` and then global installation.

**Comment by stereobooster** [comment]
Thanks @ericsoco but as I said earlier

> At first I thought that examples folder has something in common with development server, but it is not. So question boils down to: how to start development server

**Comment by ibgreen** [comment]
> At first I thought that examples folder has something in common with development server, but it is not. So question boils down to: how to start development server.

@stereobooster 
Have you looked at the `package.json` in the various examples? They all contain an `npm start` script that runs `webpack-dev-server`. 

```
{
  "description": "Main example for react-map-gl",
  "license": "MIT",
  "scripts": {
    "start": "webpack-dev-server --progress --hot --open",
    ...
  ```

The idea is that each example is standalone. You go into that directory for the example you are interested in, install  and start
```
cd examples/main
yarn # or
npm install
npm start
```

Maybe this needs to be added to the README. @abmai

**Comment by stereobooster** [comment]
@ibgreen

I'm interested in development server. Example: I created new component Marker in `src/components`. Now I want to test/debug it. Where should I add it, what should I start? 

[package.json](https://github.com/uber/react-map-gl/blob/master/examples/main/package.json) lists "react-map-gl": "^1.7.2" not local version.

**Comment by ibgreen** [comment]
@stereobooster 

To handle the development case, the examples have a second script `npm run start-local` that build against the local src code instead of the installed version of react-map-gl.

We need both, to support development and as an example of using the published libraries.

**Comment by stereobooster** [comment]
huh.. now I see. Thanks. Will try

**Comment by stereobooster** [comment]
I would say Readme needs more notes on development process, but I got all my answers. You can close this at your will. Thanks for help.

**Comment by abmai** [comment]
@stereobooster apologies for the confusion here. We're in the process of revamping a bunch of README and examples on master so things should improve in the coming weeks. In the mean time, please feel free to continue raising issues as you encounter them!

**Comment by stereobooster** [comment]
No need for apologies. Thanks for doing this project. It is super cool. Thanks for answering my infinite questions. Thanks @abmai @ibgreen @ericsoco @Apercu ❤️

**Comment by ibgreen** [comment]
See comment in https://github.com/uber/deck.gl/issues/624 for the root cause behind the `create-react-app` issue.
