### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by vicapow** [uber/react-map-gl#22]

**Comment by vicapow** [comment]
Subtasks
- [ ] Use stamen tiles instead of open street map tiles.
- [ ] Have individual tabs / pages for each example
- [ ] Support adding examples of third party overlays

**Comment by vicapow** [comment]
See existing docs at: http://uber.github.io/react-map-gl/

**Comment by vicapow** [comment]
@wwwtyro feel like starting on this next? It's a bit more open ended than the other tasks. Otherwise, #17  would be great to nail down.

**Comment by wwwtyro** [comment]
Sure, no problem!

**Comment by vicapow** [comment]
@wwwtyro one additional step I forgot to mention. Can you submit a separate diff to the gh-pages with just the result of running: `npm run build`? This should update the local `bundle.js` file.

**Comment by wwwtyro** [comment]
#37 sorry about that!

**Comment by vicapow** [comment]
it's all good!

**Comment by wwwtyro** [comment]
Any interest in jsx-ifying the docs?

**Comment by vicapow** [comment]
@wwwtyro not a bad idea. Maybe we could create a seperate task for that? But I think it still makes sense to keep the project on r-dom to avoid the added complexity of a build step and/or to avoid imposing the requirement on consumers of the component.

**Comment by wwwtyro** [comment]
Ah, yeah, I see what you mean. :+1:

**Comment by vicapow** [comment]
I added some more detail to the docs. http://uber.github.io/react-map-gl/
