### ISSUE TITLE
Touch/mobile support

### ISSUE THREAD

**Issue by jdeerhake** [uber/react-map-gl#232]
After upgrading from 3.0.0-alpha.4 to alpha.9 it seems my map has stopped responding to touch events on mobile.  I was able to track it down to the touch handlers being removed here: https://github.com/uber/react-map-gl/pull/212/files#diff-c338a0328235aa9485914040a3e81043L143

I'm just wondering if this was an accident or if it was intentionally removed and left to the user to implement via a custom ControllerClass?

**Comment by ibgreen** [comment]
> I'm just wondering if this was an accident or if it was intentionally removed and left to the user to implement via a custom ControllerClass?

@jdeerhake As you have seen, react-map-gl event handling is mid-stream in a big refactor. Our aspiration has certainly been to have full mouse support in v3 (including pinch to zoom and rotate), but this will depend on how the work progresses.

Will classify this as a bug for now and will open a release tracking task to give more transparency to v3 release plans and progress.

**Comment by malonehedges** [comment]
Any timeline on this issue @ibgreen ? Would love to use this in my project but can't without touch support.

**Comment by jdeerhake** [comment]
FWIW the touch support is pretty good in the latest alpha release thanks to awesome work by @Pessimistress, i think this is just being held open until the 3.0 release?  Or I was supposed to close it, in which case.. oops.

**Comment by abmai** [comment]
Yep, as @jdeerhake said, we have pretty good touch support now on the latest alpha release, `3.0.0-alpha.15`. I'll close this one out for now as the original issue seems to be resolved. If you're having specific problems with touch support in your project, can you please open another issue for easier tracking, @malonehedges?

**Comment by malonehedges** [comment]
@abmai is there any demo page for the alpha release?

**Comment by abmai** [comment]
@malonehedges we don't have the demos built publicly. You can just clone `master` and do one of the following (note you will need a Mapbox Token - https://github.com/uber/react-map-gl/blob/master/docs/get-started/mapbox-tokens.md):

1) Check out the full doc site by going into `website` and `yarn && npm run start`
2) Check out any of the examples under `examples` - they're all working standalone examples.

**Comment by malonehedges** [comment]
@abmai Awesome, thanks for the help. Will check it out. Do you know approx when 3.0 will be released in full? Can use the alpha but just curious.
