### ISSUE TITLE
Using url ?access_token give me 3d map

### ISSUE THREAD

**Issue by Shadowman4205** [uber/react-map-gl#237]
Is there anyway to pick the map i want? i am coming from leaflet where i use 
this 

> https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}

to pick the map.

How i do this here? When i use http://localhost:8080/?access_token=....... i get a 3D map.
![react-map-gl](https://cloud.githubusercontent.com/assets/23194476/25937552/d3fe8eb4-3634-11e7-8c98-1cc317bfb615.png)

**Comment by ibgreen** [comment]
> How i do this here? When i use http://localhost:8080/?access_token=....... i get a 3D map.

@Shadowman4205 I realize this is not the full answer but perhaps still helpful: react-map-gl uses mapbox-gl styles to control the colors and layers etc of the base map. 

The fact that the map is shown in perspective mode (3D) has nothing to do with the style, that is how the example application that you are running is rendering the map. Changing the map style would change how it is renderer (colors etc) not the fact that it is in perspective mode.

If you want to prepare a mapbox token that includes custom style information, to the extent that is possible, you may want to consult mapbox-gl docs directly.

**Comment by ericsoco** [comment]
You're conflating the access token (which allows you access to Mapbox's API) and the basemap style. If I'm understanding correctly, you want to change your basemap style. As @ibgreen mentioned, we're using Mapbox styles, which you can specify by passing a `mapStyle` prop into your `<InteractiveMap>` or `<StaticMap>`. For example, in [view.js::render()](https://github.com/uber/react-map-gl/blob/master/examples/custom-interactions/view.js#L121), add this prop:

`mapStyle="mapbox://styles/mapbox/dark-v9"`

et voila:
<img width="896" alt="screen shot 2017-05-11 at 9 17 51 am" src="https://cloud.githubusercontent.com/assets/1127259/25960094/c4dcb37a-362a-11e7-935c-509853642fa7.png">
