### ISSUE TITLE
Unable to import Marker component

### ISSUE THREAD

**Issue by G2Jose** [uber/react-map-gl#240]
I'm trying to use the `Marker` component, but I seem to have trouble importing it. I tried following the example at https://github.com/uber/react-map-gl/blob/1cef144dc14652fb3ef682a84e8b09a4b74da4bf/docs/controls/Marker.md - 

```
import MapGL, { Marker } from 'react-map-gl';
```

but when I try `console.log(Marker)`, I see that `Marker` is `undefined`. 

Package versions:
```
"immutable": "^3.8.1",
"r-dom": "^2.3.2",
"react": "^15.5.4",
"react-dom": "^15.5.4",
"react-map-gl": "^2.0.2"
```

**Comment by abmai** [comment]
@G2Jose things on master are in active development still. You'll have to install `3.0.0-alpha.10` if you want to try them out. `2.0.2` does not have the `Marker` component.
