### ISSUE TITLE
update mapbox-gl to 0.11.4

### ISSUE THREAD

**Issue by abmai** [uber/react-map-gl#25]
running into a ton of these errors:

![image](https://cloud.githubusercontent.com/assets/2263443/11353891/102fcc60-91fc-11e5-800b-adba0a49c96c.png)

quick google search shows that this problem creeped up with the mapbox-gl `0.11.3` update:

https://github.com/mapbox/mapbox-gl-js/issues/1694

which was fixed and should be included in the `0.11.4` version

https://github.com/mapbox/mapbox-gl-js/pull/1696

I think we're version locking to `0.11.3` right now so would be nice to update.

**Comment by vicapow** [comment]
https://github.com/uber/react-map-gl/pull/26
