### ISSUE TITLE
`onChangeViewport` inconsistency in v3

### ISSUE THREAD

**Issue by Pessimistress** [uber/react-map-gl#253]
In v1 and v2, `onChangeViewport` does not include `width` and `height` in the callback parameters. v3-alpha currently does. This change of behavior may break the apps that store map states and viewport size separately:
```jsx
<MapGL
  {...windowSize}
  {...mapState}
  ...
  />
```
Is there a strong argument for or against this behavior? Should we just keep compatible with the old versions?

@ibgreen @abmai @shaojingli

**Comment by abmai** [comment]
Why does `onChangeViewport` return `width` and `height` in v3-alpha? Was there some need to do that?

**Comment by Pessimistress** [comment]
@abmai It was not a decision, just happened when we refactored map controls. 
The old callback parameter was explicitly constructed: https://github.com/uber/react-map-gl/blob/1.0-release/src/map.react.js#L503
While the new callback parameter is not: https://github.com/uber/react-map-gl/blob/master/src/utils/map-controls.js#L114

**Comment by abmai** [comment]
Ah I see. I think that the new way *is* clearer in code path (viewport in, viewport out). And one would expect `width` and `height` to be part of the `viewport`, even if they might not be used often.

I'm open to continue returning `width` and `height` with the new `viewport` object. We'll just need to be explicit when documenting V3 breaking changes.

Unless there are strong reasons *not* to expose these variables.
