### ISSUE TITLE
v3 - onLoad gone?

### ISSUE THREAD

**Issue by contra** [uber/react-map-gl#267]
Seems like this doesn't work anymore - I see the test for it still on master, but the code has no reference to the load event anymore.

**Comment by ibgreen** [comment]
@contra Good finding. While we haven't concluded the final API reviews, I do believe the intention so far is to keep supporting this callback in v3.

**Comment by pranspach** [comment]
if you use master, it's added back @contra. IDK when the releases are tagged for this project.

**Comment by abmai** [comment]
I'll cut a new alpha with this today/tomorrow.

**Comment by abmai** [comment]
Publish `3.0.0-alpha.13`.
