### ISSUE TITLE
Display error message when isSupported=false

### ISSUE THREAD

**Issue by keithkml** [uber/react-map-gl#268]
I just lost an hour or two of productivity after the map on our app went blank. I thrashed around trying to debug the issue, assuming it was a MapBox key issue, or NPM version issue, or whatever. Eventually I stepped through the code and happened to find that this code was being executed:

```js
    _this.state = {
      isSupported: _mapboxGl2.default.supported(),
   // ...
    if (!_this.state.isSupported) {
      _this.componentDidMount = noop;
      _this.componentWillReceiveProps = noop;
      _this.componentDidUpdate = noop;
    }
```

For some reason WebGL wasn't loading, and I just had to restart Chrome.

It would have saved me 2 hours of time if:
1. An error message were displayed on the screen
2. An error message were printed to the JavaScript console

**Comment by ibgreen** [comment]
@keithkml Sorry to hear that you lost time. Agree that it would be a good idea to at least add a console log. We should get this into the upcoming v3 release. 

PR welcome.

**Comment by pranspach** [comment]
If WebGL isn't supported, I'd also like to be able to detect that and load a backup experience. 

Their non-react standard: https://github.com/mapbox/mapbox-gl-supported/

Some options:
Call `supported()` on the Map's ref in componentDidMount
Wrap `mapbox-gl-supported` in something more React friendly

Has anyone implemented this component toggling with react-map-gl? A console log sounds like a useful debugging feature.

**Comment by Pessimistress** [comment]
We have a static method `MapGL.supported()` that wraps the mapbox-gl validator.

**Comment by Pessimistress** [comment]
Warning message is supported in v3.1.
