### ISSUE TITLE
Unable to run example, npm install failed. 

### ISSUE THREAD

**Issue by liuhy0302** [uber/react-map-gl#273]
Hi, this is my first time using deck.gl, and I failed to run "npm install" in the examples/arc directory. I'm also attaching the debug.log file. 

Any help would be highly appreciated!
=================================================
➜  arc git:(master) ✗ npm install
npm WARN deprecated feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm WARN deprecated whoots-js@2.1.0: This module is now under the @mapbox namespace: install @mapbox/whoots-js instead
npm WARN deprecated shelf-pack@1.1.0: This module is now under the @mapbox namespace: install @mapbox/shelf-pack instead
npm WARN deprecated geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git checkout d11f6d2775bf5b22534b3b2fb3410755b2473cdf
npm ERR! fatal: reference is not a tree: d11f6d2775bf5b22534b3b2fb3410755b2473cdf
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hongyi/.npm/_logs/2017-06-09T02_14_09_331Z-debug.log

[2017-06-09T02_14_09_331Z-debug.log.txt](https://github.com/uber/react-map-gl/files/1062870/2017-06-09T02_14_09_331Z-debug.log.txt)

**Comment by liuhy0302** [comment]
sorry... I shouldn't put this issue here ...
Please just close this one...

**Comment by abmai** [comment]
No worries :).

**Comment by calpa** [comment]
Same here...
@abmai

**Comment by shaojingli** [comment]
@liuhy0302 @calio if you are using npm 5, then this might be the cause:

https://github.com/npm/npm/issues/17146
