### ISSUE TITLE
Examples don't run without a root install

### ISSUE THREAD

**Issue by G2Jose** [uber/react-map-gl#274]
I wonder if it makes sense to have a README section for links to projects that use react-map-gl.

I know I personally would have benefitted quite a bit from something like that since some of the examples provided (at least then) seemed a bit out of date.

That said, I can see some good reasons both in favor of and against having such a section. What do you folks think?

**Comment by Pessimistress** [comment]
@G2Jose We definitely want to make it easier for developers to get started.
In the [examples](https://github.com/uber/react-map-gl/tree/master/examples) folder `layers` `interaction` `controls` and `geojson` are newly added apps that showcase capabilities of v3. We are also planning to upgrade/clean up the legacy examples in there soon.

**Comment by ibgreen** [comment]
> I wonder if it makes sense to have a README section for links to projects that use react-map-gl.

@G2Jose I like this idea. Are you aware of any open source projects that would represent good examples?

**Comment by abmai** [comment]
+1 to this. We can start a section if there are some good initial examples and will welcome PR to add more as well.

**Comment by jpdevries** [comment]
I'm getting a "Cannot find webpack error" when trying to run the examples. I'm going into an example directory and 

```bash
npm install
npm run start
```

I still get the error even after `npm install webpack`

**Comment by ibgreen** [comment]
@jpdevries Can you be a bit more specific? 

* Which specific example directory are you working with?
* Or are they all broken? 

I looked through the `package.json` files in all the examples and they all do list `webpack` as a `devDependency`,  nautrally with the exception of the `exhibit-browserify` example.

* Does your `npm install` fail to install webpack?
* if you do `npm ls webpack` what do you get?
* Is there anything in `node_modules/webpack`

**Comment by jpdevries** [comment]
@ibgreen from the latest commit on master I tested going into each example directory. For example:

```bash
cd examples/main
npm install
npm run start
```

> Does your npm install fail to install webpack?

It seems to install it 

> if you do npm ls webpack what do you get?

```bash
j15:main jP$ npm ls webpack
/Users/jP/Sites/uber/react-map-gl/examples/main
├─┬ buble-loader@0.4.1
│ └── webpack@2.6.1  deduped
└── webpack@2.6.1 
```

> Is there anything in node_modules/webpack

Yes. 

```bash
j15:main jP$ ls node_modules/webpack
LICENSE		bin		hot		node_modules	schemas
README.md	buildin		lib		package.json	web_modules
```

I get this error in the console:

<details>
  <summary>Console Message</summary>
<pre>

> @ start /Users/jP/Sites/uber/react-map-gl/examples/main
> webpack-dev-server --progress --hot --open

module.js:487
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jP/Sites/uber/react-map-gl/examples/webpack.config.local.js:9:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `webpack-dev-server --progress --hot --open`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jP/.npm/_logs/2017-06-18T21_39_39_648Z-debug.log
j15:main jP$ 
</pre>
</details>

<details>
<summary>debug.log</summary>
<pre>
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.2/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/jP/Sites/uber/react-map-gl/examples/main/node_modules/.bin:/Users/jP/.rbenv/shims:/Users/jP/.node/bin:/Users/jP/Sites/modx/Gitify:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin:/Users/jP/bin:/usr/local/bin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin:/opt/X11/bin
10 verbose lifecycle @~start: CWD: /Users/jP/Sites/uber/react-map-gl/examples/main
11 silly lifecycle @~start: Args: [ '-c', 'webpack-dev-server --progress --hot --open' ]
12 silly lifecycle @~start: Returned: code: 1  signal: null
13 info lifecycle @~start: Failed to exec start script
14 verbose stack Error: @ start: `webpack-dev-server --progress --hot --open`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid @
16 verbose cwd /Users/jP/Sites/uber/react-map-gl/examples/main
17 verbose Darwin 16.6.0
18 verbose argv "/usr/local/Cellar/node/8.1.2/bin/node" "/usr/local/bin/npm" "run" "start"
19 verbose node v8.1.2
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error @ start: `webpack-dev-server --progress --hot --open`
23 error Exit status 1
24 error Failed at the @ start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
</pre>
</details>

**Comment by ibgreen** [comment]
@jpdevries Are you using npm 5? Seems like installs are failing for many users:

npm/npm#17146

I just tried installing both with yarn and npm 4.2 and both worked. I also pushed a small update to the webpack config in the example. Should not be related to your issue but worth pulling anyway.

**Comment by jpdevries** [comment]
@ibgreen ya I'm on

```bash
npm --version
5.0.3
```

I get the same thing with

```bash
rm -rf node_modules
yarn
yarn start
```

**Comment by ibgreen** [comment]
OK I see. please run another install in the root directory before you start the example and it should work. This is a bug, we should fix this.

**Comment by jpdevries** [comment]
Thanks @ibgreen that did the trick.

**Comment by ibgreen** [comment]
Let's actually fix this before we close it. We just need to make sure we conditionally require the shared webpack config in all examples (@pessimistress already did this in a couple of the examples).

**Comment by abmai** [comment]
Docs and Examples on Master should be fixed now. Closing this issue out. Please feel free to re-open if anyone here still run into problems.
