### ISSUE TITLE
node postinstall.js fails on install

### ISSUE THREAD

**Issue by josephobradovich1** [uber/react-map-gl#279]
When installing react-map-gl I am getting an error on the node postinstall.js. The installation errors out with the following: 

TypeError: Object #<Object> has no method 'access'.

**Comment by Apercu** [comment]
Hey, could you provide your full stacktrace, node and deck.gl versions? It's a bit hard to debug with just this piece of info.

**Comment by abmai** [comment]
@josephobradovich1 Make sure you're running on Node v6+

**Comment by josephobradovich1** [comment]
The issue was my Node version, I forgot to switch to version 6. Thanks for the help!
