### ISSUE TITLE
Support contextmenu (for enabling right click events)

### ISSUE THREAD

**Issue by jejay** [uber/react-map-gl#288]
As far as I have understood, Mapbox does not fire a click event when a right click occurs. Instead it fires a contextmenu event. See https://github.com/mapbox/mapbox-gl-js/issues/1416

My Problem now is, that the contextmenu event seems to be not supported by react-map-gl. So I cant listen to right click events.

I suggest a onContextmenu-prop on the InteractiveMap that consumes a callback.

**Comment by wuweiweiwu** [comment]
React provides a synthetic event wrapper for [`onContextMenu`](https://reactjs.org/docs/events.html#mouse-events) 

So it'd be relatively straightforward to add a [prop](https://github.com/uber/react-map-gl/blob/master/src/mapbox/mapbox.js#L34) to mapbox that is passed into / or bound to the internal dom ref

**Comment by Pessimistress** [comment]
Added in 3.2.9
