### ISSUE TITLE
scroll to end of page when scrollZoom is set to false

### ISSUE THREAD

**Issue by epicallan** [uber/react-map-gl#289]
I have a map in the middle of a web page with scrollZoom set to false, and I would like to be able to scroll to end of the page even while cursor is over the map.

I see something related to this issue was brought up here https://github.com/uber/react-map-gl/pull/134 

I am using 3.0.0-alpha.12

**Comment by abmai** [comment]
Apologies for the issue - PR #283 should resolve this once it lands.
