### ISSUE TITLE
integration with create-react-app after npm eject

### ISSUE THREAD

**Issue by roma98** [uber/react-map-gl#297]
Hello all,
I have recently run `npm eject` on a `create-react-app` project, in order to tweak webpack to include `react-map-gl`.
I have followed the example [here](https://github.com/uber/react-map-gl/blob/master/examples/exhibit-webpack/webpack.config.js), by simply adding `'mapbox-gl$': resolve('./node_modules/mapbox-gl/dist/mapbox-gl.js')` on my config.
However it doesn't solve my problem, just pointing to another issue.

I went from this error

```
Error in ./~/mapbox-gl/js/util/util.js
Module parse failed: /Users/romain/WebstormProjects/gougle/node_modules/mapbox-gl/js/util/util.js Unexpected token (15:35)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (15:35)
 @ ./~/mapbox-gl/js/mapbox-gl.js 26:16-38
```

to this error

```
Error in ./~/mapbox-gl/js/geo/coordinate.js
Module parse failed: /Users/romain/WebstormProjects/gougle/node_modules/mapbox-gl/js/geo/coordinate.js Unexpected token (14:10)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (14:10)
 @ ./~/mapbox-gl/js/geo/transform.js 5:17-40
```

I've been playing around for a long time and don't really know where to go now.

**Comment by roma98** [comment]
it works now after the last update. Thank you.

**Comment by alexyuly** [comment]
@roma98 I am currently encountering the first error in your issue description. Webpack throws an error because it can't parse the Flow syntax found in `node_modules/mapbox-gl/js/util/util.js`. It sounds like you were able to resolve this issue. If you are able to provide any further information, it would be much appreciated.

**Comment by roma98** [comment]
so weirdly, it worked after performing an updates of all npm packages, but now whenever I install a new npm package, I end up with the same parse error on coordinate.js... I have no idea why... It disapear when I uninstall the new package.
I don't have a deep understanding of webpack since I started with create-react-app, so there's might be something that I'm missing. All I did was running npm-eject, and then adding the alias on my webpack config.

**Comment by alexyuly** [comment]
*Update:* It is working for me too now, although I'm not sure why.

Immediately after encountering the above error, I added (with Yarn) [flowtype-loader](https://github.com/torifat/flowtype-loader) to my project hoping it would help solve the problem, but having no success I removed it shortly after. Now, when I run webpack, it is successful. I'm not sure why. Nothing else appears to have changed in my project, between encountering the error and resolving it.

**Comment by alexyuly** [comment]
@roma98 I'm getting the same behavior, using webpack 3.1.0.

**Comment by roma98** [comment]
Hey so whenever I install a new package and I come back to the previous error, I just remove and re-install react-map-gl, and then everything works fine. Weird.

**Comment by alexyuly** [comment]
I'm using Yarn and I also found that deleting my node_modules folder and running `yarn` again (to effectively remove and re-install all packages), will fix the problem. I might assume that the same would go for users of NPM.

**Comment by roma98** [comment]
Hi @alexyuly it works fine in dev, but it won't compile, despite using the same alias.
I got `static/js/main.17c6208a.js from UglifyJs
SyntaxError: Unexpected token: name (Coordinate) [./~/mapbox-gl/js/geo/coordinate.js:13,0]
`
Did you stumble upon the same problem?

**Comment by alexyuly** [comment]
@roma98 I remember encountering that error once, but I have not been able to reproduce it since. To clarify, I have been using react-map-gl 2.0.3.

**Comment by roma98** [comment]
I could solve this issue by using `devtool: 'eval'` in `webpack.config.prod.js`

**Comment by alexyuly** [comment]
Upgrading to v3 (beta) solved the problem for me. (This is an option if you're willing to use a beta version.)
