### ISSUE TITLE
When using css transform: scale() mouse events do not work properly

### ISSUE THREAD

**Issue by nwlieb** [uber/react-map-gl#299]
If the map has been scaled by a css transform, the dragging scale and the centering is wrong, as if the map were using the real pixel location of the cursor and not accounting for the scale. We are using version 3.0.0-alpha.14

Example:
```
<div style={{transform: 'scale(0.5, 0.5) translateX(-50%)'}}>
    <MapGL {...mapProps} />
</div>
```
edit: this affects both v2 and v3

**Comment by abmai** [comment]
@Pessimistress any thoughts on this?

@nwlieb is there a need to use CSS transform here versus passing in a different set of dimensions to the Map component?

**Comment by nwlieb** [comment]
@abmai We are doing an app-wide scale so there is no way to exclude the map from getting scaled. I just tried this:

```
<div style={{transform: 'scale(0.5, 0.5) translateX(-50%)'}}>
    <div style={{transform: 'scale(2, 2) translateX(-25%)'}}>
        <MapGL {...mapProps} width={mapProps.width/2} height={mapProps.height/2} />
    </div>
    <div>Other scaled component</div>
</div>
```

And with this the dragging works, but now the map zoom does not reflect the positioning we set while it is unzoomed (which is a problem since we toggle the scale).
