### ISSUE TITLE
OnClick, OnDrag and other events are propagated even though e.preventDefault() and e.stopPropagation() are called

### ISSUE THREAD

**Issue by aindeev** [uber/react-map-gl#304]
When you add Markers or other Overlays on top of the map, the pointer events are still propagated to the map.

For example if we render a "control panel" on top of the map in the corner, we can still drag the map around through the overlay. The only way around this issue is to render such content outside of the map component

The same problem happens with Markers. In my case I am adding a onClick handler on the Marker itself and adding an additional onClick markers on the map itself. Both handlers are fired even if we specify:

```js
onMarkerClick(e) {
   e.preventDefault()
   e.stopPropagation()
}
```

```js
onMapClick(e) {
    // -> still fired
}
```

I am attempting to create something similar in nature to this.
https://www.mapbox.com/mapbox-gl-js/example/toggle-layers/

**Comment by alex2wong** [comment]
Is there any comments on this? I have tested in simple react parent/child components, event can be stopped in event handler in child component which would not propagate to parent.

But dblClick event can always pass to mapComponent causing zoom, stopPropagation does not work. Weird.

**Comment by kriscarle** [comment]
I just ran into this as well. It appears be because the eventCanvas is a parent of the overlays container where the children are inserted.  It is present in the examples too, for example in https://uber.github.io/react-map-gl/#/Examples/markers-popups you can drag the map while on top of the overlays

My work around is to put my controls outside of the react-map-gl component inside of passing them as children.

**Comment by Pessimistress** [comment]
The problem here is caused by us using hammer.js under the hood. The `click` and `doubleClick` events are triggered by `pointerUp`, which always fires before the native `click` and `dblClick`.
@ericsoco @ibgreen @shaojingli

**Comment by Pessimistress** [comment]
@aindeev @alex2wong @kriscarle In your use cases, would it work if the Marker/Popup components by default blocks map interaction (click and drag do not propagate) but also offers a prop to turn it on?

**Comment by heathercodes** [comment]
I'm not sure if this fix was solved for @aindeev , but this propagation issue is still affecting my app despite the fix. 
If on the `ReactMapGL` you specify an `onClick` function, then have a Popup component as a child, any onClick callback functions in the Popup component will still propagate to the map.
Am I missing something? I've looked through the examples and documentation without luck

**Comment by Pessimistress** [comment]
@heathercodes You can block the click event from propagating by setting `captureClick: false` on the Popup component (see https://github.com/uber/react-map-gl/pull/377).

The long explanation is that, to handle pointer/touch gestures, react-map-gl registers its event handlers using the native JavaScript API. Calling `stopPropagation` on React's synthetic events does not block the native events from firing.

**Comment by heathercodes** [comment]
Thanks for responding @Pessimistress . I have tried setting the flag to false on the Popup component, but this does nothing. The only thing that stops the propagation is when I remove the `onClick` callback function from the `ReactMapGL` component itself.

Obviously, this isn't ideal, as I'm trying to capture location when the user clicks on the map, and display it in a popup.

**Comment by Pessimistress** [comment]
@heathercodes Sorry I mistyped, it should have be `captureClick: true` (edited original message).

Though after a quick test it does not seem to function as expected. I'll investigate.

**Comment by Pessimistress** [comment]
@heathercodes Give 3.2.10 a try.

**Comment by heathercodes** [comment]
thanks for the quick turn around @Pessimistress. I tried the new version, but am still seeing the same behaviour.

**Comment by Pessimistress** [comment]
@heathercodes Could you post your code and steps to reproduce the problem here?

**Comment by heathercodes** [comment]
hey @Pessimistress , looks like I forgot to re-enable `captureClick` on the Popup component from the last test I did on this bug. I took it off again, and things are functioning properly; 3.2.10 resolves this issue. Thanks for looking into this so quickly! 👍

**Comment by CSFlorin** [comment]
Any idea how I could do this in a non-Popup component? Catching the scroll, click, etc event in a custom controller does not seem to indicate which element I clicked; it just shows I clicked the map.

**Comment by lamuertepeluda** [comment]
guys, great library but this behavior is annoying... I think I will end up bypassing these nice but "nosy" event mjolnir handlers and attach directly to the map on the onLoad callback, since mapbox already implements 'click' and other events. It's a pity, though.

Even context menu is intercepted by onClick, which does not make sense to me

e.g.
```jsx
<InteractiveMap
...
ref={mapViewRef}
oLoad={()=>{
  const map = mapViewRef.getMap()
  map.on('click', mapClickHandler)
}}
/>
```

But I'd appreciate a cleaner solution

**Comment by lamuertepeluda** [comment]
Even worse, the `div.overlays` intercepts all the mouse events, so we have to force it via CSS 😞 

I added a rule in a parent component stylesheet/style component


```scss
div.overlays {
   pointer-events: none;
}
```

I would suggest an option to use mapbox handlers instead of mjolnir's, or at least make them less invasive.

I had to do this since I added some extra map controls.

Huge downside: all children of overlays are cut out, including those from react-map-gl-draw 😭

**Comment by j8seangel** [comment]
Any of the solutions worked for me. Anyway, thanks everyone for sharing! 
I took a look at the native popup component and see how it handles the closeButton functionality to replicated it using `_MapContext` and its `eventManager` in my Popup click callback.

```
import { _MapContext } from '@globalfishingwatch/react-map-gl'
```

```
const context = useContext(_MapContext)
```

```
const handleClick = (ev: React.MouseEvent<Element, MouseEvent>) => {
  context.eventManager.once('click', (e: any) => e.stopPropagation(), ev.target)
  ...
})
```

Hopefully this works in every case and simplifies it.

**Comment by david-morris** [comment]
Whoops, it's totally unclear how to do this with the new major version. Should we reopen this here? Is this an issue with current capabilities or just documentation?

**Comment by trumbitta** [comment]
It would be cool to have `captureClick` for `Marker` also.

Anyway, this works for me:

```jsx
<Marker
  latitude={latitude}
  longitude={longitude}
  onClick={({ originalEvent }) => {
    originalEvent.preventDefault();
    originalEvent.stopPropagation();

    doYourThing();
  }}
/>
```
