### ISSUE TITLE
Reference is not a tree error

### ISSUE THREAD

**Issue by Kerizer** [uber/react-map-gl#306]
After running `npm install --save react-map-gl`  I receive `fatal: reference is not a tree: d11f6d2775bf5b22534b3b2fb3410755b2473cdf`

**Comment by abmai** [comment]
@Kerizer what version of `npm` are you using?

**Comment by Kerizer** [comment]
@abmai 5.0.3

**Comment by abmai** [comment]
Looks like this is related to: https://github.com/uber/react-map-gl/issues/293 which is affecting npm v5

Can you try installing our v3 beta, which we're about to release soon: `npm install react-map-gl@beta`.

**Comment by kachkaev** [comment]
Still seeing this with npm 5.3.0 / react-map-gl@2 / mapbox-gl-js@0.32.1

**Comment by abmai** [comment]
Opened an issue on `npm` to see if they can help here: https://github.com/npm/npm/issues/17880

**Comment by vicapow** [comment]
https://github.com/yarnpkg/yarn/issues/3407 seems to be related which causes "authorization headers to be sent for resources not from the configured registry.

For example, assuming you have the following `.npmrc` file:

````sh
(master) -> cat ~/.npmrc
registry=https://my-own-npm-registry.com/
_auth="XXXXX-some-registry-token-XXXXXXXX"
email=victor@example.com
always-auth=true
loglevel=http
````

yarn will make the following request:

```sh
curl -H 'authorization: Basic XXXXX-some-registry-token-XXXXXXXX' -H 'Accept: application/octet-stream' -H 'Accept-Encoding: gzip' -H 'User-Agent: unpm-allow-external-deprecated-packages' https://codeload.github.com/mapbox/mapbox-gl-style-spec/tar.gz/83b1a3e5837d785af582efd5ed1a212f2df6a4ae --verbose -o /dev/null
```

```sh
< HTTP/1.1 404 Not Found
< Content-Length: 15
< Access-Control-Allow-Origin: https://render.githubusercontent.com
< Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'
< Strict-Transport-Security: max-age=31536000
< Vary: Authorization,Accept-Encoding
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
< Date: Tue, 25 Jul 2017 01:36:31 GMT
< X-GitHub-Request-Id: B362:3859:113128:20FFF2:5976A09F
```

Github returns a 404 with invalid auth credentials even if the request would succeed with no credentials.
