### ISSUE TITLE
deck.gl GeoJSONLayer vs Data-Driven Map Style

### ISSUE THREAD

**Issue by jejay** [uber/react-map-gl#309]
For integrating GeoJSON the README promotes the deck.gl GeoJSONLayer (at least indirectly). In contrast to this, when you look into the examples folder just for "geojson", you will find a example based on data-driven map styles. 

My Questions are:

* What is the preferred way for integrating GeoJSON? To me the data-driven-map-styles approach feels counter intuitive and fiddling. Is there any advantage to this approach?
* Furthermore, assumed we all agree on my implication, would it be helpful if I convert the geojson-example to a deck.gl-based one?

**Comment by ibgreen** [comment]
@jejay - There are two camps here, some prefer mapbox styles and some prefer deck.gl, some like to mix. We try to cater to all these use cases.

react-map-gl is intended to expose as much as possible of mapbox functionality, which includes data driven styles.

The two geojson solutions also have some differences in how much data they can handle, how fast they animate etc, there is not a clear winner for all use cases.

Try our new website (go into the website folder and install and start). We are adding links to deck.gl, so I think most deck.gl examples should be in that repo.
