### ISSUE TITLE
I created a tutorial repository for someone who use create-react-app

### ISSUE THREAD

**Issue by zjhch123** [uber/react-map-gl#323]
[Here is! ](https://github.com/zjhch123/react-map-gl-demo-with-create-react-app)
Because of the Unclear `README.md`, I created a tutorial repository for someone who use create-react-app.😆

I am a Chinese, my English is not very good...Emmmmm...😔
Anyway,  follow my turorial, and you can run your project with no **BUG**

**Comment by warka0** [comment]
Thx bro! :)

**Comment by ibgreen** [comment]
@zjhch123 Added a link to our docs (https://github.com/uber/react-map-gl/blob/master/docs/get-started/README.md). Many thanks for doing this!
