### ISSUE TITLE
Invalid name: "@mapbox/gl-matrix"

### ISSUE THREAD

**Issue by bluhring** [uber/react-map-gl#327]
While trying to install this package using:
npm install --save react-map-gl

I get a handful of warnings about deprecated packages and modules, followed by an error that says:
Invalid name: "@mapbox/gl-matrix"

I have Darwin 15.6.0, Node 6.10.3, and NPM 3.10.10

I don't see anyone else mentioning this in the issues list or by searching Google, so hoping someone can help.

Thanks!

**Comment by abmai** [comment]
@bluhring we just recently release version 3. Is this still an issu eof ryou?
