### ISSUE TITLE
SDK to use 0.39 as the latest lib

### ISSUE THREAD

**Issue by jeveloper** [uber/react-map-gl#333]
Thank you for making this library great !

Just letting you know the 0.39 seems to have a lot of good bugs fixed.

Is there a way to force this lib to use 0.39 without forking ?

**Comment by abmai** [comment]
Hey @jeveloper - since there are a lot of changes that went into 0.39, we wanted to play around with it some more before updating fully. I don't have an ETA yet but look for it in a `3.1.x` release soon.

**Comment by jeveloper** [comment]
Ahh , totally understood :) 
Just thought that some of the issues reported here might be really caused by the mapbox lib instead :)

appreciate your work

**Comment by abmai** [comment]
Yep! We'll do our best to get the upgrade out there soon :). Thanks for pinging on this!
