### ISSUE TITLE
Investigate using individual d3 4.0 modules

### ISSUE THREAD

**Issue by vicapow** [uber/react-map-gl#34]
instead of the d3 3.0 kitchen sink module.

**Comment by samhogg** [comment]
@vicapow are you looking for help here?

Thought using the entirety of d3 was overkill and then came across this issue. Happy to jump in with a PR.

**Comment by vicapow** [comment]
Hi @samhogg! A PR that tackles this would be much appreciated.

**Comment by ibgreen** [comment]
This is implemented on latest master
