### ISSUE TITLE
How do I add fullscreen control?

### ISSUE THREAD

**Issue by gengue** [uber/react-map-gl#345]
I want to add fullscreen option into my map

I tried:
```
 const map = this.refs.map.getMap();
map.addControl(new mapboxgl.FullscreenControl());
```
The fullscreen icon is show on a corner but when I clicked on it, entesr to fullscreen but the old viewport still be de same and the markers and navigation controls disappear.

I use the following code in order to fix the viewport but the navigation controls and markers still missing.
```
  componentDidMount() {
    window.addEventListener('resize', this.resize);
  }

  componentWillUnmount() {
    window.removeEventListener('resize', this.resize);
  }

  /**
   * Resize the viewport when go to fullscreen 
   */
  resize = () => {
    this.setState({
      viewport: {
        ...this.state.viewport,
        width: this.props.width || window.innerWidth,
        height: this.props.height || window.innerHeight
      }
    });
  };

```

**Comment by ibgreen** [comment]
We don't have any built-in convenience function, but this is easy to do in any app, no need to use mapbox since browsers have a simple to use [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API). There might be npm modules for this as well...

**Comment by neotheicebird** [comment]
@ibgreen thanks for the advice, that took me in the right direction. I used [react-fullscreenable](https://github.com/ggingell/react-fullscreenable) to achieve it. 

Link to my implementation:  [MyMap.js](https://github.com/spacetime-creative-education/spacetime-education-site/blob/master/src/MyMap.js)
