### ISSUE TITLE
FlyTo and other transitions?

### ISSUE THREAD

**Issue by daumann** [uber/react-map-gl#350]
I am trying to create a flyTo transition to a geopoint but cannot find anything in the docs or examples.

Currently I have
```
this.setState({
      viewport: {
        ...this.state.viewport,
        latitude: event.lngLat[1],
        longitude: event.lngLat[0]
      }
    });
```
And **viewport** is attached to the **<MapGl** component.

This however let's the map "jump" to the new point while I would prefer a flyTo animation. Is that currently supported or are there workarounds? I saw a year old discussion in https://github.com/uber/react-map-gl/issues/70 but without conclusion.

**Comment by daumann** [comment]
@aderaaij shared a workaround at https://github.com/uber/react-map-gl/issues/286#issuecomment-322831219

**Comment by 1chandu** [comment]
CC: @ibgreen @shaojingli 
AFAIK there is no matching API for `flyTo`.
As a workaround you can check `examples/viewport-animation`, where TWEEN is used to animate the viewport change. We are also discussing on new camera animation/flyover API, will post the details once finalized.

**Comment by Pessimistress** [comment]
Now available via 3.2.0 release http://uber.github.io/react-map-gl/#/Documentation/introduction/whats-new

**Comment by yn5** [comment]
@Pessimistress Although the release notes state "smooth transition when using keyboard navigation or the NavigationControl" the transitioned is also smoothened when navigating through the map with the mouse. Is that intentional behaviour? Just checking before opening up a dedicated issue.

**Comment by Pessimistress** [comment]
@yn5 do you see said behavior on our [website](http://uber.github.io/react-map-gl)?

**Comment by yn5** [comment]
No I don't :) But I also don't see an example using the transition functionality, is there one? Maybe I was unclear: it is only after setting transitionDuration I experience this behavior, if the prop is not set everything behaves liked it used to.

**Comment by yn5** [comment]
O there is sorry: https://github.com/uber/react-map-gl/tree/3.2-release/examples/viewport-animation

I'll have a look what is different to my code, apparently I'm doing something wrong. Thanks for your help @Pessimistress !

**Comment by Pessimistress** [comment]
@yn5 If you copied the code on our [doc](http://uber.github.io/react-map-gl/#/Documentation/advanced/viewport-transition) I think I know what caused the problem. Refer to the example app while I fix the doc :(

**Comment by yn5** [comment]
@Pessimistress Yes that is exaclty what happened, after looking at the example it all words fine. Thanks for your help and effort!
