### ISSUE TITLE
Running tests failing in Event Manager

### ISSUE THREAD

**Issue by tonyd256** [uber/react-map-gl#356]
I'm trying to test a simple interactive map render and it's failing in the event manager. 

My test code using Mocha, Chai, Enzyme:
```
describe('<MyMap />', function() {
  it('loads successfully', function() {
    const wrapper = mount(<MyMap />);
    wrapper.should.not.Throw
  });
});
```
My React code:
```
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import InteractiveMap from 'react-map-gl';

export default class MyMap extends Component {
  render() {
    return (
      <div>
        <InteractiveMap
          width={400}
          height={400}
          latitude={37}
          longitude={-122}
          zoom={11.5}
          onViewportChange={(viewport) => {
            const { width, height, latitude, longitude, zoom } = viewport;
            console.log(viewport);
          }}
        />
      </div>
    );
  }
}
```
Here's the top of the stack trace:
```
TypeError: this.manager.get is not a function
      at EventManager._toggleRecognizer (node_modules/react-map-gl/src/utils/event-manager/event-manager.js:114:37)
      at EventManager._addEventHandler (node_modules/react-map-gl/src/utils/event-manager/event-manager.js:132:10)
      at EventManager.on (node_modules/react-map-gl/src/utils/event-manager/event-manager.js:85:12)
      at InteractiveMap.componentDidMount (node_modules/react-map-gl/src/components/interactive-map.js:158:18)
```
I was able to fix this by adding noop functions to the `ManagerMock` function.
```
  instance.get = chainedNoop;
  instance.set = chainedNoop;
```
I was going to open a PR but I see that the latest commit on master removes the event manager. When do you think you'll have a new version with that change available?

**Comment by ericsoco** [comment]
Yep, this [was fixed last month](https://github.com/uber/react-map-gl/commit/f5aa19d97d410b57deaa68f22736ab6b74a11b35) but is apparently not yet released. As you've noticed, we're breaking `EventManager` out into its own package since it's used by both [deck.gl](deck.gl) and react-map-gl, and the fix will live there moving forward.

Since it's fixed, I'm closing this, but will let @ibgreen or @Pessimistress speak to timeline for the next release.
