### ISSUE TITLE
How to add polygon with react-map-gl with click event handler?

### ISSUE THREAD

**Issue by intelcoder** [uber/react-map-gl#363]
I do not see a good example for polygon layer with onClick event. There is geoJson example doing similar thing but I do now want to use d3. Currently, I am adding layer with addLayer function like below
```
 map.addLayer({
      'id': 'feature',
      'type': 'fill',
      'source': {
        'type': 'geojson',
        'data': {
          'type': 'Feature',
          'geometry': {
            'type': 'Polygon',
            'coordinates': [[
              [-67.13734351262877, 45.137451890638886],
              [-66.96466, 44.8097],
              [-68.03252, 44.3252],
              [-69.06, 43.98],
              [-70.11617, 43.68405],
              [-70.64573401557249, 43.090083319667144],
              [-70.75102474636725, 43.08003225358635],
              [-70.79761105007827, 43.21973948828747],
              [-70.98176001655037, 43.36789581966826],
              [-70.94416541205806, 43.46633942318431],
              [-71.08482, 45.3052400000002],
              [-70.6600225491012, 45.46022288673396],
              [-70.30495378282376, 45.914794623389355],
              [-70.00014034695016, 46.69317088478567],
              [-69.23708614772835, 47.44777598732787],
              [-68.90478084987546, 47.184794623394396],
              [-68.23430497910454, 47.35462921812177],
              [-67.79035274928509, 47.066248887716995],
              [-67.79141211614706, 45.702585354182816],
              [-67.13734351262877, 45.137451890638886]]]
          }
        }
      },
      'layout': {},
      'paint': {
        'fill-color': 'rgba(200, 100, 240, 0.4)',
        'fill-outline-color': 'rgba(200, 100, 240, 1)'
      }
    });

```

It seems I can add event handler with dom but is there anyway I can do that in react way ? 
For example

```
<Polygon {...data} onClick={this.onClick}/>
```

**Comment by ibgreen** [comment]
@intelcoder 
It is a reasonable question, unfortunately I don't think this is possible at the moment.

I realize this is an indirect answer, but we do most of our visualization overlays on top of react-map-gl using deck.gl which does offer a reactive interface, so the [deck.gl `GeoJsonLayer`](https://uber.github.io/deck.gl/#/documentation/layer-catalog/geojson-layer) is certainly one option.

**Comment by intelcoder** [comment]
@ibGreen
Thank you for the answer! I was able to add click/hover handler direct to layer. 
But I am having hard time to find doc and example about how to update layer color on event such as line color. Would you be able to guide me to some example or doc?

```jsx
<DeckGL  {...this.state.viewport} layers={[
            new GeoJsonLayer({
              id: 'geojson-layer',
              data: {
                'type': 'Feature',
                'geometry': {
                  'type': 'Polygon',
                  'coordinates': [[
                    [-67.13734351262877, 45.137451890638886],
                    [-66.96466, 44.8097],
                    [-68.03252, 44.3252],
                    [-69.06, 43.98],
                    [-70.11617, 43.68405],
                    [-70.64573401557249, 43.090083319667144],
                    [-70.75102474636725, 43.08003225358635],
                    [-70.79761105007827, 43.21973948828747],
                    [-70.98176001655037, 43.36789581966826],
                    [-70.94416541205806, 43.46633942318431],
                    [-71.08482, 45.3052400000002],
                    [-70.6600225491012, 45.46022288673396],
                    [-70.30495378282376, 45.914794623389355],
                    [-70.00014034695016, 46.69317088478567],
                    [-69.23708614772835, 47.44777598732787],
                    [-68.90478084987546, 47.184794623394396],
                    [-68.23430497910454, 47.35462921812177],
                    [-67.79035274928509, 47.066248887716995],
                    [-67.79141211614706, 45.702585354182816],
                    [-67.13734351262877, 45.137451890638886]]]
                }
              },
              lineWidthScale: 4,
              opacity: 0.4,
              filled: true,
              stroked: true,
              lineWidth: 2,
              lineColor:  [255, 0, 0],
              lineWidthMinPixels: 2,
              wireframe: true,
              getLineColor: f => [255, 0, 0],
              getFillColor: f => [255, 0, 0, 0],
              pickable: true,
              onHover: info => console.log('Hovered:', info),
              onClick: info => console.log('Clicked:', info)
            })
          ]}/>


```

**Comment by ibgreen** [comment]
@intelcoder 

deck.gl has a mechanism called [`updateTriggers`](https://uber.github.io/deck.gl/#/documentation/api-reference/layer?section=data-properties). Using this you can tell a deck.gl layer which attributes need to be updated.

When you hover over a line, you'd save the index of that line (default -1), and then your `getLineColor` would return a different color for that index.

You'll have to check the docs for the exact details, but it should roughly look something like:
 ```
   getLineColor: (f, i) => i === this.state.selectedIndex ? color1 : color2,
   updateTriggers: {lineColor: this.state.selectedIndex}
```

**Comment by intelcoder** [comment]
@ibgreen 
Thank you for the help ! #

**Comment by sonickseven** [comment]
> ```js-jsx
> lineWidthScale
> ```

Please write de imports because i have not could find them

`import DeckGL from '@deck.gl/react'`

but where i can fount `GeoJsonLayer` ??

**Comment by sonickseven** [comment]
> @intelcoder
> It is a reasonable question, unfortunately I don't think this is possible at the moment.
> 
> I realize this is an indirect answer, but we do most of our visualization overlays on top of react-map-gl using deck.gl which does offer a reactive interface, so the [deck.gl `GeoJsonLayer`](https://uber.github.io/deck.gl/#/documentation/layer-catalog/geojson-layer) is certainly one option.

The link is broken!!!

**Comment by saharilarshad** [comment]
may i add a question.. how to make a popup once we click on polygon?

**Comment by the-habu** [comment]
> > ```
> > lineWidthScale
> > ```
> 
> Please write de imports because i have not could find them
> 
> `import DeckGL from '@deck.gl/react'`
> 
> but where i can fount `GeoJsonLayer` ??

@deck.gl/layers

> The link is broken!!!

This is a closed issue and not a documentation. Google helps. (!!!)
