### ISSUE TITLE
Uncaught ReferenceError when imported react-map-gl to built using webpack2 

### ISSUE THREAD

**Issue by asling** [uber/react-map-gl#364]
react-map-gl version:
3.0.0-alpha.13

Steps to Trigger Problem
npm run start:production
Set up MapGl with webpack 2 via [react-boilerplate](https://github.com/react-boilerplate/)
after built, I check it in browser
https://user-images.githubusercontent.com/5282933/30639665-6525c79e-9e32-11e7-8a20-b24e3c29fa82.png
Map is used with import MapGL from 'react-map-gl';

Configuration is as follows:
Base:
https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/webpack/webpack.base.babel.js
Production:
https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/webpack/webpack.prod.babel.js

Thanks for your help!

**Comment by ibgreen** [comment]
@asling I notice you are still using an alpha version. The [official 3.0.0](https://uber.github.io/react-map-gl/#/Documentation/introduction/whats-new) version was released end of July. Let's first check if the problem is still reproducible on that version.

**Comment by asling** [comment]
@ibgreen I update the version to latest 3.0.4. But the error is still exist. After I add `devtool: 'eval'` to package.json, the error disappear. It is so weird. See https://github.com/mapbox/mapbox-gl-js/issues/4359. This also happens when running mapbox-gl.
And it doesn't work for me 
using `new webpack.optimize.UglifyJsPlugin({
            sourceMap: true,
            compress: {
                warnings: false,
                comparisons: false,  // don't optimize comparisons
            },
        }),`
this is a solution below mapbox-gl issue.
