### ISSUE TITLE
Deckgl geojsonLayer does not stay when the mapRef execute flyTo or fitBounds function

### ISSUE THREAD

**Issue by intelcoder** [uber/react-map-gl#366]
Currently, I am using interactive map.  Whenever I use flyTo or fitBounds function using mapRef. It moves map but Layer which was in different city follows together.

For example, I have GeoJsonLayer which covers New York. Then, I use flyTo function to Toronto. New York layer follows to Toronto and covers Toronto.

**Comment by Pessimistress** [comment]
@intelcoder As part of the React paradigm, you must animate the viewport from outside of the component and pass it in as props. Check out the [animation](https://github.com/uber/react-map-gl/tree/master/examples/viewport-animation) example.
