### ISSUE TITLE
onClick returning empty event.features array

### ISSUE THREAD

**Issue by callil** [uber/react-map-gl#371]
Hi folks, 
I'm attempting to return features from a click event on my map. According to the `InteractiveMap` docs, I should be getting an array of features under the map from the `queryRenderedFeatures` api. 

Right now I'm just getting an empty array. Is there something I'm missing to make this work?
Thanks

**Comment by ibgreen** [comment]
@callil I believe the layers must be marked as `interactive`:
https://github.com/uber/react-map-gl/blob/master/src/components/static-map.js#L139
https://github.com/uber/react-map-gl/blob/master/src/utils/style-utils.js#L4

**Comment by yn5** [comment]
I'm having the same problem with onHover.

@ibgreen How do you add that property to the layers in the style if you just pass a style url to `react-map-gl`?

```
<MapGL
  mapStyle={mapbox://styles/mapbox/streets-v9}
  mapboxApiAccessToken={MAPBOX_TOKEN}
  onHover={e => console.log(e.features)}
/>
```

**Comment by Pessimistress** [comment]
I believe this is a regression. Will get a fix in the next patch release.

**Comment by Pessimistress** [comment]
3.1.5
