### ISSUE TITLE
API access token is required ERROR despite never using Mapbox Layers (introduced in 3.1)

### ISSUE THREAD

**Issue by daumann** [uber/react-map-gl#385]
I recently bumped react-map-gl from "3.0.4" to "3.1.0" and my app stopped working because it throws the error **An API access token is required to use Mapbox GL** during _initialization_.

I am not using any of mapbox layers/fonts/icons. Is an access token now mandatory simply for using this package?

**Comment by ibgreen** [comment]
@daumann 3.1.0 may have been published prematurely. Recommend you pin to 3.0.x while we sort this out.

**Comment by Pessimistress** [comment]
@daumann The missing API access token message should not have been printed as an error, but that should not have stopped the application from rendering. Can you provide more context of how you are using react-map-gl?

**Comment by Pessimistress** [comment]
@daumann Pinging again. Your custom map tiles should still render in spite of the console error. Can you tell us more about the problem?

**Comment by daumann** [comment]
@ibgreen @Pessimistress I now bumped the version to **3.1.1** and while the map is working as normal, I get this notokenwarning element rendered on top of my map:

![notokenwarning](https://user-images.githubusercontent.com/5303880/32624216-de1c82b4-c588-11e7-82a8-330be9244b82.png)

Here is the relevant element: https://github.com/uber/react-map-gl/blob/5cafff8f30640e903fc43c4b6c2b5b2c21f3b2e3/src/components/static-map.js#L178-L193

Is there a way to hide/ surpress it? On a conceptual level, shouldn't be a warning in the logs be enough?

This issue was introduced here: https://github.com/uber/react-map-gl/pull/370

**Comment by ibgreen** [comment]
https://github.com/uber/react-map-gl/pull/400

**Comment by Pessimistress** [comment]
Fixes published in 3.1.2 patch release.

**Comment by daumann** [comment]
![5newerrors](https://user-images.githubusercontent.com/5303880/32660293-8e06862c-c622-11e7-8360-df041b23e75b.png)
Unfortunately with the new 3.1.2 patch release I encounter those 5 new errors in my log (the app works though). Any idea what caused this in the new release (from 3.1.1 to 3.1.2)?

I suspected mapStyle to be malformed, but as you can see in the above image I print out mapStyle right before the errors (which get triggered when react-map-gl component is rendered) and it has version sources and layers as properties.

**Comment by Pessimistress** [comment]
@daumann Thanks for reporting this, it seems that these were suppressed by the previous token error message?
I can reproduce it. Should be an easy fix.

**Comment by Pessimistress** [comment]
@daumann Can you give 3.1.3 a try?

**Comment by daumann** [comment]
@Pessimistress works perfectly. No errors in the logs. Thanks!
