### ISSUE TITLE
Rotating the map with shift+drag can lead to AssertionError

### ISSUE THREAD

**Issue by boromisp** [uber/react-map-gl#392]
### The line that fails:
https://github.com/uber/react-map-gl/blob/25c3b795bab5e71cc2c4e857c3e47d79bf6eef28/src/utils/map-state.js#L178

### How to reproduce:

I'm not sure, which version is used on the examples pages, but the bug can easily be reproduced there (e.g. https://uber.github.io/react-map-gl/#/Examples/geojson).

1. Open dev tools
2. Start shift+drag from one side of the map
3. Drag in one direction more than the width of the map.

Maybe instead of assert, an offset / modulo could be used?

**Comment by Pessimistress** [comment]
Fix published in 3.1.2 patch release.
