### ISSUE TITLE
demo of viewport-animation doesn't work

### ISSUE THREAD

**Issue by cheekahao** [uber/react-map-gl#395]
when I copy the viewport-animation demo to a new folder, and `npm install` it. it doesn't work.
I log `experimental`, it only have `MapControls` and `autobind` props.
the props ‘experimental.viewportFlyToInterpolator’ is undefined.
I check the source code of react-map-gl in my `node_modules`, it different with github. like this: 
```
// code of src/index.js in my node_modules
    export const experimental = {
        MapControls,
       autobind
    };

```

**Comment by ibgreen** [comment]
@cheekahao Could you copy the example from the `3.1-release` branch and try again.

We are developing a new improved animation system on master,  but we haven't published the library yet so you can't use it standalone. We should probably have put the updated demo in a separate folder to avoid confusion.

**Comment by cheekahao** [comment]
@ibgreen ok, thank you. But I want to use this api in my project,  I will consult your opinion and discuss with my colleagues how to solve this problem

**Comment by 1chandu** [comment]
@cheekahao we are planning to include this feature in next release. (tentatively in mid-november).
