### ISSUE TITLE
StaticMap: mapStyle prop-types overly strict

### ISSUE THREAD

**Issue by GunnarSturla** [uber/react-map-gl#396]
StaticMap requires that mapStyle is either string of an instance of Immutable.Map, while not allowing it to be a regular JS object.

[The documentation](http://uber.github.io/react-map-gl/#/Documentation/api-reference/static-map) says that it can be {String | Object | Immutable.Map}, and mapbox-gl-js also [allows a plain object](https://www.mapbox.com/mapbox-gl-js/api/#map). Is there a reason for restricting mapStyle to an Immutable.Map?

I solved this problem like this:
```
import { Map as ImmutableMap } from 'immutable';
import ms from './mapStyle.js';

const mapStyle = ImmutableMap(ms);
```

However, since the 3.1 update, I started the following error from [style-utils.js](https://github.com/uber/react-map-gl/blob/master/src/utils/style-utils.js#L9) : `TypeError: l.get is not a function`, because it seems that while mapStyle is an Immutable.Map, its children aren't (and thus don't have a `.get` function).

So my problem is I can't use my mapStyles because if it's a plain object (as permitted by the docs, and mapbox-gl-js), then  prop type fill fail, but if I create an Immutable.Map, I'll get the error above.

Should I create the Map differently? Should the prop-type validation be updated to accept plain objects? Will that break anything?

**Comment by ibgreen** [comment]
> However, since the 3.1 update, I started the following error from style-utils.js : TypeError: l.get is not a function, because it seems that while mapStyle is an Immutable.Map, its children aren't (and thus don't have a .get function).

This sounds like a regression, I don't think we have intentionally done any changes to style handling in 3.1 except maybe refactor some of the surrounding code. Will mark this as a bug until we have clarity.

```
import Immutable from 'immutable';
const mapStyle = Immutable.Map(ms);
```
I think there is a method `Immutable.fromJS()` that converts the entire tree to Immutable. Maybe that will help you get unblocked?

**Comment by mshrieve** [comment]
It's true that although the docs say an Object type is valid for the mapStyle prop, the StaticMap component enforces a propType of either string or Immutable object.
If you'd like to convert your JS object mapStyle to an Immutable map, use Immutable.fromJS to do a deep conversion.

**Comment by Pessimistress** [comment]
3.1.5
