### ISSUE TITLE
If I use react-map-gl ,can I import mapbox-gl at the same time.

### ISSUE THREAD

**Issue by Wwangchen** [uber/react-map-gl#401]
import MapGL, { SVGOverlay } from 'react-map-gl';
import mapboxgl from 'mapbox-gl';
I want to know the MapGL and the mapboxgl are the same object ?
Is it correct I use like this? I look forward to your reply.

**Comment by abmai** [comment]
Hey @Wwangchen, I don't think you'll have issue except that you'll have to instantiate a new mapboxgl instance manually.

What use case are you solving for here?

**Comment by pannz** [comment]
Can react-map-gl draw lines, draw circle of a point ...

As I can see the api of react-map-gl, its not enough of use
