### ISSUE TITLE
Upgrade mapbox-gl to version >= 0.42.1 to fix map flickering

### ISSUE THREAD

**Issue by tbergman** [uber/react-map-gl#414]
Please see [#5490](https://github.com/mapbox/mapbox-gl-js/issues/5490) and [#5704](https://github.com/mapbox/mapbox-gl-js/pull/5704) for a description of the flickering issue.

**Comment by antonjb** [comment]
We are running into this issue too with Chrome Version 62.0.3202.94 (Official Build) (64-bit).

**Comment by Pessimistress** [comment]
Now available via 3.2.0 release http://uber.github.io/react-map-gl/#/Documentation/introduction/whats-new

**Comment by tbergman** [comment]
Thanks a lot!
