### ISSUE TITLE
Map with marker always captures scroll events

### ISSUE THREAD

**Issue by storybynumbers** [uber/react-map-gl#415]
It seems that markers always capture mouse events, regardless of the settings. The following map renders as expected, but I cannot scroll past it. If I remove the marker, I can.

```jsx
<ReactMapGL
    dragPan={false}
    dragRotate={false}
    captureDoubleClick={false}
    mapStyle={_config.mapboxStyle}
    onViewportChange={this.handleViewport}
    scrollZoom={false}
    {...this.state.viewport}>

    <Marker latitude={44.427824} longitude={-73.213587} offsetLeft={154 / -2}
            captureScroll={false} captureDrag={false} captureClick={false} captureDoubleClick={false}
            offsetTop={-38}>
        <div className={css.marker}>
            <IconShop width={35}/>
            <h3>Marker</h3>
        </div>
    </Marker>

</ReactMapGL>
```

**Comment by tlenclos** [comment]
Same issue here, the settings `scrollZoom` just stop the scroll on the map but still capture the wheel event.

**Comment by tlenclos** [comment]
It seems that the event is always captured on the BaseControl component here event when `this.props.captureScroll` equals false https://github.com/uber/react-map-gl/blob/master/src/components/base-control.js#L66.

Adding a condition on the event handler fix the issue but I don't know if this is a clean fix. Any insights @Pessimistress ?
```javascript
const events = {};

if (this.props.captureScroll) {
  events.wheel = this._onEvent;
}
```

**Comment by Pessimistress** [comment]
@storybynumbers @tlenclos Thanks for reporting this problem. I'll get a fix out asap.

**Comment by Pessimistress** [comment]
3.1.5
