### ISSUE TITLE
Multi-touch gesture “rotate” do not work

### ISSUE THREAD

**Issue by Nut** [uber/react-map-gl#416]
Hi there,

It seems to me that the multi-touch gestures are not working for touch devices. I’ve tried the uber examples and created a project by myself but not all touch gestures are working. The only thing I can do is to zoom in and out but I cannot rotate the map. Does anyone have any idea why?
Rotation with right click/shift+mouse is working very well on desktop. 

Best regards,
Nut

**Comment by Pessimistress** [comment]
@Nut The touch gestures are not fully implemented. Would you help us test them if I stage something for 3.2?

**Comment by Nut** [comment]
Oh okay… I didn’t know that. I thought all multi-touch gestures are already implemented because the [release doc for v3.0](https://github.com/uber/react-map-gl/blob/3.0-release/docs/whats-new.md) says: “Full support for multi-touch gestures…”. 
However, I would like to help you to test the gestures. What should I do?

**Comment by Pessimistress** [comment]
@Nut Sorry about that. Give `3.2.0-alpha.3` a try -- you'll need to enable the [touchZoom & touchRotate](https://github.com/uber/react-map-gl/blob/master/docs/components/interactive-map.md#touchzoom-bool-default-true) props.

**Comment by Pessimistress** [comment]
Now available via 3.2.0 release http://uber.github.io/react-map-gl/#/Documentation/introduction/whats-new
