### ISSUE TITLE
Transition Classes not available via npm

### ISSUE THREAD

**Issue by bensteers** [uber/react-map-gl#417]
Can you push the transition classes (i.e. FlyToInterpolator) to npm? I tried installing react-map-gl from the master branch, but it's not finding the module when I do that.

**Comment by balthazar** [comment]
I'm not up-to-date on the exact completion status of the props animation, but generally, we won't publish things that are not ready to be installed to the broad audience of our package. If you want to be bleeding edge, you can clone the repository and link the dependency to your own project. You might encounter bugs, and an helpful thing would be to report them to us 🙂

**Comment by Stupidism** [comment]
When can we start using `FlyToInterpolator`?

**Comment by rmakovyak** [comment]
Can you align your documentation accordingly then? This is a bit confusing.

**Comment by ibgreen** [comment]
> I'm wondering when can we start using FlyToInterpolator? Do you guys have a timeline to release this feature?

@Stupidism Our goal is to publish new versions of our frameworks, including react-map-gl this month (Dec 2017). We should be able to publish a 3.2-beta release quite soon.

> Can you align your documentation accordingly then? This is a bit confusing.

@rmakovyak Certainly. Where in the docs is it mentioned? https://uber.github.io/react-map-gl/#/

**Comment by Pessimistress** [comment]
@bensteers @rmakovyak The master branch is the active dev branch and is currently publishing to `3.2.0-alpha.x`. For examples and docs of the latest release, please check [the 3.1-release branch](https://github.com/uber/react-map-gl/tree/3.1-release).

**Comment by Stupidism** [comment]
@ibgreen I found the demo in the [examples](https://uber.github.io/react-map-gl/#/Examples/camera-transition) page.  Since it's not documentated, I clicked `view code` button to see the source code. And saw it in the [master branch](https://github.com/uber/react-map-gl/blob/master/examples/viewport-animation/src/app.js). The problem's the link should link to 3.1-release branch.

**Comment by rmakovyak** [comment]
@Pessimistress, @ibgreen ok, I was looking in a wrong place then ;)

**Comment by Pessimistress** [comment]
@Stupidism Thanks for pointing it out, I will fix the links. If you need to use viewport transition today, you can try `3.2.0-alpha.3`.

**Comment by Pessimistress** [comment]
Now available via 3.2.0 release http://uber.github.io/react-map-gl/#/Documentation/introduction/whats-new
