### ISSUE TITLE
Support create-react-app custom environment variable

### ISSUE THREAD

**Issue by MichielDeMey** [uber/react-map-gl#425]
As per the spec of `create-react-app`, every environment variable should begin with `REACT_APP_ ` for any custom environment variables to be added. This is due to a security reason so you don't accidentally expose sensitive environment variables.

See https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables for more information.

Is this something we can support by adding an additional ENV variable check?

**Comment by Pessimistress** [comment]
Published 3.3.8
