### ISSUE TITLE
Improve speed with a large geojson?

### ISSUE THREAD

**Issue by FergusDevelopmentLLC** [uber/react-map-gl#428]
Hi!
Great framework. I am enjoying testing it. This is my latest test, basically from the examples.
https://github.com/FergusDevelopmentLLC/deckgl-geojson
Live in "production" here (it's slow to load, this is the problem):
[http://104.236.16.91:8650/deckgl-geojson/](http://104.236.16.91:8650/deckgl-geojson/)

I am purposely sending a large geojson polygon [dataset](http://104.236.16.91:8650/deckgl-geojson/data/nps.geojson), in this case the boundaries of the U.S. National Park Service. My goal is to compare react/deckgl to what I was doing with my stack and vuejs/leaflet here:
[https://github.com/FergusDevelopmentLLC/geodev-node-rest/](https://github.com/FergusDevelopmentLLC/geodev-node-rest/).

I had high hopes based on my tests with point data and [hexagon layers](http://104.236.16.91:8650/starbucks-deckgl/). Is there anything obvious I can do to increase performance (besides simplifying geojson).

Also, is there a slack or other platform where people connect around working with the framework?

thanks!

**Comment by Pessimistress** [comment]
Looks like this is a question regarding deck.gl. Could you open it in https://github.com/uber/deck.gl instead?
