### ISSUE TITLE
Can I add a GeoJSON line like they do in the (mapbox-gl-js documentation) using react-map-gl ?

### ISSUE THREAD

**Issue by aziz-boudi4** [uber/react-map-gl#429]
I'm trying to add a GeoJSON line to show car direction between a point A and a point B ( like they have in the official documentation of  mapbox-gl-js (https://www.mapbox.com/mapbox-gl-js/example/geojson-line/) 

But the docs of react-map-gl doesn't talk about that at all.

How can I achieve something similar to this : 

![screen shot 2017-12-20 at 5 55 10 pm](https://user-images.githubusercontent.com/7435015/34237168-0996ba44-e5b0-11e7-838e-efb54df7a79c.png)

**Comment by aziz-boudi4** [comment]
I created a stackoverflow question : https://stackoverflow.com/questions/47916941/can-i-add-a-geojson-line-like-they-do-in-the-mapbox-gl-js-documentation-using

**Comment by Pessimistress** [comment]
@aziz-boudi4 There are two ways you can do this:
- Add the custom data source to a JSON format map style, or
- Use the `getMap()` method to get the mapbox instance, and follow the mapbox-gl example.

**Comment by Pessimistress** [comment]
Added article to docs: [adding custom data](http://uber.github.io/react-map-gl/#/Documentation/getting-started/adding-custom-data)
