### ISSUE TITLE
Geo-located data drifts when resizing window at max zoom

### ISSUE THREAD

**Issue by JorinRBM** [uber/react-map-gl#439]
From a mis-posted issue of mine on deck.gl. https://github.com/uber/deck.gl/issues/1306

"If you navigate to this url: https://uber.github.io/deck.gl/#/documentation/layer-catalog/arc-layer in a non-maxed out chrome window, you can make the points drift by zooming out all the way, then dragging the window larger vertically.

This same effect can be seen when you have an implementation of geo-located data in your own project, so it seems there is a bug in updating the zoom of the data positions along with the zoom of the underlying map as the resize occurs."

It was recommended that I repost to this repo as the discussion in the previous issue revealed that the bug might be traceable to react-map-gl.

**Comment by Pessimistress** [comment]
The fix has been included in the 3.2.2 patch release.
