### ISSUE TITLE
custom overlay not passed to staticmap children until viewport edited

### ISSUE THREAD

**Issue by ahoarfrost** [uber/react-map-gl#444]
I wrote a custom polygon overlay, but when a page is loaded the overlay isn't initialized so you see a blank map. Once I change the viewport by zooming or panning, the overlay is initialized and I can see the polygons as expected. When I look in the dev tools I notice that the data I expect to see in the children props are present in the InteractiveMap, but the children for StaticMap are null. 

my map component looks like this: 

```
import React from 'react';
import ReactMapGL from 'react-map-gl';
import MapOverlay from './MapOverlay';

const MAPBOX_ACCESS_TOKEN = 'pk.eyJ1IjoibWV0YXNlZWsiLCJhIjoiY2o3YjQ4anVrMG5vaDMycW14bWcwbTBnaSJ9.67xUW2hLL2laKI8XyY91dA';

var MapDeckGL = React.createClass({
  getInitialState : function() {
    return {
      viewport: {
        'width': 500,
        'height': 500,
        'latitude': 0,
        'longitude': 0,
        'zoom': 0,
        'maxZoom': 16,
        'pitch': 0,
        'fov':100,
      }
    }
  },

  _onViewportChange(viewport) {
    this.setState({
      viewport: {...this.state.viewport, ...viewport}
    });
  },

  render : function() {
    return (
      <div className="explore-map-contents">
        <ReactMapGL
          {...this.state.viewport}
          onViewportChange={this._onViewportChange}
          mapboxApiAccessToken={MAPBOX_ACCESS_TOKEN}
        >
          <MapOverlay
            viewport={this.state.viewport}
            data={this.props.mapdata}
          />
        </ReactMapGL>
      </div>
    );
  }
});

export default MapDeckGL;
```

and the MapOverlay component looks like:

```
import React from 'react';
import {setParameters} from 'luma.gl';
import DeckGL, {PolygonLayer} from 'deck.gl';


var MapOverlay = React.createClass({
  getInitialState : function() {
    return {
      hoverInfo : null
    }
  },

  render : function() {
    const {viewport, data} = this.props;

    if (!data) {
      return null;
    }

    const layer = new PolygonLayer({
      id: 'square',
      data,
      filled: true,
      extruded: false,
      pickable: true,
    });

    return (
      <div>
        <DeckGL {...viewport} layers={ [layer] } />
      </div>
    );
  }
});

export default MapOverlay;
```

I tried to initialize the viewport with ComponentWillMount to see if that would initialize the map as expected, no luck. Any help appreciated!

**Comment by ahoarfrost** [comment]
a small update: if I change the map in the map component from <ReactMapGL> to calling <StaticMap> directly, I can see my polygons right away as expected. But of course I don't have any interactivity, which I'd like to preserve. 

also, if you want to try to run this here's some sample data for what this.props.mapdata should look like, which will show a few squares:

[
{count:7, fillColor:[66, 91, 161,113], lat:34.9, lon:-15.4, polygon:[[-20.4, 29.9],[-20.4, 39.9],[-10.4, 39.4],[-10.4, 29.9],[-20.4, 29.9]]},
{count:24, fillColor:[66, 91, 161, 136], lat:44.9, lon:-15.4, polygon:[[-20.4, 39.9],[-20.4, 49.9],[-10.4, 49.4],[-10.4, 39.9],[-20.4, 39.9]]},
{count:18, fillColor:[66, 91, 161, 136], lat:54.9, lon:-15.4, polygon:[[-20.4, 49.9],[-20.4, 59.9],[-10.4, 59.4],[-10.4, 49.9],[-20.4, 49.9]]}
]

**Comment by Pessimistress** [comment]
It sounds like an issue fixed in https://github.com/uber/react-map-gl/pull/413. What is the react-map-gl version you're using?

**Comment by Jivings** [comment]
I'm running v3.2 and still have a similar issue. If I update the markers in my overlay then the map doesn't update until I make a change to the viewport.

My workaround is to make an imperceptible change to the zoom to force a render.

```
componentWillReceiveProps(nextProps) {
  const { markers } = this.props;
  const { markers: nextMarkers } = nextProps;
  const markerIds = markers.map(m => m.key);
  const newMarkerIds = markers.map(m => m.key);
  if (!_.isEqual(markerIds.sort(), newMarkerIds.sort())) {
    this.setState({
      viewport: {
        ...this.state.viewport,
        zoom: this.state.viewport.zoom - 0.0001
      }
    })
  }
}
render() {
    const { viewport } = this.state;
    const { width, height, longitude, latitude, zoom } = viewport;
    const { markers } = this.props;
    return (
      <ReactMap
        latitude={ latitude }
        longitude={ longitude }
        zoom={ zoom }
        width={ width }
        height={ height }
        onViewportChange={(vp) => this.viewportChange(vp)
      >
        { markers }
     </ReactMap>
    );
  }```

**Comment by ahoarfrost** [comment]
I was on 3.1.3, and updating  to 3.2.0 fixed my problem (although I need to explicitly import mapbox-gl.css in my index.html now). Sure seems like something I should have tried already - thanks!
