### ISSUE TITLE
TransitionEasing Documentation is not helpful

### ISSUE THREAD

**Issue by mmmeff** [uber/react-map-gl#453]
https://github.com/uber/react-map-gl/blob/master/docs/components/interactive-map.md#transitioneasing-function

Not sure what I'm supposed to gather from a linked website that shows CSS timing functions and jQuery plugins.

Can I have a real example of how to actually use this prop with LinearInterpolator?

**Comment by Pessimistress** [comment]
Thank you for the feedback. I agree the linked site is confusing.

An easing function takes a number between `[0, 1]` as argument and outputs another number. You can generate an easing function using [d3-ease](https://www.npmjs.com/package/d3-ease) or any of the other easing libraries out there.

The default value of the `transitionEasing` prop is linear transition:
```
transitionEasing={t => t}
```
Smooth in and out using d3:
```
transitionEasing={d3.easeQuadInOut}
```
Elastic transition using d3:
```
transitionEasing={d3.easeElasticOut}
```
Custom polynomial easing:
```
transitionEasing={t => Math.pow(t, 2.5)}
```
