### ISSUE TITLE
Update to mapbox-gl-js version 44.0 to satisfy stricter CSP policies

### ISSUE THREAD

**Issue by kristiehowboutdat** [uber/react-map-gl#458]
# Ask
Upgrade to use `mapbox-gl-js` version 44.0 (https://www.npmjs.com/package/mapbox-gl).

# Why
Mapbox gl js upgraded to [remove the need to use script-src unsafe-eval](https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md) in [this PR](https://github.com/mapbox/mapbox-gl-js/issues/559) for Content Security Policies.

I have a strict CSP that I have to use, and I am unable to add `unsafe-eval` to that CSP directive. Upgrading to the latest version would solve this problem while allowing me to use this library and deck.gl. It's also a security win in general.

Thank you!

**Comment by Pessimistress** [comment]
react-map-gl@3.2.4
