### ISSUE TITLE
Can't install via yarn nomnom-2.0.0.tgz: Request failed 

### ISSUE THREAD

**Issue by istarkov** [uber/react-map-gl#462]
How to reproduce:

```
yarn cache clean
yarn add react-map-gl
```

result

```
error An unexpected error occurred: "https://registry.yarnpkg.com/nomnom/-/nomnom-2.0.0.tgz: Request failed \"404 Not Found\"".
```

**Comment by koistya** [comment]
Seems like an issue with `nomnom` package or NPM registry.

**Comment by istarkov** [comment]
`warning nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.`

**Comment by istarkov** [comment]
As a workaround: 

removing `nomnom` from dependencies of  `jsonlint-lines-primitives@~1.6.0:` in `yarn.lock` allow to install and use `map`.

**Comment by istarkov** [comment]
Seems like solved https://github.com/zaach/jsonlint/issues/103#issuecomment-367416531
Now it works
