### ISSUE TITLE
PinchZoom End

### ISSUE THREAD

**Issue by kershnerd** [uber/react-map-gl#466]
I am using getCursor to tell if the map is being dragged and that is working well.  

I am using onTransitionStart/End/Interrupted to tell when the map is being transitioned and this is working well.

The last piece to my puzzle is when doing a pinch zoom, **how can I tell when the zoom had completed** (completed meaning, the fingers have been lifted from the trackpad)?  The onViewportChange is correctly being called and view is updated, but I don't want to make API calls at 60 times a second.

Can someone point me to how I might detect when pinchZoom has ended?

**Comment by kershnerd** [comment]
I was able to create a custom control class:

```
export default class MyMapControls extends experimental.MapControls {

  constructor(props) {
    super(props);
    this.props = props;
    this.events = ['panend', 'wheel'];
  }

  // override the default handler in MapControls
  handleEvent(event) {
    if (event.type === 'panend') {
      this.props.onPanEnd();
    }

    else if (event.type === 'wheel') {
      this.props.onZoom();
    }

    return super.handleEvent(event);
  }
}
```

Looking at the events here: https://uber.github.io/react-map-gl/#/Documentation/api-reference/map-controls
... I am unable to see any events that would let me know when zoom has ended.  Is there an event I missed?

**Comment by Pessimistress** [comment]
You may be looking for `pinchend`?
There's no "zoomEnd" to wheel zoom as they are handled as discrete events.
