### ISSUE TITLE
Handling onClick with custom overlays

### ISSUE THREAD

**Issue by rimig** [uber/react-map-gl#470]
I'm writing some custom overlays that use `CanvasOverlay` and `SVGOverlay`. I want to capture mouse events (click/hover) within these overlays and be able to unproject and store the lat/lng in some state.

In the old API I got the viewport within the React context, however, now it seems the API wants me to use the `redraw` method to access the viewport's project/unproject. So, in this mode does it seem reasonable to add an onClick wrapper that would give me the mouse event and the viewport?

Then I could do something like:
```
<CanvasOverlay
  redraw={this._redraw}
  onClick=(({mouseEvent, unproject}) => {
    this.setState({
      myPoint: getMouseCoords(mouseEvent, unproject)
    });
  })
```

Even better if it just gave me lat/lng of mouse events.

**Comment by Pessimistress** [comment]
Would it make sense if the `render` method of overlay classes just passes through user props to the root component (`canvas`, `div` or `svg`)? I can see props needed for every React synthetic event.

**Comment by Pessimistress** [comment]
Closed for inactivity.

**Comment by Alexandrescu** [comment]
@Pessimistress, I ran into the same issue. Passing in all the props to the underlying elements would be super useful!
