### ISSUE TITLE
breaks parcel bundle

### ISSUE THREAD

**Issue by fczuardi** [uber/react-map-gl#472]
When trying to use this lib on a project and bundle it with Parcel I get the error ``_typeof is not defined``

**Comment by fczuardi** [comment]
Possibly related: 
https://github.com/parcel-bundler/parcel/issues/671
https://github.com/parcel-bundler/parcel/issues/679
https://github.com/parcel-bundler/parcel/issues/697

**Comment by kunal-mandalia** [comment]
We're seeing this issue too. Using webpack 3/babel on a customised ejected create react app config. Dev build work fine.

**Comment by kunal-mandalia** [comment]
Turns out our issue was including node modules in webpack. Removing that fixed the issue.

**Comment by Pessimistress** [comment]
@kunal-mandalia Is it ok to close this issue? Is it an error others might encounter as well?

**Comment by cyrilchapon** [comment]
@Pessimistress 

> including node modules in webpack

Is actualy not an "issue" but a feature for some people.
Some want to transpile react-map-gl **their** way with their browser requirements etc.

This should be reopened

**Comment by ThunderDev1** [comment]
Having the same problem, did you find a solution @fczuardi ?

**Comment by allen-n** [comment]
@fczuardi same question, I too am having this issue. A year later and I still cannot find any fixes.
