### ISSUE TITLE
Built failed with babel-loader 8.x | babel 7.x?

### ISSUE THREAD

**Issue by huaying** [uber/react-map-gl#473]
Hi, 
I am using `webpack 4 | babel-loader 8.x | babel 7.x` and I can't do `import ReactMapGL from 'react-map-gl'`. (`webpack 4 | babel-loader 7.x | babel 7.x` works just fine)
It gave the error below:
<img width="917" alt="screen shot 2018-03-07 at 5 25 53 am" src="https://user-images.githubusercontent.com/3991678/37094669-6c61680a-21c8-11e8-90ff-2540a499b082.png">

Has anyone met the same error?
```
// My webpack config
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');

module.exports = {
  mode: 'development',
  entry: {
    app: [
      'webpack-hot-middleware/client',
      './src/index.js',
    ]
  },
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist'),
    publicPath: '/'
  },
  devtool: 'inline-source-map',
  plugins: [
    new HtmlWebpackPlugin({
      template: 'template/index.html',
    }),
    new webpack.NamedModulesPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
  ],
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /\/node_modules$/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              '@babel/preset-env',
              '@babel/preset-react',
              '@babel/preset-stage-2'
            ]
          }
        }
      },
      {
        test: /\.css$/,
        use: [
          'style-loader',
          'css-loader'
        ]
      },
      {
        test: /\.(png|svg|jpg|gif)$/,
        use: [
          'file-loader'
        ]
      }
    ]
  }
};
```

Thanks,

**Comment by Pessimistress** [comment]
@ibgreen

**Comment by ibgreen** [comment]
babel-loader 8 is still in beta. Not all existing webpack loaders are compatible with it. Suggest you comment out your loaders one by one to see which one is breaking.

Also, I opened a PR that upgrades react-map-gl main example to babel-loader 8, so hopefully that can be a working baseline.

**Comment by luoquan1982** [comment]
npm i babel-loader@7 -D

**Comment by ElkinCp5** [comment]
![image](https://user-images.githubusercontent.com/26524274/72912861-4122fa00-3d0a-11ea-899b-502a740b2555.png)

"devDependencies": {
    "@babel/cli": "^7.7.5",
    "@babel/core": "^7.7.5",
    "@babel/node": "^7.7.7",
    "@babel/plugin-proposal-class-properties": "^7.7.4",
    "@babel/preset-env": "^7.7.6",
    "@babel/preset-react": "^7.7.4",
    "babel-loader": "^8.0.6",
    "cors": "^2.8.5",
    "css-loader": "^3.2.0",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "^0.8.2",
    "node-sass": "^4.13.0",
    "nodemon": "^1.19.4",
    "open": "^7.0.0",
    "postcss-loader": "^3.0.0",
    "sass-loader": "^8.0.0",
    "style-loader": "^1.0.0",
    "url-loader": "^3.0.0",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.10",
    "webpack-dev-middleware": "^3.7.2",
    "webpack-dev-server": "^3.9.0",
    "webpack-livereload-plugin": "^2.2.0"
  }

**Comment by afif-malghani** [comment]
> **my solution was this**
> 
> ![image](https://user-images.githubusercontent.com/26524274/72912978-7596b600-3d0a-11ea-85cd-50177146dcdf.png)
> 
> ![image](https://user-images.githubusercontent.com/26524274/72913018-87785900-3d0a-11ea-8aec-56bfd8710496.png)

Where do I put the rules? I am new to web dev.
