### ISSUE TITLE
RTLTextPlugin

### ISSUE THREAD

**Issue by jc211** [uber/react-map-gl#498]
How do I support Right to Left languages with this component? Is there a way to get a handle to mapboxgl and call setRTLTextPlugin?

**Comment by jc211** [comment]
This solution has worked for me. 
You can just require the mapbox library again and call the method as below:
```
import MapGL, { Marker, Popup } from 'react-map-gl';
const mapboxgl =  require('mapbox-gl') ;
mapboxgl.setRTLTextPlugin('https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.1.2/mapbox-gl-rtl-text.js');
```

**Comment by aboganas** [comment]
I have tried this, but unfortunately didn't work for me
