### ISSUE TITLE
Cannot read property 'send' of undefined   when zooming in or out

### ISSUE THREAD

**Issue by 7091lapS** [uber/react-map-gl#499]
Hello, I've been getting this error when zooming in and out while using a custom style object (even with the examples style objects provided). The map still works although it's very laggy within transitions.

The error does not occur if I use one of the preset styles (eg: "mapbox://styles/mapbox/dark-v9" ) and the transitions are smooth as they should be.

I can't seem to be able to figure out what's causing it.
```
mapbox-gl.js:517 Uncaught TypeError: Cannot read property 'send' of undefined
    at Dispatcher.send (mapbox-gl.js:517)
    at t.loadTile (mapbox-gl.js:231)
    at t._loadTile (mapbox-gl.js:223)
    at t._addTile (mapbox-gl.js:223)
    at t._updateRetainedTiles (mapbox-gl.js:223)
    at t.update (mapbox-gl.js:223)
    at t.<anonymous> (mapbox-gl.js:223)
    at t.Evented.fire (mapbox-gl.js:521)
    at t.Evented.fire (mapbox-gl.js:521)
    at mapbox-gl.js:231
    at u (mapbox-gl.js:207)
    at XMLHttpRequest.r.onload (mapbox-gl.js:503)
```

**Comment by Pessimistress** [comment]
This is an error from within mapbox-gl.
Do you see any react-map-gl errors before this?

**Comment by 7091lapS** [comment]
I sometimes get the warning
```
mapbox-gl.js:551 Unable to perform style diff: Style is not done loading.  Rebuilding the style from scratch.
```
but I'm not sure if they are related.
The typeError only seems to occur when I zoom in/out quickly (by mouse wheel or trackpad).

**Comment by Pessimistress** [comment]
This is again an error orinated in mapbox. Without more information I can't tell if it's related to react-map-gl.

**Comment by 7091lapS** [comment]
I think this error was due to mapbox performance errors and to the map reloading the styles at every render. I moved parts of my code outside the render function and now it seems to be resolved.
