### ISSUE TITLE
Map not resizing when supplied with new width/height props

### ISSUE THREAD

**Issue by ralphstodomingo** [uber/react-map-gl#504]
Have been trying to make a full-width and height map, and am using `react-virtualized`'s `AutoSizer`.
Consider the following:
```
<AutoSizer>
  {({ height, width }) => (
    <ReactMapGL
      width={width}
      height={height}
      {...this.state.viewport} // from example
      onViewportChange={viewport => {
        this.setState({ viewport });
      }}
    />
  )}
</AutoSizer>
```
I can confirm the AutoSizer's parent has 100% viewport height and width, and AutoSizer reports the  height updating once I resize the browser:
![image](https://user-images.githubusercontent.com/15341353/38914967-745c57d2-4314-11e8-8cb5-83d89ae83641.png)
But upon checking with React DevTools, the map height prop doesn't change: 
![image](https://user-images.githubusercontent.com/15341353/38915028-af838c36-4314-11e8-95a6-0a23709f3c0e.png)

Also, I can see that while the map hasn't loaded yet, the size updates, since AutoSizer starts at 0 width and 0 height:
![image](https://user-images.githubusercontent.com/15341353/38915082-fd8c52dc-4314-11e8-95cc-d8096d4e9a27.png)
But once the map loads, the map does not resize.
Any ideas as to what's wrong with this setup?

**Comment by Pessimistress** [comment]
`{...this.state.viewport}` overwrites the props with the previous width and height. You need to reorder your props so that the new width and height are applied after this.

**Comment by ralphstodomingo** [comment]
@Pessimistress thanks for responding.
I did. My `this.state.viewport` only has this:
```
state = {
  viewport: {
    latitude: 14.6379145,
    longitude: 121.0286935,
    zoom: 16.5,
  },
};
```

**Comment by Pessimistress** [comment]
The `onViewportChange` callback returns all props including width and height. You can see this by inspecting your viewport state at runtime.

**Comment by ralphstodomingo** [comment]
Closing this as it is no longer an issue, strangely. Perhaps I made a mistake somewhere, as in a fresh installation this works perfectly.

**Comment by marek-sed** [comment]
@Pessimistress ran into same issue, 
I understand that onResize was added later, so it would make more sense to width and height
be returned by onResize and everything else onViewportChange. 

Or if width and height is initialized with non numeric value it should keep using the initial one.
