### ISSUE TITLE
Can't export png

### ISSUE THREAD

**Issue by 7091lapS** [uber/react-map-gl#509]
I'm trying to save a png file using the base64 url that I get from ```getMap().getCanvas().toDataURL()```

When I save the url to png it always results in a blank png.
I have ```preserveDrawingBuffer=true ``` and have tried using both static and interactive map.

This is how I'm doing it:

```
componentDidMount() {
   this.setState({ pngUrl: this.mapRef.getMap().getCanvas().toDataURL() })
}

render(){
return(

<StaticMap
          {...mapboxConfig.viewport}
          mapboxApiAccessToken={accessToken}
          preserveDrawingBuffer={true}
          ref={map => this.mapRef = map}
          mapStyle={mapStyle}
        />
<a href={this.state.pngUrl} id="download" download="canvasexport.png">Export png</a>
)}
```
The map object returned by this.mapRef.getMap() has ```preserveDrawingBuffer: true``` so that shouldn't be the problem.

Am I doing something wrong?

**Comment by Evanfeenstra** [comment]
if you delay the getDataURL() with a setTimeout this should work. It takes a second to get the map tiles and render the canvas
