### ISSUE TITLE
MapGL doesn't support default vector tiles

### ISSUE THREAD

**Issue by yuvadm** [uber/react-map-gl#51]
Running the full example code in https://uber.github.io/react-map-gl/#/interactivity works fine as is, but doesn't show anything on the map when using:

``` js
mapStyle: 'mapbox://styles/mapbox/light-v8'
```

`mapboxApiAccessToken` is properly added, and network requests show the at least some of the data jsons actually loading, but nothing is being displayed. Does MapGL not support vector tile sets?

**Comment by lafin** [comment]
I did a small demo https://github.com/lafin/talks-on-map/tree/dev (dev branch)

**Comment by yuvadm** [comment]
@lafin thanks will take a look!

**Comment by Apercu** [comment]
Hey @yuvadm are you sure that's still the case? Works fine with me.

**Comment by yuvadm** [comment]
@Apercu haven't tested in a while, this is probably a stale issue.

**Comment by Apercu** [comment]
Thanks ;)
