### ISSUE TITLE
How to control overlapping markers?

### ISSUE THREAD

**Issue by alcferreira** [uber/react-map-gl#516]
Hi! 

I have some markers that are overlapping and I wish to set the `zIndex` to the one that should appear in top of the others.
How can I achieve that?

I know that the last marker child overlaps all others, but i should be able to set a `zIndex` to a marker or something like that.

**Comment by alcferreira** [comment]
Yeah, I just realised I can use `className` to achieve that.

**Comment by stevenschmatz** [comment]
Hey @alcferreira , what did you do to solve this problem?

Would be useful if you shared, since this is the first Google result under "react-map-gl z-index".

**Comment by huzaifa-ahmed** [comment]
I have many markers that have same location, and markers are overlapping each other, how can i solve this issue to show all of them?

**Comment by alcferreira** [comment]
Hey folks, sorry for the delay. 
Here's what I did back then:

```js 
<Marker
  latitude={producer.lat}
  longitude={producer.lon}
  key={producer.id}
  className={index === currentProducer ? 'active' : ''}
>
  {...}
</Marker>
```

Then set z-index to 1 in your css
```css
.active-pin {
  z-index: 1;
}
```

**Comment by huzaifa-ahmed** [comment]
> Hey folks, sorry for the delay.
> Here's what I did back then:
> 
> ```js
> <Marker
>   latitude={producer.lat}
>   longitude={producer.lon}
>   key={producer.id}
>   className={index === currentProducer ? 'active' : ''}
> >
>   {...}
> </Marker>
> ```
> 
> Then set z-index to 1 in your css
> 
> ```css
> .active-pin {
>   z-index: 1;
> }
> ```

It is not making any difference see picture below

![image](https://user-images.githubusercontent.com/60890108/82578112-6551f300-9ba5-11ea-9b06-5e7a4c3e648e.png)

As you can see overlapping markers, I had give hard-coded margin-left to single marker to see other markers on back, Please help.
