### ISSUE TITLE
What is the difference between `reuseMap` and `reuseMaps`?

### ISSUE THREAD

**Issue by kristiehowboutdat** [uber/react-map-gl#523]
I noticed that there are both `reuseMap` and `reuseMaps` props, but `reuseMap` is undocumented. I'm following along with the conversation for reducing the number of GL contexts created since that's an issue for my application, so I want to make sure I'm doing the most I can.

What is the difference between the two props? cc @ibgreen since you're the PR author

Thank you!

**Comment by ibgreen** [comment]
It is the same thing. It was initially called `reuseMaps`, but since I started using the prop, it felt more natural to call it `reuseMap`. So I added support for both, with an idea of deprecating `reuseMaps`. But for now they both are supported.
