### ISSUE TITLE
NavigationControl - 'bearing' of undefined

### ISSUE THREAD

**Issue by mhjey** [uber/react-map-gl#527]
There seems to be some sort of bug with the bearing

This is my Component 

`class Poster extends Component {
	state = {
		viewport: {
			width: 400,
			height: 400,
			latitude: 37.7577,
			longitude: -122.4376,
			zoom: 8,
			bearing: 0
		}
	}
	render() {
		return (
			<div>
				<ReactMapGL
					mapboxApiAccessToken={TOKEN}
					{...this.state.viewport}
					onViewportChange={viewport => this.setState({ viewport })}
				/>
				<div style={{ position: "absolute", right: 0 }}>
					<NavigationControl onViewportChange={viewport => console.log(viewport)}/>
				</div>
			</div>
		)
	}
}`

and I get following BUG:

`TypeError: Cannot read property 'bearing' of undefined
    at NavigationControl._renderCompass (../node_modules/react-map-gl/dist/components/navigation-control.js:141:43)
    at NavigationControl.render (../node_modules/react-map-gl/dist/components/navigation-control.js:172:239)
    at processChild (/../node_modules/react-dom/cjs/react-dom-server.node.development.js:2207:18)`

**Comment by mhjey** [comment]
Sorry my bad. Everything is fine.

**Comment by HeiYanjing** [comment]
could you show your code?
what happened?
how you resolve it?

**Comment by HeiYanjing** [comment]
aha
