### ISSUE TITLE
Cannot control interactivity of overlays

### ISSUE THREAD

**Issue by alpha-beta-soup** [uber/react-map-gl#535]
I want to have control over the cursor on the map. Specifically, I want some of my custom GeoJSON-source layers to change the cursor to a pointer, and otherwise for the cursor to be grab/grabbing. The [Mapbox style spec _used_ to allow you to specify an `interactive` prop](https://github.com/mapbox/mapbox-gl-style-spec/issues/418) that would allow me to achieve this effect, but that [is no longer the case](https://github.com/mapbox/mapbox-gl-js/issues/1479). What I see is that whenever I mouse over a feature from _any_ layer that isn't the background, the cursor changes to a pointer. This is misleading, because the vast majority of features that cause this cursor style change aren't really interactive (by design, nothing will happen if you click on them — although of course I would be free to make something happen if that made sense for my application). I have a click handler that first filters the intersecting features for layers that start with a custom prefix (e.g. `foo://`; so as to not conflict with any layers defined in the Mapbox-hosted base style). However the mouse cursor doesn't really support this interaction, because _every layer_ appears clickable due to the `pointer` style.

So is there some way to control the cursor style at the level of individual layers?

**Comment by Pessimistress** [comment]
@alpha-beta-soup Try set the `getCursor` prop: https://uber.github.io/react-map-gl/#/Documentation/api-reference/interactive-map

Relevant issue: https://github.com/uber/react-map-gl/issues/558

**Comment by alpha-beta-soup** [comment]
Thanks, that works perfectly.

**Comment by gala-m** [comment]
@Pessimistress That link leads to a 404 now. 

I'm also trying to get a specific layer to have a pointer instead of grab cursor. `getCursor` works in `<ReactMapGL>`, but that makes the whole map window have that same cursor. 

Is there anyaway to have `getCursor` in `<Layer>` in a situation like this:

```
<Source
    id="points" 
    type="geojson" 
    data={allData} 
    >
    <Layer {...layerStyle} />
</Source> 
```

thank you
