### ISSUE TITLE
Attach popups to markers

### ISSUE THREAD

**Issue by Majaspic** [uber/react-map-gl#538]
Hi,

https://www.mapbox.com/help/custom-markers-gl-js/#attach-popups-to-markers

How is this possible with react map gl ? I can't find such an example for React, only for Vanilla JS on Mapbox documentation

**Comment by hnq90** [comment]
@Majaspic There's an example for attaching popups to markers here: https://uber.github.io/react-map-gl/#/Examples/markers-popups

**Comment by saadsaifse** [comment]
Example seems to be shifted here https://uber.github.io/react-map-gl/examples/controls

**Comment by unnatii** [comment]
@saadsaifse this link is not working as well .

**Comment by saadsaifse** [comment]
@unnatii try http://visgl.github.io/react-map-gl/examples/controls
they seem to be quite inconsistent with their URLs.

**Comment by juliettebeaudet** [comment]
Late to the party but I really like this tutorial https://mariestarck.com/how-to-display-popups-on-a-mapbox-map-mapbox-react-tutorial-part-3/ !
