### ISSUE TITLE
HTMLOverlay with captureClick doesn't actually capture click

### ISSUE THREAD

**Issue by cjevning** [uber/react-map-gl#539]
I've created a quick reproduction of the issue here (insert token where indicated):
https://codesandbox.io/s/ww1j2ymv5w

The overlay onClick is never fired upon a click of the map/overlay, but the map onClick always is. This also seems to affect SVGOverlay:
https://codesandbox.io/s/vjpnry3p87

**Comment by nara007** [comment]
I have the same question.

**Comment by Pessimistress** [comment]
Fix published in 3.3.4
