### ISSUE TITLE
Zoom does not match between viewport and tiles

### ISSUE THREAD

**Issue by carlostxm** [uber/react-map-gl#541]
Hi,

I need to get the zoom level of the tiles currently shown but there is a shift between the tile's zoom and the zoom in the viewport.

Please check this [jsfiddle](https://jsfiddle.net/carlostxm/becy9p28/3/), you can see that the zooms do not match.

I assume that this is the component's behaviour but I would like to know how can I get this info.

The main reason to do that is to load data by tiles in a deckGL layer, so I need the XYZ values to request the info.

Any help is appreciated.

Thanks,

Carlos.

**Comment by Pessimistress** [comment]
What do you mean shift? Zoom is always rounded to the nearest z level (integer).
You can refer to [this page](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Coordinates_to_tile_numbers_2) regarding tile number calculation.

**Comment by Pessimistress** [comment]
What do you mean shift? Zoom is always rounded to the nearest z level (integer).
You can refer to [this page](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Coordinates_to_tile_numbers_2) regarding tile number calculation.

**Comment by carlostxm** [comment]
Sorry, I meant that the zoom level in the viewport does not match with the tile zoom level.

In the JSFiddle attached, the tooltip shows the viewport's zoom level (or in this case the zoom level returned by the method getZoom) and in the map the zoom level of every tile. I.e. Initially the zoom level in the map viewport is 4 (integer) the tiles requested has zoom level 5.
