### ISSUE TITLE
Markers don't update when rendered "passthrough" style.

### ISSUE THREAD

**Issue by RDGthree** [uber/react-map-gl#544]
In our app structure, we use a "passthrough" structure fairly often. Roughly meaning that we often render children in individual components via `props.children`, and then layout the actual structure in more full featured view (let's call it `Main`).

```
<App>
  <FooView>
    <FooView.Bar />
    <hr />
    <FooView.Bar />
  </FooView>
  <MapView
    latitude={LATITUDE_VALUE},
    longitude={LONGITUDE_VALUE}
    zoom={ZOOM_VALUE}>
      <MapView.MapViewMarker
        latitude={listing.latitude}
        longitude={listing.longitude}
      />
  </MapView>
</App>
```

So our state and state updates for `MapView` are within the `MapView` component but not the `Main` component, and that means markers aren't being re-rendered even though they're children: https://github.com/facebook/react/issues/4067

It seems like the markers should be updating explicitly on map movement, not implicitly like this -- I can't really see a scenario where you _wouldn't_ want the marker to stay in it's correct geographic position.

Thoughts?

**Comment by Pessimistress** [comment]
@RDGthree 
- It's not clear to me what <MapView> and <MapViewMarker> components are in your example. Can you elaborate?
- Right now react-map-gl uses React's [legacy context API](https://reactjs.org/docs/context.html#legacy-api) which does not trigger an update if the child is a `PureComponent`. Given the direction React is taking, I'm planning to change this implementation in the next major release. This may or may not be related to your issue. Regardless, I would like to understand your use case better.

**Comment by joaquinbeltran** [comment]
Hello, I'm creating markers similar to this project react-map-gl/examples/controls/src/app.js and I'm allowing users to add a new marker, so I'm passing in updated data to the markers data source but I'm wondering if there's anything else I need to do for the new markers to update on the map?
