### ISSUE TITLE
Mapbox token error wrongly displayed when any tile returns a 401

### ISSUE THREAD

**Issue by nerik** [uber/react-map-gl#550]
Hello,

https://github.com/uber/react-map-gl/blob/master/src/components/static-map.js#L205
react-map-gl sees tiles requests returning 401s and that no Mapbox token is set, and wrongly infers that the client is failing to load tiles from Mapbox. In our case, the tiles do fail to load, but they are not hosted on Mapbox servers at all (and we aren't using any layers/fonts etc from Mapbox).

What can we consider a stable enough way to tackle this? Would applying a regex to `evt.error.url` work ?

**Comment by Pessimistress** [comment]
This feature was originally designed for a first-time developer to understand the issue when their map fails to load. I would like to avoid hard-coding url patterns in case Mapbox makes changes to their service.

Does it make sense if I add a prop (something like `disableTokenWarning`) for your use case?

**Comment by nerik** [comment]
Thanks for the reply, and I definitely understand the motivation behind that feature.
`disableTokenWarning` sounds perfect.

**Comment by Pessimistress** [comment]
Fix published in 3.3.4
