### ISSUE TITLE
Add scale to map

### ISSUE THREAD

**Issue by aakim26** [uber/react-map-gl#551]
Is there any way to add a scale to the map? The equivalent of a scaleControl in MapboxGL:
https://www.mapbox.com/mapbox-gl-js/api/#scalecontrol

Thanks!

**Comment by Pessimistress** [comment]
You can get access to the `mapboxgl.Map` instance via the [getMap](https://uber.github.io/react-map-gl/#/Documentation/api-reference/static-map?section=methods) method then follow the above example.

**Comment by aakim26** [comment]
Ah, makes sense, thanks!
