### ISSUE TITLE
reuseMap doesn't prevent destroy and remount map

### ISSUE THREAD

**Issue by dt-rush** [uber/react-map-gl#555]
The reuse-map example destroys the map each time you click "toggle". The component is unmounted and on remount triggers all new requests for map data.

**Comment by ibgreen** [comment]
@dt-rush Thanks for reporting. Apologies in advance for giving a basic reply, but just to set expectations: 

* The `reuseMap` feature is intended to work "as if"  a new map was created.
* The purpose is make sure we don't run out of resources such as WebGL contexts etc by creating and destroying many maps. 
* It is not intended to bring back the map with its previous settings, so reloading map data does not in itself seem like a problem, although I am not quite sure why it would have to do it. Maybe this relates to the way that we set and "diff" map styles?

The feature should should just detach the map canvas from the DOM tree to protect it (and its webgl context) from being destroyed, and then reattach them later.

Do these comments make sense? If not maybe you could provide a more detailed pointer to what we should be looking at? Or maybe we should improve the docs to set the right expectations?

**Comment by dt-rush** [comment]
@ibgreen thanks for the quick reply! So it turns out my problem is in another direction, and it could be beneficial to clarify in the Readme for the example or in the documentation for the `reuseMap` param. 

I have a map on a router with `react-router`, which unmounts and remounts components when changing routes. Re-mounting a `ReactMapGL` object each time the `/#/map` route is navigated-to is causing new network requests to the mapbox API every time a new `ReactMapGL` object is constructed and mounted. I found `reuseMap` in searching for a solution. I feel like this must be a common-enough use-case to have been solved before. While I've got your attention, you seem to be knowledgeable about this repo - does this problem ring a bell?

**Comment by dt-rush** [comment]
Posting for the future benefit of anyone in a similar situation, since I ran into some pretty specific solutions that don't seem documented anywhere.

I had to switch from using `react-router`'s `Route` component, wrapping my Map view, since it can *only* function by unmounting the views which are not matched - and unmounting/remounting the `ReactMapGL` component inevitably results in it re-requesting the map data from the mapbox API, leading to unnecessary latency and network traffic.

Instead: I wrapped my App's content area with the HOC `withRouter`, so that it could subscribe to route changes, and I just added a conditional styling on the various views according to whether their route was matched. This prevents them from getting unmounted:

```
import React, { Component } from 'react';

// Content is aware of routing and displays a different view depending
import {
  withRouter,
} from "react-router-dom";

// import views
import MapView from "./MapView";
import CardsView from "./CardsView";
  
// this component will be exported at the bottom of this file wrapped with 
// the react-router-dom package's withRouter higher-order-component, so 
// that it can get access to the location property and set styling on 
// views directly
export class AppContent extends Component {
  constructor(props) {
    super(props)
    // state.location gets updated on route changes by history listener
    // attached below
    this.state = {
      // route to the hash on page load
      location: window.location.hash.substr(1)
    };
  }
  // on mount, attach a history listener callback to update the state's
  // `location` variable
  componentDidMount() {
    this.unlistenHistory = this.props.history.listen((location, action) => {
      this.setState(_ => ({ location: location.pathname }));
    });
  }
  // on unmount, detach the history listener
  componentWillUnmount() {
    this.unlistenHistory();
  }
  render() {
    // styles are hidden / shown depending on location
    const { location } = this.state;
    return (
      <div className="AppContent">
        {/* this particular pattern is needed so that we can properly hide
          the map -- preventing it from being remounted and having to call
          the mapbox API again, while is still retains knowledge of its
          size and can resize properly while hidden as well.

          https://stackoverflow.com/a/35487429/9715599*/}
        <div className="AppContent-view"
          style={{
              position: 'fixed',
              opacity: location === '/' ? '1.0' : '0.0',
              zIndex: location === '/' ? '1' : '-1',
        }}>
          <MapView />
        </div>
        <div className="AppContent-view"
          style={{display: location === '/cards' ? 'block' : 'none'}}>
          <CardsView />
        </div>
      </div>
    );
  }
}

export default withRouter(AppContent);
```

The `MapView` component has to be styled a bit differently from a normal view like `CardsView`, which you can just set to `display: none`, since if the `ReactMapGL` component goes `display: none`, the interior `canvas` element will get sized incorrectly on returning to `display: block` (this ultimately is an issue with `mapbox-gl-js`, not `react-map-gl`, which inherits this issue just by virtue of being a wrapper). 

So, instead, we hide the map view by modifying it's `zIndex` and `opacity` to put it behind everything else and hidden, but it doesn't lose a sense of it's size. If you have a resize listener on it, it will resize properly in between being hidden and displayed.

An example of this can be seen in the `modules/dashboard/client/src` folder of my repo [`drone-network-sim`](https://github.com/dt-rush/drone-network-sim). Run it with `npm run dev` (requires `mongod` to be running on `localhost:27017`) to see it in action.
