### ISSUE TITLE
QueryRenderedFeatures "help wanted" 

### ISSUE THREAD

**Issue by sheub** [uber/react-map-gl#558]
Hi, I am struggling to get access to the rendered features from a map which I have customized and is hosted at Mapbox.
I have search for the mapboxgl.js function `queryRenderedFeatures ` and found this in interactive-map.js:

´´´javascript
 /**
    * Called when the map is hovered over.
    * @callback
    * @param {Object} event - The mouse event.
    * @param {[Number, Number]} event.lngLat - The coordinates of the pointer
    * @param {Array} event.features - The features under the pointer, using Mapbox's
    * queryRenderedFeatures API:
    * https://www.mapbox.com/mapbox-gl-js/api/#Map#queryRenderedFeatures
    * To make a layer interactive, set the `interactive` property in the
    * layer style to `true`. See Mapbox's style spec
    * https://www.mapbox.com/mapbox-gl-style-spec/#layer-interactive
    */
  onHover: PropTypes.func,
´´´´

However, 

- the `event.features` Array remains always empty when I perform a hover on the map

- It seems the `interactive` property in the Mapbox's style spec, has been removed from the spec in [this ](https://github.com/mapbox/mapbox-gl-js/commit/7801a517b196c33288cc9f6a311cc06478ca77c6) commit and is now deprecated .

**Comment by Pessimistress** [comment]
Fix published in 3.3.3
