### ISSUE TITLE
Use `pointerEvents: none` for the overlay container

### ISSUE THREAD

**Issue by vicapow** [uber/react-map-gl#56]

**Comment by vicapow** [comment]
I believe so. This Is about ensuring the built in overlays and examples set pointer events to none to prevent user interactions with the overlays themselves

**Comment by ralphstodomingo** [comment]
Integrating `MapboxDraw`, I ran into the issue of the overlay container blocking the mouse events. Setting the container's `pointer-events` to `none` solved it for me.
