### ISSUE TITLE
v4.0 Goals

### ISSUE THREAD

**Issue by Pessimistress** [uber/react-map-gl#561]
### Core Components
- [x] Remove Immutable from dependency
- [x] Remove implementation of style diffing: use Mapbox's own style diffing feature
- [x] Update or remove the usage of the legacy React context API
- [x] Support relative `width` and `height` props

### Interaction
- [x] Offer flags for pan/zoom/rotate in callbacks
- [x] Offer APIs to access more pointer events

### Build System
- [x] Upgrade babel to v7
- [x] Remove manual binding of class methods

### Other
- [ ] Improve testing

**Comment by TrySound** [comment]
I would start using babel-runtime. Currently helpers are duplicated in every module.

**Comment by tstirrat15** [comment]
@Pessimistress is there any busywork-type work that I can do to help move towards this release?

**Comment by sos0** [comment]
Relative 👏 width 👏 and 👏  height 👏 🎉 🎈

**Comment by Pessimistress** [comment]
4.0.0-beta.1 is published

**Comment by archansel** [comment]
Hi, Does v4 support react below v16? I tried using v4.0.0-beta.3 and got `_react.createContext` error. My react version is `15.6.1`

**Comment by tstirrat15** [comment]
@archansel No. One of the goals of v4 is to move towards the new React context API (released in v16.3), which is incompatible with the old API.

**Comment by Pessimistress** [comment]
4.0.0 is published!

**Comment by TrySound** [comment]
@Pessimistress Where is tag and changelog?

**Comment by Pessimistress** [comment]
@archansel Some of the v15 API that v3 was using will be removed in the next major release of React. Although unfortunate, when we have to choose, we'd like the latest react-map-gl to support 17 rather than 15.

**Comment by Pessimistress** [comment]
@TrySound 4.0-release branch
