### ISSUE TITLE
drag capture doesn't work

### ISSUE THREAD

**Issue by cyrilchapon** [uber/react-map-gl#562]
With a dead simple map, when trying `<HTMLOverlay captureDrag />` or even a custom implementation like `<DraggablePointOverlay>`; the approach of `event.stopPropagation()` doesn't seem to work : the map still pans.

Is that wanted ?

**Comment by cyrilchapon** [comment]
Probably related to https://github.com/uber/react-map-gl/issues/539

**Comment by cyrilchapon** [comment]
Confirmed with *examples/additional-overlays* example from Master

**Comment by Pessimistress** [comment]
Fix published in 3.3.4

**Comment by vkammerer** [comment]
This is now causing the mapbox original layer behind `<div class="overlays">` to be unable to receive clicks...
Is there a way to pass a click to the mapbox original layer?

**Comment by cyrilchapon** [comment]
@vkammerer I can't reproduce.

Do you mean clicking on blank parts of the overlay ?

**Comment by Alexandrescu** [comment]
I have the same issue @vkammerer has. Imagine you have any custom overlay in the `<InteractiveMap>` (like a canvas), when the `pointer-events: none` was removed all the clicks which used to be passed-through to this layer are now being intercepted by `<div class="overlays">`.
