### ISSUE TITLE
Pan map when drag starts on a marker?

### ISSUE THREAD

**Issue by realyze** [uber/react-map-gl#580]
Is there any way I could allow the map to be moved when a drag starts on a marker? I have a cordova mobile app that renders quite a few markers, say 20, on screen. Now, when user wants to move the map and they place their finger on a marker—which is quite probable given the marker density—and start dragging, nothing will happen (which makes the app look broken).

Thanks for all your hard work on this awesome library! 🙌

**Comment by Pessimistress** [comment]
Set `captureDrag` prop to `false` on your `<Marker>`. [documentation](https://uber.github.io/react-map-gl/#/Documentation/api-reference/marker)

**Comment by realyze** [comment]
As my friend would say: extremely excellent. :) Thanks so much, @Pessimistress, should have RTFM'd! Closing this now.
