### ISSUE TITLE
Text Layer onHover/ onClick not fired between letters

### ISSUE THREAD

**Issue by daumann** [uber/react-map-gl#582]
I don't think that this is wanted behavior - if you try to hover over a label of a **TextLayer** it only fires if it is over a fill of such label, so for example if you move your mouse cursor in the middle of an O or click between the letters, nothing happens.

Is there a workaround? For example have huge invisible outlines? The optimal solution would be if a hover event is fired while on the boundaries (rectangle) of the label (like Google Maps does with city names).

You can reproduce this issue by going to the [TextLayer example](http://deck.gl/#/documentation/deckgl-api-reference/layers/text-layer), put the size scale to 6 or higher and try to hover over the label. 

A somewhat related issue is that the autoHighlight should highlight not only the hovered letter, but the entire label.

**Comment by Pessimistress** [comment]
Can you post this in the deck.gl repo instead?
