### ISSUE TITLE
react-map-gl/examples/draggable-markers/ - draggable not woking 

### ISSUE THREAD

**Issue by gauravverma029** [uber/react-map-gl#583]
![download 1](https://user-images.githubusercontent.com/4488516/44455509-8c5d4880-a5fe-11e8-8058-7c936bfae611.png)

{
  "scripts": {
    "start": "webpack-dev-server --progress --hot --open",
    "start-local": "webpack-dev-server --env.local --progress --hot --open"
  },
  "dependencies": {
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-map-gl": "^3.2.0"
  },
  "devDependencies": {
    "babel-core": "^6.21.0",
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-2": "^6.18.0",
    "webpack": "^2.4.0",
    "webpack-dev-server": "^2.4.0"
  }
}

**Comment by Pessimistress** [comment]
The master branch is the dev branch. Please use the 3.3-release branch examples instead.

If you want to try unpublished features, you need to run `npm run start-local` in this example's directory.
