### ISSUE TITLE
React-map-gl about mapbox accessToken

### ISSUE THREAD

**Issue by HeiYanjing** [uber/react-map-gl#586]
firstly, soryy about my English....
I want to add a NavigationControl In a  webPage,. Imitates the demo in "/examples/website/trips".
I made all resource native, a native vector tiles  in  opemmaptiles-server docker .
`    <div>
        <ReactMapGL  {...viewport} onViewportChange={updateViewport}>
        <div style={{position: 'absolute',top:10, right: 10}}>
            <NavigationControl onViewportChange={updateViewport} />
        </div>
        </ReactMapGL>
      <DeckGL
        layers={this._renderLayers()}
        initialViewState={INITIAL_VIEW_STATE}
        viewState={viewState}
        controller={controller}
      >
        {baseMap && (
          <StaticMap
            reuseMaps
            mapStyle="style.json"
            state ={true}
          />
        )}
      </DeckGL>
    </div>`
this style.json make fonts,source url,glyphs link to local server。
the page could show the map ,but  there is something wrong.

![lup89jx6pd3 r_ llcw](https://user-images.githubusercontent.com/42837853/44851851-363e7400-ac94-11e8-9592-28a06a01a75f.png)

If my question is immature, please forgive me.

**Comment by GunnarSturla** [comment]
Do you have a MapBox token set up?  If you haven't, check out the [About Mapbox Tokens](https://uber.github.io/react-map-gl/#/Documentation/getting-started/about-mapbox-tokens) in the Getting started section of the docs to see how.

Also, if you use three backticks (\`\`\`), you will render a block of code, like this (making it much easier to read):
```<div>
  <ReactMapGL {...viewport} onViewportChange={updateViewport}>
    <div style={{ position: 'absolute', top: 10, right: 10 }}>
      <NavigationControl onViewportChange={updateViewport} />
    </div>
  </ReactMapGL>
  <DeckGL
    layers={this._renderLayers()}
    initialViewState={INITIAL_VIEW_STATE}
    viewState={viewState}
    controller={controller}
  >
    {baseMap && <StaticMap reuseMaps mapStyle="style.json" state={true} />}
  </DeckGL>
</div>
```

**Comment by HeiYanjing** [comment]
> Do you have a MapBox token set up? If you haven't, check out the [About Mapbox Tokens](https://uber.github.io/react-map-gl/#/Documentation/getting-started/about-mapbox-tokens) in the Getting started section of the docs to see how.
> 
> Also, if you use three backticks (```), you will render a block of code, like this (making it much easier to read):
> 
> ```
>   <ReactMapGL {...viewport} onViewportChange={updateViewport}>
>     <div style={{ position: 'absolute', top: 10, right: 10 }}>
>       <NavigationControl onViewportChange={updateViewport} />
>     </div>
>   </ReactMapGL>
>   <DeckGL
>     layers={this._renderLayers()}
>     initialViewState={INITIAL_VIEW_STATE}
>     viewState={viewState}
>     controller={controller}
>   >
>     {baseMap && <StaticMap reuseMaps mapStyle="style.json" state={true} />}
>   </DeckGL>
> </div>
> ```

Thank you very much

**Comment by HeiYanjing** [comment]
> Do you have a MapBox token set up? If you haven't, check out the [About Mapbox Tokens](https://uber.github.io/react-map-gl/#/Documentation/getting-started/about-mapbox-tokens) in the Getting started section of the docs to see how.
> 
> Also, if you use three backticks (```), you will render a block of code, like this (making it much easier to read):
> 
> ```
>   <ReactMapGL {...viewport} onViewportChange={updateViewport}>
>     <div style={{ position: 'absolute', top: 10, right: 10 }}>
>       <NavigationControl onViewportChange={updateViewport} />
>     </div>
>   </ReactMapGL>
>   <DeckGL
>     layers={this._renderLayers()}
>     initialViewState={INITIAL_VIEW_STATE}
>     viewState={viewState}
>     controller={controller}
>   >
>     {baseMap && <StaticMap reuseMaps mapStyle="style.json" state={true} />}
>   </DeckGL>
> </div>
> ```

for mapbox ,I have no mapbox token ,because I'm no in the USA.my map resource is native by openmaptiles docker. in my style.json,url sprite glyphs point to local address. without reactmapgl ,it's OK,but if I want to use ReactMapGl to  add a navigationcontrol ,this error would be shown  ，note " A valid API access token is required to use Mapbox data". 
so In constructor it will be check access token ?

**Comment by GunnarSturla** [comment]
It looks like you're including the map twice (once with `ReactMapGL` and the second time with `StaticMap`), and you're not including the reference to your mapStyle in your first map, which will cause the error to show.

Although I haven't used Deck.gl with `NavigationControl`, it looks like it works the same as with `ReactMapGL`. You need to listen to updates to the viewport/viewState via `onViewStateChange`, store the new viewState in your state and pass it back to `DeckGL`. Something like this:
```
<div>
  <DeckGL
    layers={this._renderLayers()}
    viewState={viewState}
    controller={controller}
    onViewStateChange={updateViewport}
  >
    {baseMap && <StaticMap reuseMaps mapStyle="style.json" state={true} />}
    <NavigationControl onViewportChange={updateViewport} />
  </DeckGL>
</div>
```
See more in the [Deck Class documentation](http://deck.gl/#/documentation/deckgl-api-reference/deck).

**Comment by HeiYanjing** [comment]
> It looks like you're including the map twice (once with `ReactMapGL` and the second time with `StaticMap`), and you're not including the reference to your mapStyle in your first map, which will cause the error to show.
> 
> Although I haven't used Deck.gl with `NavigationControl`, it looks like it works the same as with `ReactMapGL`. You need to listen to updates to the viewport/viewState via `onViewStateChange`, store the new viewState in your state and pass it back to `DeckGL`. Something like this:
> 
> ```
> <div>
>   <DeckGL
>     layers={this._renderLayers()}
>     viewState={viewState}
>     controller={controller}
>     onViewStateChange={updateViewport}
>   >
>     {baseMap && <StaticMap reuseMaps mapStyle="style.json" state={true} />}
>     <NavigationControl onViewportChange={updateViewport} />
>   </DeckGL>
> </div>
> ```
> See more in the [Deck Class documentation](http://deck.gl/#/documentation/deckgl-api-reference/deck).
> 
> Edit: Nope, I tried this, and it didn't work. It looks like the `NavigationControl`needs to be a child of `StaticMap`, but I couldn't get that to work either. I haven't found any examples of this, but I believe it is doable. Good luck!

Thank you very much
