### ISSUE TITLE
Change base map source from MapBox to another source.

### ISSUE THREAD

**Issue by Abdelrahman146** [uber/react-map-gl#594]
Hello,

I just want to ask if we can change the source of the maps from MapBox to another source.

if yes, how to do that? or from where to start?

Thanks.

**Comment by Pessimistress** [comment]
You can point the [source](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-vector) url in your map style to any server that implements the [Mapbox vector tile spec](https://www.mapbox.com/developers/vector-tiles/).

You will get better support by asking this question on Mapbox's own support channels. A few resources that I know of:
Alternative map tiles: https://www.maptiler.com/cloud/
Generate your own tiles: https://github.com/mapbox/awesome-vector-tiles
