### ISSUE TITLE
getMap() instance mouse events not working

### ISSUE THREAD

**Issue by Pagnito** [uber/react-map-gl#595]
It seems when i pull in an instance of getMap() it comes in as interactive:false and even if i set it manually this.map._interacive=true. It still doesnt respond to mouse events

**Comment by Pagnito** [comment]
Heloooooo, anybody out there

**Comment by Pessimistress** [comment]
The map's `interactive` option is turned off. What mouse event are you trying to use?

**Comment by Pagnito** [comment]
Mousemove and mouseleave. How do i pull in the instance with interactive set to true?

**Comment by Pessimistress** [comment]
Try use the `onHover` prop: https://uber.github.io/react-map-gl/#/Documentation/api-reference/interactive-map

Native map interaction does not work with this library, as discussed in-depth in this thread: https://github.com/uber/react-map-gl/issues/569

**Comment by Pagnito** [comment]
Thats what im currently doing but i have alot of complex hover highlights
and can rly use mouseleave. Is there anything i can implement from
react-map-gl similar?

**Comment by Pessimistress** [comment]
You should be able to use `onMouseLeave` on the parent container of `<MapGL />`.

**Comment by Pagnito** [comment]
Interesting, will it fire off when leaving native mapbox layer features?

On Sep 19, 2018 4:47 PM, "Xiaoji Chen" <notifications@github.com> wrote:

You should be able to use onMouseLeave on the parent container of <MapGL />.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/uber/react-map-gl/issues/595#issuecomment-422952037>,
or mute the thread

**Comment by Pessimistress** [comment]
I see what you're trying to do. No. You have to keep track of the hovered features yourself.

**Comment by Pagnito** [comment]
So do i use queryRenderedFeatures onmouseleave? Is that what you mean?

**Comment by Pessimistress** [comment]
And why is `onHover` not working in this case? Can you share a code snippet?

**Comment by Pagnito** [comment]
OnHover works, to change the featureState which in turn conditionaly
changes the paint settings on that feature but it doesnt change back once u
hover out.
hover=(info)=>{
var feature = this.map.queryRenderedFeatures([info.offsetCenter.x,info.
offsetCenter.y],'segments');
//console.log(feature[0])
if(feature.length>0){
var hoveredSegId = feature[0].id;
this.state.currAndPrev.push(feature[0]);
this.setState({hoveredSeg:feature[0]});
if (hoveredSegId) {
this.map.setFeatureState({source: 'segments', id: hoveredSegId}, { hover:
true});
var connections = JSON.parse(feature[0].properties.connections)
if(connections.continue){
connections.continue.forEach(connectionId=>{
if(Number(connectionId)!==hoveredSegId){
this.map.setFeatureState({source: 'connectionSegs', id: connectionId}, {
connection: true,
color:'light-blue'});
//console.log(typeof connectionId)
}
})
}
if(connections.merge){
connections.merge.forEach(connectionId=>{
if(Number(connectionId)!==hoveredSegId){
this.map.setFeatureState({source: 'connectionSegs', id: connectionId}, {
connection: true,
color:'red' });
//console.log(typeof connectionId)
}
})
}
if(connections.split){
connections.split.forEach(connectionId=>{
if(Number(connectionId)!==hoveredSegId){
this.map.setFeatureState({source: 'connectionSegs', id: connectionId}, {
connection: true,
color:'yellow' });
//console.log(typeof connectionId)
}
})
}
if(connections.right){
connections.right.forEach(connectionId=>{
if(Number(connectionId)!==hoveredSegId){
this.map.setFeatureState({source: 'connectionSegs', id: connectionId}, {
connection: true,
color:'blue' });
//console.log(typeof connectionId)
}
})
}
if(connections.left){
connections.left.forEach(connectionId=>{
if(Number(connectionId)!==hoveredSegId){
this.map.setFeatureState({source: 'connectionSegs', id: connectionId}, {
connection: true,
color:'purple' });
//console.log(typeof connectionId)
}
})
}
}

**Comment by Pagnito** [comment]
btw i ended up figuring it out with just hover, its a bit hacky i guess but
it works, thnx tho

**Comment by Pessimistress** [comment]
Closing and redirecting related discussions to https://github.com/uber/react-map-gl/issues/569

**Comment by Pagnito** [comment]
Hey,

I just signed the petition "We Want Season 2 Of Hwayugi (aka A Korean
Odyssey)" and wanted to see if you could help by adding your name.

Our goal is to reach 15,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/bV4cf85VHS

Thanks!
Pavel
