### ISSUE TITLE
use react-map-gl without mapboxApiAccessToken

### ISSUE THREAD

**Issue by HeiYanjing** [uber/react-map-gl#605]
I have a question.
I want develop native.   download  map resource from openmaptiles and run in a docker.
in my style.json file .url,sprite,glyphs point to local address。
now ,I want Implement  a function.  [a building 3D effects like a deck.gl example](http://deck.gl/#/examples/custom-layers/trip-routes)
and I want add NavigationControl on my page container.
I try for some style. one style like this:
```
        <div className="test" id="map">
            <ReactMapGL {...viewport}  onViewportChange={this._updateViewport}  mapStyle ={MapStyle}>
              <div style={navStyle}>
                <NavigationControl onViewportChange={this._updateViewport} />
              </div>
            </ReactMapGL>
            <DeckGL
            layers={this._renderLayers()}
            initialViewState={INITIAL_VIEW_STATE}
            viewState={viewState}
            controller={controller}
            onViewportChange={this._updateViewport}
            >
              {baseMap && (<StaticMap reuseMaps  mapStyle ={MapStyle}  preventStyleDiffing={true}/>)}
            </DeckGL>
        </div>
```
this is a kind of style I tried.
if I delete mapStyle ={MapStyle}  in ReactMapGL,it will show required a mapbox access token.
and I also tried wrapped Deckgl by ReactMapGL.but failed.
if I do it like this,NavigationControl cannot be show but in react develop tools I can find it.
so I want know ,where am I wrong?

**Comment by Pessimistress** [comment]
You are actually rendering two maps here: `<ReactMapGL>` and `<StaticMap>` and one of them is throwing the error. react-map-gl can be used with deck.gl either as its parent component OR its child.

For your use case, you want your render tree to look like this:

```jsx
<ReactMapGL>
  <DeckGL/>
  <NavigationControl />
</ReactMapGL>
```

See the updated deck.gl example [here](https://github.com/uber/react-map-gl/blob/master/examples/deckgl-overlay/src/app.js)

**Comment by HeiYanjing** [comment]
> You are actually rendering two maps here: `<ReactMapGL>` and `<StaticMap>` and one of them is throwing the error. react-map-gl can be used with deck.gl either as its parent component OR its child.
> 
> For your use case, you want your render tree to look like this:
> 
> ```js-jsx
> <ReactMapGL>
>   <DeckGL/>
>   <NavigationControl />
> </ReactMapGL>
> ```
> 
> See the updated deck.gl example [here](https://github.com/uber/react-map-gl/blob/master/examples/deckgl-overlay/src/app.js)

thank you
