### ISSUE TITLE
ReactMapGL component breaks on Safari 10.1, 11.1, and 12

### ISSUE THREAD

**Issue by tstirrat15** [uber/react-map-gl#606]
## Background
Versions of Safari affected:

* 10.1
* 11.1
* 12

Versions of map libs:

* `react-map-gl`: 3.3.4
* `mapbox-gl`: 0.47.0

In use in my project: webpack, babel, code-splitting

## Observed behavior:
The mapbox map fails to load, and does so without errors in the console.

The handlers are attached to the map, but `queryRenderedFeatures` errors out because the map object that it's being called on doesn't exist, and this error is thrown on every click/mouseover/hover event:
```
[Error] TypeError: undefined is not an object (evaluating 'this._map.queryRenderedFeatures')
	queryRenderedFeatures (vendors~search-components-Root.js:15908:5560)
	queryRenderedFeatures
	_getFeatures (vendors~search-components-Root.js:15819:8209)
	_getFeatures
	_onMouseMove (vendors~search-components-Root.js:15819:9023)
	_onMouseMove
	(anonymous function) (vendors~search-components-Root.js:11504)
	emit (vendors~search-components-Root.js:7307)
	_onOtherEvent (vendors~search-components-Root.js:11561)
	_onOtherEvent
	handleEvent (vendors~search-components-Root.js:11952)
	handleEvent
```
I couldn't see this behavior on either the `react-maps-gl` docs or the `mapbox-gl-js` docs when viewed with those browser versions. Are they pointed at different versions of the libraries?

Is there either error handling or error swallowing going on on the part of the component? I'm surprised that it's possible for `_map` to be undefined.

Could [this line](https://github.com/uber/react-map-gl/blob/master/src/components/static-map.js#L105) be failing silently for some reason?

**Comment by Pessimistress** [comment]
- Does your app work in Chrome?
- Does the [website](https://uber.github.io/react-map-gl) work in your environment?

I've seen this error before, if

```js
this._map.queryRenderedFeatures(geometry, options)
```

is called with `options:undefined`.

Which means in this line 
https://github.com/uber/react-map-gl/blob/3.3-release/src/components/static-map.js#L156
somehow the default argument is not applied?

**Comment by cyrilchapon** [comment]
Related with https://github.com/uber/react-map-gl/pull/560 ?

**Comment by tstirrat15** [comment]
@Pessimistress the referenced website does work on those versions of safari, and my site does work with chrome. Does that point at that being the issue?

The problem there is that I'm not calling `queryRenderedFeatures` directly, and there's nothing in the API that would allow me to work around it, from what I can see.

I'm seeing this problem with a minimal `<ReactMapGL />` instantiation that only includes the `viewport` object, an `onViewportChange` that sets viewport state, and the API key. I can't see how I would provide that object if it's missing.

**Comment by tstirrat15** [comment]
@cyrilchapon that looks plausible...

**Comment by tstirrat15** [comment]
It's now looking like the map isn't loading at all. I switched to `StaticMap` to verify that it wasn't a problem with the lifecycle of the `InteractiveMap`, and the `StaticMap` isn't rendering either.

I'll try and see if it's related to a particular version.

**Comment by tstirrat15** [comment]
Update: it's CSP-related.

Disabling CSP on my project caused the map to start working again. The thing that's strange to me is that it was only safari that had this issue - all of the other browsers were fine. I'll open an issue on mapbox-gl-js about this.

**Comment by tstirrat15** [comment]
Mapbox issue for anyone interested: https://github.com/mapbox/mapbox-gl-js/issues/6892
