### ISSUE TITLE
double-click zooming follows a strange arc path

### ISSUE THREAD

**Issue by vbud** [uber/react-map-gl#612]
We've been trying to understand why double-click zooming behaves so much different in react-map-gl than in mapbox-gl. Observe the difference by double-click zooming on these two examples:
https://www.mapbox.com/mapbox-gl-js/example/simple-map/
https://uber.github.io/react-map-gl/#/Examples/dynamic-styling

The mapbox-gl example translates between point A and point B as you would expect. The react-map-gl example starts and ends at the same points, but it follows a strange arcing path to get there.

Is this a bug? Or something we could override?

**Comment by Pessimistress** [comment]
Published 3.3.7

**Comment by vbud** [comment]
Thank you so much @Pessimistress!
