### ISSUE TITLE
Mapbox GL JS *-transition properties and State Immutability 

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [uber/react-map-gl#634]
This is probably not an _issue_ but I'm not aware of a better place to pose the question. My apologies if this is not an appropriate place for this question. Feel free to close this issue.

There are a few examples in this repo that illustrate how Mapbox GL styling can be set dynamically and managed in State in a immutable fashion usually using immutable.js.  The Mapbox style spec. says that *-transition properties can be used to perform property transitions. These transitions work as expected when the Mapbox map style is is updated with Mapbox GL JSs' setPaintProperty() Map method. I am wondering how I can produce the transition effect without the use of the setPaintProperty method. When I use immutable.js to set the paint property for the style, the style change is reflected in the map after the state is updated but the transition never happens, and I wonder if that has to do with the immutable state of the map style. Thanks in advance for any advice.

**Comment by Pessimistress** [comment]
Which version are you using? Can you try 4.0.0-beta.3 and let me know if it fixes the issue?

**Comment by wheredoesyourmindgo** [comment]
Yes. 4.0.0-beta.3 fixes this issue. Maybe related to the use of Mapbox's style diffing? Looks like I have some new performance glitches with this beta during zoom and transition but I'll look into that separately. Thanks again @Pessimistress
