### ISSUE TITLE
example "filter" crush with props type cheking error

### ISSUE THREAD

**Issue by Akiyamka** [uber/react-map-gl#635]
```     
<MapGL
    width="100%"
    height="100%"
    ...
</MapGL>
```
Failed prop type: Invalid prop `width` of type `string` supplied to `InteractiveMap`, expected `number`. in InteractiveMap

**Comment by Pessimistress** [comment]
Please use examples on the 3.3-release branch. Master is dev branch and only works with non-production versions.

**Comment by Pessimistress** [comment]
Updated example dependencies to beta release
