### ISSUE TITLE
Not easy to separate `MapControls` from `TransitionManager`

### ISSUE THREAD

**Issue by tilgovi** [uber/react-map-gl#641]
I would ilke to maintain the start and end viewports outside the react-map-gl components. One complication that makes this difficult is that `setOptions()` on the `MapControls` class sets the `onViewportChange` callback for itself but and also passes it to the `TransitionManager`. The callback is then invoked for two separate purposes: to advance the viewport to the next transition frame and to initiate a new transition.

I could re-implement `MapControls` according to my liking. It's tempted to do this because I know `MapControls` is also marked as experimental. However, `TransitionManager` would be a useful class but it's not exported at all.

Another approach would be to separate the callbacks. Right now, I have the following code:

``` javascript
class MapControls extends ReactMapGLExperimental.MapControls {
  constructor(updateTargetViewport) {
    super();
    this._updateTargetViewport = updateTargetViewport;
  }

  setOptions(options) {
    super.setOptions(options);

    // The base class implementation has passed the `onViewportChange` option to a transition
    // manager that will invoke it for each frame of any transitions. Rather than use the same
    // callback for initiating new transitions, override the reference held by this instance so
    // that it uses the callback with which it was constructed, rather than the callback held by
    // the transition manager.
    this.onViewportChange = this._updateTargetViewport;
  }
}
```

What can be done to make the existing components more friendly for those who wish to track the current and target viewport states?

**Comment by Pessimistress** [comment]
Help me understand why this is needed - do you want different callbacks invoked by user interaction and transition?

**Comment by tilgovi** [comment]
That's exactly what I'd like.

In the project where I'm using react-map-gl, it's been useful to keep the viewport state available globally and not just to children of the map component. I am keeping separate the current viewport and the target (or destination) viewport of the active transition, otherwise observers see a flash of the end transition state until the next update cycle of the map triggers the transition to start and invoke the callback for the initial frame. I can't keep that state separate if I can't determine why the callback is being invoked, whether it's for a transition frame or a user interaction.

**Comment by Pessimistress** [comment]
Could you take a look at [v4.0 API](https://github.com/uber/react-map-gl/blob/master/docs/components/interactive-map.md#onviewportchange-function) - we're adding richer interaction state flags to `onViewportChange` including `inTransition`. Would it be sufficient for your use case? This is already published in 4.0.0-beta.3 if you're willing to give it a try.

**Comment by tilgovi** [comment]
I'll dig in, but I have been glancing at master every now and then to see what's changing. My suspicion is that this won't help if it just indicates the presence of an active transition. When the map controls invokes the callback, it would be set if there's a transition in progress but not set if it there isn't. What I want to know is whether _this_ invocation of the callback is passing the props for the current transition frame or the end props that will trigger a new transition, even if that means breaking one in progress.

**Comment by tilgovi** [comment]
Let me double check and get back to you. Thanks.

**Comment by Pessimistress** [comment]
Theoretically you **should** always get a callback without `inTransition` if it's initiated by user interaction. That's what it's designed to do anyways...

**Comment by Pessimistress** [comment]
> Let me double check and get back to you

Overall, I'd say this new API was put in place to support the use cases like yours. I really appreciate you help testing this. If it doesn't meet that goal let's revisit the design.

**Comment by tilgovi** [comment]
Oof, I'm not able to easily test this in my current project because it now requires react 16. I'll see what I can deduce from a careful code reading or setup a little sandbox.

**Comment by Pessimistress** [comment]
> setup a little sandbox

You can also test the behavior by going to `examples/interaction` and run `yarn start-local`:

![image](https://user-images.githubusercontent.com/2059298/47827735-c81e3800-dd3c-11e8-948b-41aafaf4ca18.png)

**Comment by tilgovi** [comment]
Works beautifully, thank you.

What I was missing was that even though `inTransition` is stored in the map controller's state, it's ignore by the constructor of `MapState`, so it's only set when the transition manager invokes the callback.

Thanks for your patience and help!
