### ISSUE TITLE
Closing Popup requires double click

### ISSUE THREAD

**Issue by MarcusPenn** [uber/react-map-gl#657]
Hi All,

I've found a bug on the close button provided on the Popup after updating to the latest version.

Two clicks are required to close the popup, the first on the button itself and the second anywhere on the popup.

I believe this issue comes from the following code in the Popup class, with the events firing in the wrong order.

`/*
   * Hack -
   * React's `onClick` is called before mjolnir.js' `click` event (aka `tap` from hammer.js)
   * which has a configurable delay.
   * If we close the popup on the React event, by the time `click` fires, this component will
   * have been unmounted, thus `captureClick` will not work.
   * Instead, we flag the popup as closed on the React event, and actually close it on the hammer.js
   * event.
   */
  _onClick = (evt) => {
    if (this.props.captureClick) {
      evt.stopPropagation();
    }

    if (this.props.closeOnClick || this._closeOnClick) {
      this.props.onClose();
    }
  }

  _onClose = () => {
    this._closeOnClick = true;
  }`

If I get some time I'll do a quick code sample to show it.

**Comment by Pessimistress** [comment]
I can't reproduce this issue on https://uber.github.io/react-map-gl/#/Examples/markers-popups

**Comment by rcbdev** [comment]
That example has `closeOnClick` enabled, which means clicking anywhere closes the popup. This bug only shows with `closeOnClick={false}` and `closeButton={true}`. I've set up a reproduction: https://xlqkz3jnyo.codesandbox.io/. This is identical to the page you linked, but with `closeOnClick={false}` on the popup component.

It looks like the events no longer fire in the correct order, with the hammer.js event firing first, and the standard onClick firing second, meaning the popup only closes on the second click. This is on the latest chrome build (70).

**Comment by Pessimistress** [comment]
Fix published in 4.0.2.
