### ISSUE TITLE
Rendering NavigationControl with deck.gl

### ISSUE THREAD

**Issue by GunnarSturla** [uber/react-map-gl#662]
Hello, I'm not sure if this issue belongs in this repo or deck.gl, let me know if you'd rather have over there.

I'm using react-map-gl with deck.gl, and when I try to use the NavigationControl in my setup, the deck.gl canvas has a higher z-index than the map, and therefor blocks mouse events to the NavigationControl. I haven't seen examples of deck.gl using NavigationContol, so I'm not sure it's at all possible.

Here's roughly my code
```js
        <DeckGL
          layers={[layer]}
          controller={true}
          width={500}
          height={300}
          viewState={viewState}
          onViewStateChange={this.handleViewStateChange}
        >
          <StaticMap mapStyle={defaultMapStyle}>
            <div className="nav" style={navStyle}>
              <NavigationControl
                onViewportChange={viewState =>
                  this.handleViewStateChange({ viewState })
                }
              />
            </div>
          </StaticMap>
        </DeckGL>
```

In the resulting HTML the deck.gl canvas and the react-map-gl StaticMap are in separate stacking contexts (each having `position: absoulte` set), with deck.gl (naturally) staying on top. That makes  increasing the z-index of the NavigationControl not sufficient.

One possible solution coule be to make NavigationControl a sibling of DeckGL, but it can't since it depends on having `viewport` in its context. Is there any other way to do it?

I had an idea, since I'm already managing `viewState` myself, to pass it directly on to NavigationControl. Would you accept a PR that would open up that possibility (and using the context when it's not being passed as props)? It should be a pretty simple change with the addition of only a couple of lines.

**Comment by Pessimistress** [comment]
You may try use this template: https://github.com/uber/react-map-gl/tree/master/examples/deckgl-overlay where DeckGL is rendered as a child of ReactMap. You will be able to control the z-index between DeckGL and the NavigationControl then.

**Comment by mdhiabouthuri** [comment]
//Try this
<div style={{zIndex: '1'}}>
              <NavigationControl/>
 </div>

**Comment by Pessimistress** [comment]
deck.gl 7.1 and above support [ContextProvider](https://deck.gl/#/documentation/submodule-api-reference/deckgl-react/deckgl?section=react-context).

```jsx
/// Example using react-map-gl controls with deck.gl
import DeckGL from '@deck.gl/react';
import {_MapContext as MapContext, StaticMap, NavigationControl} from 'react-map-gl';

<DeckGL ... ContextProvider={MapContext.Provider}>
  <div style={{position: 'absolute}}>
    <NavigationControl />
  </div>
  <StaticMap />
</DeckGL>
```

**Comment by kylebarron** [comment]
@Pessimistress I'm trying to use the `ContextProvider` method in your last comment, but I can't get the `NavigationControl` to be _clickable_. 

When I put the `div` for the `NavigationControl` before `StaticMap`, I don't see the control at all (the `StaticMap` covers it?).

```jsx
<DeckGL
  initialViewState={initialViewState}
  controller={true}
  layers={layers}
  ContextProvider={MapContext.Provider}
>
  <div style={{ position: "absolute", right: 30, top: 120 }}>
    <NavigationControl />
  </div>
  <StaticMap
    mapboxApiAccessToken={MAPBOX_ACCESS_TOKEN}
    mapStyle={mapStyle}
  />
</DeckGL>
```

When I put the `div` for the `NavigationControl` _after_ `StaticMap`, I see the `NavigationControl`, but it's not clickable.

```jsx
<DeckGL
  initialViewState={initialViewState}
  controller={true}
  layers={layers}
  ContextProvider={MapContext.Provider}
>
  <StaticMap
    mapboxApiAccessToken={MAPBOX_ACCESS_TOKEN}
    mapStyle={mapStyle}
  />
  <div style={{ position: "absolute", right: 30, top: 120 }}>
    <NavigationControl />
  </div>
</DeckGL>
```

Is there something simple I'm doing wrong?

**Comment by kylebarron** [comment]
Sorry, just added `style={{zIndex: '1'}}` and it works for me!

So for future reference, this code works:
```jsx
<DeckGL
  initialViewState={initialViewState}
  controller={true}
  layers={layers}
  ContextProvider={MapContext.Provider}
>
  <StaticMap
    mapboxApiAccessToken={MAPBOX_ACCESS_TOKEN}
    mapStyle={mapStyle}
  />
  <div style={{ position: "absolute", right: 30, top: 120, zIndex: 1 }}>
    <NavigationControl />
  </div>
</DeckGL>
```

**Comment by Jamal8548** [comment]
> ```js
> import {_MapContext as MapContext, StaticMap, NavigationControl} from 'react-map-gl';
> ```
I am having this error with React map gl and deckgl. I am trying to use React map gl navigational controls on deckgl. Please help.
export '_MapContext' (imported as 'MapContext') was not found in 'react-map-gl' (possible exports: AttributionControl, FullscreenControl, GeolocateControl, Layer, Map, MapProvider, Marker, NavigationControl, Popup, ScaleControl, Source, default, useControl, useMap)

**Comment by Jamal8548** [comment]
**found solution. (I was using version 7 so it was not working.)**
If you are using react-map-gl controls (Marker, Popup, NavigationControl etc.) with deck.gl's ContextProvider, do not upgrade to this version. The old approach no longer works with v7. We are moving the support for this use case to a new project that does not depend on mapbox.

**Comment by vnugent** [comment]
@Jamal8548 have you found a solution? 
 I'm using `mapbox-gl` and am facing similar issues with the latest react-map-gl (v7.0.10) + deck.gl (v8.7.0).  All examples in Deck.gl docs are out-dated (still using MapContext)

``` javascript
<DeckGL
      layers={layers}
      onViewStateChange={onViewStateChange}
      initialViewState={DEFAULT_INITIAL_VIEWSTATE}
    >
      <Map
        reuseMaps
        mapStyle='<redacted>'
        mapboxAccessToken='<redacted'
      />
      <NavigationControl /> // <--- causing error
    </DeckGL>
```

### error

navigation-control.js?3853:6 Uncaught TypeError: Cannot destructure property 'mapLib' of 'object null' as it is null.
    at NavigationControl.ctrl.position (navigation-control.js?3853:6:32)
    at eval (use-control.js?5f43:5:25)
    at mountMemo (react-dom.development.js?ac89:15846:1)

**Comment by Jamal8548** [comment]
@vnugent i have drafted my solution above. Please read it carefully. You just need to change versions.

**Comment by Jamal8548** [comment]
@vnugent please don’t use version 7 for react map gl. Use any version but below version 7 and then it will work all fine! Hope you got my point.

**Comment by frafra** [comment]
Using version 6.1.x is a workaround, not a definitive solution. It also does not seem to work with other components (Attribution and Source fails here, for example, but it could be due to something else). I tried hard to use different methods, or use deck.gl as a mapbox layer, but I failed to get something usable.

I would have guessed that using deck.gl with mapbox controls would have popular, so I was surprised to read that the developers dropped `MapContext` without providing an alternative.

**Comment by suryakumara** [comment]
ContextProvider={MapContext.Provider}
  MapContext.Provider not support now. any idea I can use this control ?

**Comment by aemonm** [comment]
Try making `<NavigationControl />` a child of `<Map />`.

```jsx
<DeckGL
  layers={layers}
  onViewStateChange={onViewStateChange}
  initialViewState={DEFAULT_INITIAL_VIEWSTATE}>
      <Map
        reuseMaps
        mapStyle='<redacted>'
        mapboxAccessToken='<redacted'>
        <NavigationControl />
    </Map>
</DeckGL>
```

**Comment by smartsense-as** [comment]
@aemonm Then you can't click on the controls because DeckGL canvas sits on top of everything.
