### ISSUE TITLE
Hash option not supported ?

### ISSUE THREAD

**Issue by jetaix** [uber/react-map-gl#665]
How can I add he classic #hash map option from `mapbox-gl-js` ?

From Mapbox:
![image](https://user-images.githubusercontent.com/4866709/49151972-ad29ee00-f311-11e8-8a1d-245263f45ba6.png)

If is not the case it's should be very helpful to add this. 🤗

**Comment by Pessimistress** [comment]
Try the `mapOptions` prop: https://uber.github.io/react-map-gl/#/Documentation/api-reference/static-map?section=initialization

**Comment by jetaix** [comment]
It's work. `mapOptions={{ hash: true }}`.
Thx @Pessimistress
