### ISSUE TITLE
New translation to Czech

### ISSUE THREAD

**Issue by siberin** [uber/react-map-gl#667]
Sorry, this is not an issue, just some questions about the SDK

Currently I'm building an app with Czech language, but the SDK has not supported Czech yet. 
Can I add the localization file inside my app?
If I can not add the localization file, what should I do?
Thanks.

**Comment by Pessimistress** [comment]
This question will be better answered in https://github.com/mapbox/mapbox-gl-js. react-map-gl does not handle any of the data and rendering logic.

**Comment by siberin** [comment]
Tx :)
