### ISSUE TITLE
Error - Module not found: Error: Can't resolve '@turf/bbox'

### ISSUE THREAD

**Issue by andreivictor** [uber/react-map-gl#678]
I am getting the following error while running "npm run start":

ERROR in ../zoom-to-bounds/src/app.js
Module not found: Error: Can't resolve '@turf/bbox' in '/Users/(xxx)/react-map-gl/examples/zoom-to-bounds/src'

node: v8.12.0
yarn: 1.12.3
webpack: 4.27.1

Thanks!

**Comment by Pessimistress** [comment]
`@turf/bbox` is listed as a dependency: https://github.com/uber/react-map-gl/blob/master/examples/zoom-to-bounds/package.json#L7

Did you encounter any error when installing dependencies?

**Comment by andreivictor** [comment]
I had set up the app as described in this page (https://github.com/uber/react-map-gl/blob/master/docs/developer-guide.md).

```
$ git clone https://github.com/uber/react-map-gl.git
$ cd react-map-gl
$ yarn
$ npm run start
```

I run ```npm run start``` in ```/react-map-gl``` folder.

**Comment by Pessimistress** [comment]
Ah my bad. Yes, the master example is missing the dependency.

**Comment by Pessimistress** [comment]
This should be fixed now.
