### ISSUE TITLE
Remove console debug at initialization

### ISSUE THREAD

**Issue by jaydenseric** [uber/react-map-gl#687]
There is a pointless and annoying `console.debug` call at the initialization of the `Mapbox` class that looks like this:

<img width="359" alt="screen shot 2019-01-08 at 2 41 23 pm" src="https://user-images.githubusercontent.com/1754873/50808641-91275c80-1353-11e9-8394-64614fcbed0a.png">

It was appears to have been introduced by accident in a PR to update the `mapbox-gl` dependency: 

https://github.com/uber/react-map-gl/pull/459/files#diff-b831149c1a9619d0b0f5c621aa179d8aR122

Consumers often have thousands of nested npm dependencies; imagine how unhelpful it would be if they all `console.debug` their versions.

I can't see a way for consumers to opt-out; the best thing to do is to simply remove it and save everyone's bundles the extra bytes.

**Comment by Pessimistress** [comment]
@ibgreen

**Comment by ibgreen** [comment]
> I can't see a way for consumers to opt-out; 

Hmm yes, this line is occasionally very useful when debugging issues in any one of our myriad deployed applications that use react-map-gl, but I get your point.

The only idea I have is that in our other frameworks we use `probe.gl` to log, which would allow us to disable this log by default and let the user activate such logging in the browser console when needed (and then just reload the app).

probe.gl is not a big dependency (and already pulled in by companion frameworks like deck.gl) that said it would mean adding a dependency just for this one line.

@Pessimistress I think you should make the call here: in, out, or probe.gl. If having debug logging available in react-map-gl could be more generally useful (e.g. tracking map reuse and such), then I'd say let's go with probe.gl.

**Comment by Pessimistress** [comment]
@jaydenseric I think @ibgreen is referring to internally we sometimes need to debug deployed applications without having access to the remote instance that built the bundle. When using mapbox-gl, it exposes a `mapboxgl` global which allows you to check the version. react-map-gl hides it from the client.

I agree with you that the package should not print arbitrary debug info to the console. I will remove it now and work on a long term solution.

**Comment by Pessimistress** [comment]
4.0.7
