### ISSUE TITLE
Marker is jumping at start of drag and only works with offset

### ISSUE THREAD

**Issue by timendez** [uber/react-map-gl#691]
I'm having trouble with dragging with an offset. At the start of drag the marker jumps up and to the left. Oddly enough, when I remove the offsets now, the marker isn't dragging at all.
```javascript
<ReactMapGL
  ref={map => (this.mapRef = map)}
  {...viewport}
  mapboxApiAccessToken={MAPBOX_ACCESS_TOKEN}
  onViewportChange={viewport => this.setState({ viewport })}
>
  <Marker
    latitude={marker.latitude}
    longitude={marker.longitude}
    offsetLeft={-10}
    offsetTop={-25}
    draggable
    onDragEnd={this.onMarkerDragEnd}
  >
    <img
      width="20px"
      height="25px"
      src="https://image.flaticon.com/icons/svg/33/33622.svg"
    />
  </Marker>
</ReactMapGL>
```

![why](https://user-images.githubusercontent.com/4667806/51286578-759e0080-19a8-11e9-8017-33839c2b86bb.gif)

If it matters, this is embedded in an electron app, but that really shouldn't from my knowledge of electron.

Thanks!

**Comment by timendez** [comment]
Additionally, the marker from [the example](https://uber.github.io/react-map-gl/#/Examples/draggable-marker) can be dragged by the bottom right of the marker.
![gif](https://user-images.githubusercontent.com/4667806/51357157-6aafa280-1a72-11e9-9e3a-28ddcbdcdc2c.gif)

**Comment by Pessimistress** [comment]
@schnerd

**Comment by schnerd** [comment]
Thanks for calling this out @timendez, opened #693 to try to address this.

> Oddly enough, when I remove the offsets now, the marker isn't dragging at all.

This might be because you're using an `<img>` in marker. This should work but I think you may need to set `draggable={false}` on the image or use a `-webkit-user-grab: none` css rule on the image. This helped for me during testing.

**Comment by timendez** [comment]
Thanks for fixing this so quickly!

**Comment by Pessimistress** [comment]
4.0.8
