### ISSUE TITLE
Local build not working due to babel package error

### ISSUE THREAD

**Issue by timendez** [uber/react-map-gl#695]
In https://github.com/uber/react-map-gl/blob/master/.babelrc, there is a package listed as `@babel/transform-runtime` in 4 different places.

I believe the correct package name is `@babel/plugin-transform-runtime`.

Changing this caused a successful build upon `./scripts/build.sh`

**Comment by Pessimistress** [comment]
I don't think that's the issue. This is how babel names its packages. Here are the dependencies:

```
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-flow": "^7.0.0",
```

And here are how they are referenced:

```
      "presets": [
        ["@babel/env", {modules: 'commonjs'}],
        "@babel/flow"
      ],
      "plugins": [
        "@babel/transform-runtime",
        "@babel/proposal-class-properties"
      ]
```

**Comment by timendez** [comment]
Ah ok sorry, closing as I no longer have the need to build
