### ISSUE TITLE
Proposal: default onError handler

### ISSUE THREAD

**Issue by macobo** [uber/react-map-gl#701]
Without an `onError` handler, react-map-gl swallows all errors when, say, the mapStyle is in an illegal format.

The getting started guide and examples on the github home page don't emphesize this option, so I'm proposing using `console.error` or `console.warn` as a default. Otherwise new users can spend hours trying to debug their styles without a proper feedback loop.

Based on comments, I'd say this would have made resolving https://github.com/uber/react-map-gl/issues/588 and https://github.com/uber/react-map-gl/issues/606 and https://github.com/uber/react-map-gl/issues/608 easier?

**Comment by Pessimistress** [comment]
Does mapbox-gl-js throw an error if no listener is attached?

**Comment by macobo** [comment]
Seems so from a quick experiment: http://jsfiddle.net/yd80vngx/

**Comment by Pessimistress** [comment]
Published in 4.0.10.
