### ISSUE TITLE
Can't see Marker component

### ISSUE THREAD

**Issue by pkayokay** [uber/react-map-gl#705]
Marker component not visible, not getting the css file warning. So I checked the React Dom and the Marker component is not there.

I have a child component
```
class Map extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      viewport: {
        latitude: this.props.defaultCenter.lat,
        longitude: this.props.defaultCenter.lng,
        zoom: this.props.defaultZoomLevel,
      },
    };
  }

  render() {
    return (
      <div >
        <ReactMapGL
          {...this.state.viewport}
          height={400}
          width="100%"
          attributionControl={false}
          mapboxApiAccessToken={this.props.popmenuConfig.mapboxPublicKey}
          mapStyle="mapbox://styles/mapbox/streets-v8"
          onViewportChange={(viewport) => { this.setState({ viewport }); }}
        />
      </div>
    );
  }
}
```

that is within

```
      <Map
        defaultCenter={this.centerCoordinates()}
        defaultZoomLevel={this.props.defaultZoomLevel}
        locations={this.validLocations()}
      >
        {this.validLocations().map(location => (
          <Marker
            key={location.id}
            latitude={location.lat}
            longitude={location.lng}
            onClick={MapSection.handleMarker(location)}
            offsetLeft={-20}
            offsetTop={-10}
          >
            <Icon icon="star" />
          </Marker>
        ))}
      </Map>
```
I think it's the way I'm importing my module, so it's never actually using that component I am not able to import in the context of my app.

`import ReactMapGL, { Marker } from 'react-map-gl';`

Would `const Marker = require('react-map-gl').Marker;` be equivalent?

**Comment by jcready** [comment]
Your `Map` component needs to pass its `children` prop down to the `ReactMapGL` component.

```js
  render() {
    return (
      <div >
        <ReactMapGL
          {...this.state.viewport}
          height={400}
          width="100%"
          attributionControl={false}
          mapboxApiAccessToken={this.props.popmenuConfig.mapboxPublicKey}
          mapStyle="mapbox://styles/mapbox/streets-v8"
          onViewportChange={(viewport) => { this.setState({ viewport }); }}
          children={this.props.children} // <== this bit
        />
      </div>
    );
  }
```

**Comment by pkayokay** [comment]
Ah. I see the markers now on the React DOM but without styles. Should they inherit styles by default?

https://github.com/uber/react-map-gl/blob/master/docs/components/marker.md

Not getting the css warning

**Comment by macobo** [comment]
That file absolutely has this class:

```
.mapboxgl-marker {
    position: absolute;
    top: 0;
    left: 0;
    will-change: transform;
}
```

However, this doesn't mean that they look pretty. In the examples of this library additional styling is added for example for https://uber.github.io/react-map-gl/#/Examples/markers-popups in https://github.com/uber/react-map-gl/blob/4.0-release/examples/controls/src/city-pin.js

**Comment by pkayokay** [comment]
Ah yes, found this class shortly after posting this. I expected the `<Marker />` component to display an icon/pin of sorts by default but looking at the resource you provided I can just follow that example.

I was also wondering why a simple `onClick` would not function but that example shows this as well.

Thanks!
