### ISSUE TITLE
Race condition between styles loading and InteractiveMap.interactiveLayerIds

### ISSUE THREAD

**Issue by macobo** [uber/react-map-gl#707]
We've now seen this error in production a few times. 

![screenshot from 2019-01-27 11-00-05](https://user-images.githubusercontent.com/148820/51798941-3763d500-2223-11e9-8f08-eb870af8c542.png)

This happens if:

1. You have `interactiveLayerIds` set
2. You move the cursor on the map before mapbox is done loading styles

I currently don't have a jsfiddle prepared, but can prepare it if needed.

No visible breakage afterwards, the application runs as intended, but the uncaught error is clogging up our error handling tools.

### Proposed fix

Since the problem comes from the library querying the map before the styles are loaded, a possible fix is to ignore all mouse events until `onLoad` has fired. 

Happy to provide a fix, though I'm struggling a bit with writing good tests for this in your setup (used to jest + enzyme).

**Comment by Pessimistress** [comment]
Fix published in 4.0.10.

**Comment by rgazelot** [comment]
Hello guys, actually the issue is still there according to what I experienced. 
![Screenshot 2021-01-19 at 12 20 57](https://user-images.githubusercontent.com/1488251/105028100-e3c2a580-5a50-11eb-94c8-29aeabe0cc7e.png)

Exact same behaviour, you move your mouse over the map before the map style is rendered. I'm using the v5.2.12, but maybe I missed something?

**Comment by AntonRaichuk** [comment]
Seeing the same issue as @rgazelot 


@Pessimistress could you take a look?

**Comment by koooge** [comment]
I got the same error message with 7.0.19.

workaround:

```js
const [interactiveLayerIds, setInteractiveLayerIds] = useState<string[]>([])

<ReactMapboxGl
  interactiveLayerIds={interactiveLayerIds}
  onLoad={() => setInteractiveLayerIds(['someLayerId'])}
  ...
>
```
