### ISSUE TITLE
Element type is invalid for Interactive Map

### ISSUE THREAD

**Issue by altrang** [uber/react-map-gl#710]
Hello, I just discover this library and i have some problem using the 'Getting started' example

The error i have is:  
"Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `InteractiveMap`."

Do you have any idea on how to fix this? 
I tried using component as Class, as functional component, but still getting the same error

I m using 
"react-map-gl": "4.0.10", 
"react": "16.3",
"typescript": "2.7.2",

Thanks a lot

**Comment by xintongxia** [comment]
@altrang

This error is thrown from `react`, probably the way you import a component is not correct. You can google the error to get some hints. 

Also there are a couple of standalone examples in `react-map-gl`. I will suggest you check some and compare with your own code, it would be helpful.

For example, [layers](https://github.com/uber/react-map-gl/tree/master/examples/layers) is a simple one. 

If you still can not figure out, post your code here, I can give a look.

**Comment by altrang** [comment]
Thanks a lot for your answer ! 
Well i just tried the example from layers, here is my code : 

`import React, { Component } from "react";
import MapGL from "react-map-gl";

const MAPBOX_TOKEN = ""; // Set your mapbox token here

export default class App extends Component {
  public state = {
    mapStyle: "",
    viewport: {
      latitude: 37.805,
      longitude: -122.447,
      zoom: 15.5,
      bearing: 0,
      pitch: 0
    }
  };

  public _onViewportChange = viewport => this.setState({ viewport });

  public _onStyleChange = mapStyle => this.setState({ mapStyle });

  public render() {
    const { viewport, mapStyle } = this.state;

    return (
      <MapGL
        {...viewport}
        width="100%"
        height="100%"
        mapStyle={mapStyle}
        onViewportChange={this._onViewportChange}
        mapboxApiAccessToken={MAPBOX_TOKEN}
      />
    );
  }
}`

I just removed the controlPanel part of it.

Then i just do 

`  <Route exact path="/test" key="/test" component={Map} />,`

And i m still having the same issue. 
I know that this error can come from an import so i checked it, i m trying to use react mapbox in an existing project and i never had this prob before, and i dont have it on other page. 
If you can help me on this.

**Comment by xintongxia** [comment]
What is the `Map` component you passed to `Route`?

**Comment by altrang** [comment]
Import Map from 'mypath'

**Comment by altrang** [comment]
I just updated my react to 16.3.1, react dom to 16.3.1 and typescript to 2.8 and well its working ! I dont really know why it's working now, but version compatibility seemed to be the prob here. 
Thanks a lot for your answers :)
