### ISSUE TITLE
Update to docs: Display Maps Without A Mapbox Token

### ISSUE THREAD

**Issue by thomasgwatson** [uber/react-map-gl#711]
Recently went through the process of adding a non-Mapbox base layer to a ReactMapGL instance.

At a minimum, I wish the docs had directed me to https://docs.mapbox.com/mapbox-gl-js/style-spec/ instead of https://docs.mapbox.com/mapbox-gl-js/style-spec/#sources-vector 

It is a small difference in url (its the same page!) but the data structure of the overall spec is so much more important to get that one of its subparts (just the source)

In addition, there were a few other pointers that would be helpful

-don't forget to convert to immutable data structure
-Your style depends on what schema your vector tile is in
-other authorization patterns (reference the transformRequest API)

I want to submit a pull-request but before I do, just filing this in to have an issue to reference and would love to get a quick read on which (if any) of the extra pointers I should include. Thanks!

**Comment by macobo** [comment]
We've done the same at eAgronom. Note that immutable.js is not needed at all, you can as well pass normal objects as mapStyle

**Comment by thomasgwatson** [comment]
@macobo I haven't tested but was going off the comments in: https://github.com/uber/react-map-gl/issues/119

"mapStyle is expected to be an ImmutableJS object or a url string. Wrapping your style first in an ImmutableJS object with Immutable.fromJS(mapStyle) should resolve the issue." Has that changed?

Also... @xintongxia added the docs tag but... not sure if there is interest in a pull request about this?

**Comment by Pessimistress** [comment]
Please do!

Re: immutable - immutable.js dependency was removed in v4.0. You can still use it to avoid the awkward spreading operation, but it's no longer required.
