### ISSUE TITLE
Storing Layers in Redux

### ISSUE THREAD

**Issue by ctaylor4874** [uber/react-map-gl#717]
Hello,

What is the preferred method of storing layers in Redux?  Is there an API or method that can convert Mapbox style spec (json) to layer props?  For example, converting

```json
{
    "circle-color": [
        "rgb",
        ["get", "temperature"],
        0,
        ["-", 100, ["get", "temperature"]]
    ]
}
```
to 
```json
getFillColor: () =>  ...
```

Any help is appreciated!

**Comment by Pessimistress** [comment]
There is an experimental `@deck.gl/json` module that targets the use case of transfer and reconstruction of layers from JSON objects.

@ibgreen I don't think it has implemented dynamic accessors but that's the plan?

**Comment by Pessimistress** [comment]
Is this a deck.gl question? Let's move the conversation to the other repo if so.

**Comment by ctaylor4874** [comment]
Ok will do, thank you.
