### ISSUE TITLE
RTLTextPlugin for right-to-left text

### ISSUE THREAD

**Issue by aboganas** [uber/react-map-gl#727]
I am struggling to get RTLTextPlugin to work with react-map-gl. I tried the solution in #498 but no luck.
Please I appreciate any help or suggestion

**Comment by Pessimistress** [comment]
We are no longer using the mapbox-gl version from that time. You need to use the plugin that works with the current version. See https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/

**Comment by aboganas** [comment]
Still not working.
the versions I'm using 
```
react-map-gl: 3.3.9
mapbox-gl: 0.50.0
mapbox-gl-rtl-text: 0.2.1 
```
also tried the latest version of each.

here is an example of the file that I'm adding the code to:
https://github.com/apache/incubator-superset/blob/master/superset/assets/src/visualizations/MapBox/MapBox.jsx

I greatly appreciate your help

**Comment by michalczmiel** [comment]
@Pessimistress  Any progress on this issue? I have also tried with the newest versions of `react-map-gl`, `mapbox-gl` and `mapbox-gl-rtl-text`

**Comment by vicapow** [comment]
Couple things worth double checking:

* Ensure there aren't separate instances of mapbox-gl that react-map-gl is using and your app is using. (`node_modules/react-map-gl/node_modules/mapbox-gl` should not exist.)
* Ensure `node_modules/mapbox-gl/` exists and is using the correct version as react-map-gl.
* `mapbox-gl-rtl-text` should be version `v0.2.0` (`0.2.1` may work as well)
* If your app relies on universal rendering, you may need to add some logic to catch errors related to `self` when the code is running from Node.

````js
try {
  const mapboxgl = require('mapbox-gl');
catch (e) {
 // server side code. there is probably a better way to do this :/
}
````

**Comment by vicapow** [comment]
closing since this is verified to work in react-map-gl but please re-open if you're still having issues.

**Comment by mousavihasans** [comment]
I cannot figure out how to add RTL to my StaticMap which is inside a deck.gl component. Would you please explain more, I could not handle it using the above link.
