### ISSUE TITLE
mapbox-gl 0.53

### ISSUE THREAD

**Issue by herchu** [uber/react-map-gl#737]
We are using react-map-gl, and wanted also to use a feature (clusterProperties) from mapbox-gl v0.53  which is still not supported in v0.52.

Current react-map-gl depends on `mapbox-gl: "~0.52.0"`. Is there a timeline for supporting 0.53, a planned release date?

**Comment by Pessimistress** [comment]
react-map-gl locks to a minor release because we utilize some of mapbox-gl's private APIs. We just need to do some manual testing to make sure nothing breaks. I'll make sure we upgrade by early next week.

**Comment by herchu** [comment]
Thanks! 

I have also done my own testing locally and it seems to work ok for me... In fact I already implemented what I needed, so I just need to wait for a react-map-gl release (or use a local fork in the meantime).

Of course I am not a developer on this project so I cannot say my tests are remotely close to valid! So I will wait anxiously for your release. Thanks @Pessimistress !

**Comment by herchu** [comment]
The new dependency to `mapbox-gl: "~0.53.0"` in last 4.0.14 release worked with the clusterProperties feature. Thanks for the quick release!
