### ISSUE TITLE
Latest release does not yet contain FullscreenControl

### ISSUE THREAD

**Issue by macobo** [uber/react-map-gl#738]
https://github.com/uber/react-map-gl/pull/696 added a new feature - FullscreenControl.

It seems this feature is not yet available in the latest release from a few days ago. The following snippet prints undefined on 4.0.12 after fresh yarn install for me:

```
import { FullscreenControl } from 'react-map-gl'
console.log(FullscreenControl)
```

**Comment by Pessimistress** [comment]
The new component is scheduled for 4.1.0.

**Comment by macobo** [comment]
Thanks for the update. Looking forward to the release.
