### ISSUE TITLE
Mapbox style event

### ISSUE THREAD

**Issue by deninedeny** [uber/react-map-gl#741]
Hi, i'm kinda new to react-map-gl

I was searching for a method to detect a change of map's style but couldn't find it.

Is there a way to make an event to detect the change of map's style?

like change from street to satellite ,.etc

Thank you

**Comment by Pessimistress** [comment]
You can use `getMap()` to access the underlying Map instance and listen to the [style events](https://docs.mapbox.com/mapbox-gl-js/api/#events).
