### ISSUE TITLE
onViewStateChange or onViewportChange won't work if we provide outer DeckGL a same type event listener

### ISSUE THREAD

**Issue by hijiangtao** [uber/react-map-gl#745]
Problem description: Once I wrap react-map-gl within deck.gl, and give deck.gl a same type event listener, only the outer listener (`DeckGL`) will work. My codes add these methods:

```
return (
    <DeckGL
      width="100%"
      height="100%"
      layers={renderLayers()} // eslint-disable-line
      viewState={viewState}
      onViewStateChange={handleViewStateChange}
      controller={controller}
    >
      {baseMap && (
        <ReactMapGL
          {...viewState}
          onLoad={addControlHandler}
          onInteractionStateChange={interactionState => console.log(interactionState)}
          onViewStateChange={handleViewStateChange}
          onViewportChange={(viewport) => {
            const {zoom} = viewport;
            console.log(zoom)
          }}
          // reuseMaps
          mapStyle="mapbox://styles/mapbox/dark-v9"
          preventStyleDiffing
          mapboxApiAccessToken={MAPBOX_TOKEN}
        />
      )}
      {object && toolTipHandler && toolTipHandler(tooltip)}
    </DeckGL>
);
```

In order to confirm this behavior is not influenced by other logic, I modify one example code in example folder https://github.com/uber/react-map-gl/blob/master/examples/viewport-animation/src/app.js to this https://gist.github.com/hijiangtao/214d4952fb5307cd77d8ad01ddb50829 and get the same problem, which is onViewportChange event will never be fired when I manipulate the map.

And I get one more problem in this example, which is I can't change viewport of `DeckGL` either (with mouse scrolling or panning).

**Comment by ibgreen** [comment]
@hijiangtao What is your use case, i.e. what are you trying to achieve? 

The deck.gl/react-map-gl APIs are designed to work together to ensure perfect synchronization between deck.gl and mapbox rendering, i.e. both will always show the same view state (lng/lat/zoom/pitch etc).

To let the user change the view state, you then need a "controller". You can either choose deck or mapbox to manage this event handling. But having two controllers trying to manage events at the same time will definitely cause problems. 

Can't you just let deck.gl handle the interaction? Why do you need the mapbox callbacks?

**Comment by hijiangtao** [comment]
Well, @ibgreen I can actually handle my interaction with one callback only.

I just found it wired that not both of them will be triggered and thought it might be a bug of react-map-gl, as the document of react-map-gl alone doesn't mention its relation with deck.gl. I may misunderstood it.

But for the later example code, is there something I wrote wrong cause I couldn't get map viewstate changed with mouse manipulations? Even if I annotate one of the event handlers (deck.gl or react-map-gl).

Thanks.

**Comment by ibgreen** [comment]
I see your point. I don't think we have ever tested using controllers in both deck and react-map-gl. It is not designed to work and I certainly wouldn't expect it to work. Exactly how it fails would require some debugging. But since it is not a supported use case, I am not sure it is worth the effort.

If you feel some documentation would have helped you to avoid going down this path (apologies for that), you are more than welcome to put up a PR.

**Comment by Pessimistress** [comment]
> the document of react-map-gl alone doesn't mention its relation with deck.gl

react-map-gl _**works with**_ deck.gl, but is not _**made for**_ deck.gl. It is a standalone library. deck.gl is not required in any of the react-map-gl core use cases. On the other hand, deck.gl's documentation mentions react-map-gl extensively because this is its recommended solution for base map.

All of deck.gl's examples and documentations use `StaticMap` instead of `InteractiveMap` (the default export) for base map. We do not recommend nor test the scenario where there are two nested controllers.

We make an effort to match the controller behaviors between the two but there are discrepancies. If you need a feature that is only available to the react-map-gl controller, file an issue in the deck.gl repo so we can fix it.

**Comment by hijiangtao** [comment]
@ibgreen Thanks for replying, I think I may need to make my description more clear. The situation is even if I put only one controller (`onViewStateChange` method in my codes), the map still seems not work with mouse manipulations.

I create a more concrete demo with sandbox, you can preview it online https://codesandbox.io/embed/52kqj8k88k?fontsize=14

Thanks.

**Comment by hijiangtao** [comment]
@Pessimistress I think I may misunderstood the internal designing of react-map-gl, and one controller is good enough in handling my situations.

> All of deck.gl's examples and documentations use `StaticMap` instead of `InteractiveMap` (the default export) for base map.

The things here I want is to listen the change of map zooms, and I think I can use `StaticMap` instead, I compare the new viewState and previous one manually currently, and decide whether to do additional logic. 

One more words, `onInteractionStateChange` property is not supported in both `StaticMap` or `deck.gl`, so that's why I use default export of react-map-gl to create this demo. I think if this is supported in `deck.gl` (it's not recommend to support it in `StaticMap` since the documents said it's a minimum version of reat-map-gl) since deck.gl already provides the `interactionState` property in the event handler (but not all changes can be reflected in this object), I can handle such things in a more elegant way. 

The issue I opened in deck.gl https://github.com/uber/deck.gl/issues/2726#issuecomment-468012562

Thanks.

**Comment by hijiangtao** [comment]
I think I'm still troubled by the problem, should I open another issue with a more appropriate topic (https://github.com/uber/react-map-gl/issues/745#issuecomment-468110272)? :-(

**Comment by Pessimistress** [comment]
As explained, this is not an issue of react-map-gl. deck.gl conversations should happen in its own repo.

**Comment by hijiangtao** [comment]
@Pessimistress I think you may misunderstood my thoughts. I replied with two comments, one is about the behavior (conversation with you), one is about the unexpected behavior of example code (conversation with @ibgreen ). 

And I implement demo with codesandbox but didn't get response, so I think the later one isn't solved yet.

On the other hand, the codes used in demo is from https://github.com/uber/react-map-gl/blob/master/examples/viewport-animation/src/app.js , which belongs to react-map-gl repo.
