### ISSUE TITLE
Marker in StaticMap  shows error upon update from 4.0.10 to 4.0.13

### ISSUE THREAD

**Issue by davalapar** [uber/react-map-gl#747]
Curious about this, happened as I updated from

```
    "react-map-gl": "^4.0.10",
    "mapbox-gl": "^0.53.0",
```

to

```
    "react-map-gl": "^4.0.13",
    "mapbox-gl": "^0.53.1",
```

and the following code now shows error:

```js
      <StaticMap
        width={400}
        height={400}
        latitude={14.6571755}
        longitude={121.0195416}
        zoom={16}
        mapboxApiAccessToken="tokengoeshere"
      >
        <Marker latitude={14.6571755} longitude={121.0195416} zoom={16}>
          <Typography variant="overline">
            <Place color="primary" style={{ fontSize: '16px' }}/>
            <strong>
              Main Office
            </strong>
          </Typography>
        </Marker>
      </StaticMap>
```

When I remove the `<Marker>` component it renders gracefully as it should. I've checked the docs and pretty sure I'm not missing something, right? 

Reference images:
- <img src="https://i.imgur.com/ZYpE3u9.png" />
- <img src="https://i.imgur.com/ZjK42Aa.png" />

**Comment by xintongxia** [comment]
@davalapar 

Thanks for reporting this. It is a bug on our end.

**Comment by Pessimistress** [comment]
Fix is published in 4.0.14

**Comment by davalapar** [comment]
That's gangsta, thank you :100:

**Comment by krzochalski** [comment]
I've experienced the same issue with 5.2.9
