### ISSUE TITLE
[GeolocateControl]: How to get `markerPosition`?

### ISSUE THREAD

**Issue by MunifTanjim** [uber/react-map-gl#759]
The `GeolocateControl` component can update and track the user's position. But I also need to perform some operation with it's data.

Is there any way to get access to the `GeolocateControl` component's `this.state.markerPosition`?

**Comment by xintongxia** [comment]
Do you want to manipulate the `markerPosition` or just want read only? We could potentially open up a callback when the `markerPosition` updated.

**Comment by MunifTanjim** [comment]
> Do you want to manipulate the markerPosition or just want read only?

Read-only.

> We could potentially open up a callback when the markerPosition updated.

I've opened #761 with some enhancement for this component (including what you suggested). It would be really helpful if you could review it. Thanks...
