### ISSUE TITLE
[GeolocateControl]: styling bug

### ISSUE THREAD

**Issue by MunifTanjim** [uber/react-map-gl#760]
The example given in [/docs/components/geolocate-control.md](https://github.com/uber/react-map-gl/blob/2571193be1a76d76a6de0e8da67b9f128428da8e/docs/components/geolocate-control.md) doesn't work

```jsx
<div style={{ position: "absolute", right: 0 }}>
  <GeolocateControl 
    positionOptions={{enableHighAccuracy: true}}
    trackUserLocation={true}
    onViewportChange={this._updateViewport}
  />
</div>
```

The problem is that, `div.mapboxgl-marker.mapboxgl-user-location-dot` (with absolute position) is rendered inside `div` (with absolute position) > `div.mapboxgl-ctrl.mapboxgl-ctrl-group`

The [example on demo site](https://uber.github.io/react-map-gl/#/Examples/locate-user) works because the container `div` has style `left: 0`.

If you use `right: 0` style, the blue location dot's position gets messed up.

---

_This might help:_
- _https://stackoverflow.com/a/5928069/4456924_

**Comment by xintongxia** [comment]
Thanks for reporting this issue.
