### ISSUE TITLE
How to get Longitude and Latitude from MapController events?

### ISSUE THREAD

**Issue by hip1310** [uber/react-map-gl#762]
Hi All,
First of all, thanks for this great package. The map works really well. Currently I am using heatmap following the heatmap example.

Now, I want to filter data based on selected portion on the map. I implemented panstart, panmove and panend events. I am able to get x and y co-ordinates from the event, but in my case to filter the data, I have to know longitude and latitude. I printed out event object, but couldn't find latitude and longitude in there.

Can anyone please help me on that?

**Comment by MunifTanjim** [comment]
For which point do you want the `longitude` and `latitude` for?

**Comment by hip1310** [comment]
@MunifTanjim I need longitude and latitude for the point when I start pan (panstart event), and end pan (panend event).

**Comment by MunifTanjim** [comment]
You didn't include your implementation. But here's one approach that can be used:

```js
import React from 'react'
import { BaseControl } from 'react-map-gl'

class CustomControl extends BaseControl {
  toCoords = ({x,y}) => {
    const [longitude, latitude] = this._context.viewport.unproject([x,y])
    return { longitude, latitude }
  }

  _render() {
    return null
  }
}

export default CustomControl
```

You can use `this.Coords` function in this component to get co-ordinates from point.

**Comment by hip1310** [comment]
@MunifTanjim  Thanks!
I am using Custom MapController that extends MapCotroller to handle events, if that matters to get longitude and latitude.

`
import { MapController } from 'react-map-gl'

export default class CustomMapController extends MapController {

  constructor(mode, handlePanStart, handlePanMove, handlePanEnd, handlePanMoveSpatialFilter, handleClick, handleCloseSpatialFilter) {
    super()
    this.mode = mode
    this.onPanStart = handlePanStart
    this.onPanEnd = handlePanEnd
    this.onPanMove = handlePanMove
    this.onClick = handleClick
    this.onPanMoveSpatialFilter = handlePanMoveSpatialFilter
    this.onCloseSpatialFilter = handleCloseSpatialFilter
    this.events = ['click', 'mousemove', 'dblclick']

    this.setMode = (mode) => {
      // if (this.mode !== mode) {
      //     console.log(`map controls switching to mode: ${mode}`)
      // }
      this.mode = mode
    }

    this.handleEvent = (event) => {
      if (this.mode === 'DRAWINGCROSSSECTION') {
        if (event.type === 'panstart') {
          this.onPanStart(event)
        } else if (event.type === 'panend') {
          this.onPanEnd(event)
        } else if (event.type === 'panmove') {
          this.onPanMove(event)
        }
      } else if (this.mode === 'DRAWINGSPATIALFILTER') {
        if (event.type === 'mousemove') {
          this.onPanMoveSpatialFilter(event)
        } else if (event.type === 'click') {
          this.onClick(event)
        } else if (event.type === 'dblclick') {
          this.onCloseSpatialFilter(event)
        }
      } else {
        return super.handleEvent(event)
      }
    }
  }
}
`
I tried using WebMercatorViewport from deck.gl, as I am already using it to draw lines, But it's giving me wrong latitude and longitude.

**Comment by MunifTanjim** [comment]
> I tried using WebMercatorViewport from deck.gl, as I am already using it to draw lines, But it's giving me wrong latitude and longitude.

I can't help with that, because without seeing your codes I can't guess why you are getting wrong values. Try using alternative methods.

**Comment by Pessimistress** [comment]
@hip1310 Did @MunifTanjim's tips help?

I can see it being useful to add a `MapController` method that does the projection for you.

**Comment by hip1310** [comment]
@Pessimistress  Yes, @MunifTanjim 's tips helped. Thanks for asking.

@MunifTanjim  Thanks for the suggestion.
