### ISSUE TITLE
"closeOnClick" prop of Popup doesn't seem to close when map is clicked. 

### ISSUE THREAD

**Issue by zifahm** [uber/react-map-gl#763]
The "closeOnClick" prop of Popup doesn't seem to close when map is clicked, unless if we click on the Popup itself. 
If the popup is clicked on, it closes with no issue but if the surrounding map is clicked it doesn't close.
The intended behaviour should be, if the popup is clicked nothing should happen but if the surrounding map is clicked it should get closed.

Or am i missing something?

**Comment by Pessimistress** [comment]
This is kind of by design - or rather, nobody ever asked for it. I guess both use cases exist. You can always listen to the `onClick` event of the map and close any open popup from there.
