### ISSUE TITLE
Maximum update depth exceeded

### ISSUE THREAD

**Issue by Blooshaanster** [uber/react-map-gl#773]
Hi There,

I'm trying to update the viewport state with lat/lng props received from a geocoder component. But attempting to update state results in the following error. 

'Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.'

**Comment by xintongxia** [comment]
> 'Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.'

Did you call `setState` inside these react lifecycle functions `ComponentWillUpdate or componentDidUpdate`?

**Comment by Blooshaanster** [comment]
No. I'm directly calling it from inside the render method. When the props are passed from geo coding component.

**Comment by xintongxia** [comment]
Are you saying you call `setState` inside `render`? 

If so, that would cause infinite loop of updating react components.

If not, could you post your code here?

**Comment by Blooshaanster** [comment]
I'm actually setting it in a callback function in render() but seem to get
the error. Sorry if it's a silly question but can you tell me what's the
safe way to update state based props(received from geo coder)

**Comment by Blooshaanster** [comment]
Was able to solve this by moving up the viewport to parent component state. Gets updated in 2 ways.
1. Set viewport state from parent geocoder component and pass the state down to map as props
2. Call setViewport prop function to update parent viewport state on onViewportChanged Callback

**Comment by chriszrc** [comment]
I got this error when using a custom MapController, but I forgot to create a new instance for each map I had on the page 🤦‍♂️
