### ISSUE TITLE
Safari fails to show map on fullscreen

### ISSUE THREAD

**Issue by ilvez** [uber/react-map-gl#774]
Latest MacOS (10.14.4) Safari (12.1) fails to render fullscreen properly. No errors visible on Javascript console.

Currently can provide you 2 screenshots.

1. Before clicking fullscreen button ![Before](https://i.ibb.co/vJkMrk5/Screenshot-2019-04-18-at-15-00-01-cropped.png)
2. In Fullscreen ![After](https://i.ibb.co/xgZWwTQ/Screenshot-2019-04-18-at-15-01-44.png)

Does not repro on Chrome, Firefox or Edge.

**Comment by Pessimistress** [comment]
I cannot reproduce this (MacOS 10.14.3 + Safari 12.0). Does Mapbox's original [example](https://docs.mapbox.com/mapbox-gl-js/example/fullscreen/) work for you?

**Comment by sandersiim** [comment]
I'm answering for @ilvez, the Mapbox and react-map-gl examples do indeed work as expected. We'll try to track down minimal code example that reproduces the problem.

**Comment by sandersiim** [comment]
Turns out on Safari it was necessary to explicitly add fullscreen styling to the container div that we were showing on fullscreen like this:
`div:fullscreen {
  width: 100vw; 
  height: 100vh;
}`

That solved the problem for us.

**Comment by ilvez** [comment]
Thanks for leading into @Pessimistress for pointing to right direction.
