### ISSUE TITLE
BUG: Version 4.1.2 breaks IE / 4.1.1 still works on IE  

### ISSUE THREAD

**Issue by MoritzGruber** [uber/react-map-gl#787]
I am using Internet Explorer 11 on Virtual box 

This happends after I use FlyToInterpolator in the InteractiveMap and also using WebMercatorViewport.fitBounds from viewport-mercator-projectand 

4.1.1 ist still working with my codebase, 
4.1.2 is causing that error my codebase

**Error: Function expected**

https://docs.microsoft.com/en-us/scripting/javascript/misc/function-expected

For testing:
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by tilgovi** [comment]
This was an upstream error (mapbox/mapbox-gl-js#8139) that was fixed in Mapbox GL 0.54.0. Upgrading to react-map-gl 4.1.5 or greater should fix the issue for you.
