### ISSUE TITLE
GeolocateControl Warning: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by massivelines** [uber/react-map-gl#788]
This warning shows up when using GeolocateControl. 
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `Context.Consumer`. See https://fb.me/react-warning-keys for more information.
    in div (created by Context.Consumer)
    in GeolocateControl (at Map.js:44)
    in div (created by Context.Consumer)
    in div (created by AutoSizer)
    in AutoSizer (created by StaticMap)
    in div (created by StaticMap)
    in StaticMap (created by InteractiveMap)
    in div (created by InteractiveMap)
    in InteractiveMap (at Map.js:39)

It even shows up on the examples [Locate User](https://github.com/uber/react-map-gl/tree/master/examples/locate-user)

**Comment by xintongxia** [comment]
Should be fixed in version 4.1.4.
