### ISSUE TITLE
Map doesn't display when using mapStyle

### ISSUE THREAD

**Issue by amanshu-kataria** [uber/react-map-gl#791]
I'm trying to pin multiple points (10,000+) on map. I used markers but then the map doesn't responds because of huge data. So, I tried using it using `geoJson`. I can now see the points but map is not rendering. Below is the image for this issue.
![Screenshot 2019-05-22 at 12 39 21 PM](https://user-images.githubusercontent.com/13014093/58157658-73b9b600-7c96-11e9-9c87-ca6dcbd3009d.png)

Here's the code:

```
class App extends PureComponent {
  componentDidMount() {
    this.data = [];
    this.coordinates = [];
  }

  state = {
    showMap: false,
    data: [],
    coordinates: [],
    viewport: {
      width: 600,
      height: 600,
      latitude: 12.92415,
      longitude: 77.67229,
      zoom: 8
    }
  };

  setData = () => {
    this.setState({
      showMap: true,
      data: this.data,
      coordinates: this.coordinates
    });
  };

  getMapStyle = () => {
    return {
      version: 8,
      sources: {
        points: {
          type: 'geojson',
          data: {
            type: 'FeatureCollection',
            features: [
              {
                type: 'Feature',
                properties: {},
                geometry: {
                  type: 'MultiPoint',
                  coordinates: this.state.coordinates
                }
              }
            ]
          }
        }
      },
      layers: [
        {
          id: 'my-layer',
          type: 'circle',
          source: 'points',
          paint: {
            'circle-color': '#fbb03b',
            'circle-radius': 4
          }
        }
      ]
    };
  };

  render() {
    return (
      <div className="app">
        {this.state.showMap ? (
          <ReactMapGL
            {...this.state.viewport}
            mapboxApiAccessToken={MY_MAPBOX_API_TOKEN}
            onViewportChange={viewport => this.setState({ viewport })}
            mapStyle={this.getMapStyle()}
          />
        ) : (
          <CsvUploader
            onComplete={this.setData}
            onEachStep={data => {
              this.data.push(data);
              this.coordinates.push([data.long, data.lat]);
            }}
          />
        )}
      </div>
    );
  }
}
```
What's happening is I'm uploading a CSV file and from `CsvUploader` and storing it in state and using those coordinates in `getMapStyle`. I also want to know if this is the correct way to point multiple points (10,000+).

**Comment by xintongxia** [comment]
With this amount of data, it is difficult to interact with the map.

You can use our another framework `deck.gl`, WebGL based framework which can handle larger dataset performantly, [`ScatterplotLayer`](https://deck.gl/#/documentation/deckgl-api-reference/layers/scatterplot-layer) could match your use case. There is also an [example](https://github.com/uber/react-map-gl/blob/master/examples/deckgl-overlay/src/app.js) in `react-map-gl`.

**Comment by Pessimistress** [comment]
@xintongxia It is fine using a mapbox layer to render large geojsons.

@amanshu-kataria Your map style does not include sources and layers for the base map. It would look something like https://github.com/uber/react-map-gl/blob/master/examples/map-style-basic-v8.json

**Comment by amanshu-kataria** [comment]
@Pessimistress thanks. Issue Solved.
