### ISSUE TITLE
Use HTTPS on interactive docs

### ISSUE THREAD

**Issue by iamvdo** [uber/react-map-gl#80]
There are mixed content errors in Interactive docs, because of HTTP AJAX calls on tiles providers.

> Mixed Content: The page at 'https://uber.github.io/react-map-gl/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://tile.stamen.com/toner/12/656/1582.png'. This request has been blocked; the content must be served over HTTPS.

**Comment by winkler1** [comment]
Yes -- means the examples don't work. Really great docs & examples otherwise!

![image](https://cloud.githubusercontent.com/assets/883896/15290024/dfae9e64-1b43-11e6-82b0-3cc41bf452e2.png)

**Comment by kachkaev** [comment]
This is still the case. When you are on https://uber.github.io/, not http://uber.github.io/, the tiles from `stamen.com` do not load. 

Looks like something is also wrong with the SSL cert for stamen maps:
https://tile.stamen.com/toner/12/653/1582.png

![stamen maps privacy error](https://cloud.githubusercontent.com/assets/608862/16655705/94b9b374-4453-11e6-85bc-1a3e70b15f17.png)

How about just switching the map style into something more reliable?

**Comment by wandergis** [comment]
The url i think can change to `//tile.stamen.com/toner/z/x/y.png`

**Comment by dnordberg** [comment]
+1 haven't been able to try the maps

**Comment by Apercu** [comment]
Resolved
