### ISSUE TITLE
double tap zooming on mobile is very unreliable

### ISSUE THREAD

**Issue by omfgitsjack** [uber/react-map-gl#806]
Double tapping on a mobile device doesn't seem to work reliably. 

You can compare this between [react-map-gl](https://uber.github.io/react-map-gl/#/Examples/dynamic-styling) and [map-box-gl](https://docs.mapbox.com/mapbox-gl-js/example/simple-map/).

Mapbox gl never fails to capture the double tap, whereas react-map-gl appears to move the map a tiny amount.

**Comment by Pessimistress** [comment]
@omfgitsjack This should work better in the latest release.
