### ISSUE TITLE
Feature icon does not show up. 

### ISSUE THREAD

**Issue by danksky** [uber/react-map-gl#810]
The **marker-15** feature icon is not showing up. 

```
import React, { Component } from 'react';
import ReactMapboxGl, { Layer, Feature, Marker } from "react-mapbox-gl";

import '../stylesheets/StoryList.css'

const Map = ReactMapboxGl({
  accessToken: "helloaccesstoken"
});


class StoryList extends Component {

	render() {
		return (
			<div className='StoryList' >
				<div className='story-list-map' >
					<Map							
						style="mapbox://styles/mapbox/streets-v9"
						containerStyle={{
							height: `100%`,
							width: `100%`
						}}>
						<Layer
							type="symbol"
							id="marker"
							layout={{ "icon-image": "marker-15" }}>
							<Feature coordinates={[51.511459, -0.245408]} />
						</Layer>
					</Map>
				</div>
			</div>
		);
	}
}
```
<img width="472" alt="Screen Shot 2019-06-03 at 2 59 34 PM" src="https://user-images.githubusercontent.com/10901068/58837395-482cb900-8610-11e9-8839-d86b59c1ead4.png">

This is the only potentially relevant warning:
`Line 72:  Style prop value must be an object react/style-prop-object`

**Comment by xintongxia** [comment]
> import ReactMapboxGl, { Layer, Feature, Marker } from "react-mapbox-gl";

`react-mapbox-gl` is a different [library](https://github.com/alex3165/react-mapbox-gl).
