### ISSUE TITLE
Popover tip position is incorrect

### ISSUE THREAD

**Issue by brobertsUPS** [uber/react-map-gl#817]
The tip of the popover is in the wrong position by default.

EX:
<img width="92" alt="Screen Shot 2019-06-05 at 2 25 34 PM" src="https://user-images.githubusercontent.com/5407471/58991826-0fbae580-879e-11e9-8d2e-bbd2f293b2e9.png">

Reproducible demo: https://codesandbox.io/s/reactmapgl-popover-offset-broken-in-415-njxg8

This bug appears to be have been introduced in `4.1.5`. If I change the version to `4.1.4` in code sandbox, the position goes back to normal:

<img width="78" alt="Screen Shot 2019-06-05 at 2 32 32 PM" src="https://user-images.githubusercontent.com/5407471/58992203-fd8d7700-879e-11e9-88b6-d19f06ca233e.png">

**Comment by Pessimistress** [comment]
This is broken due to a change in the latest mapbox-gl stylesheet.

**Comment by xintongxia** [comment]
Published a patch with the fix in v4.1.7.

**Comment by brobertsUPS** [comment]
Thanks @Pessimistress & @xintongxia!
