### ISSUE TITLE
Disabling scrollZoom on StaticMap with mapOptions doesn't have any effect

### ISSUE THREAD

**Issue by mathieudelvaux** [uber/react-map-gl#824]
Hi all 👋

I've been using the StaticMap component for one of my projects, but recently I had to disable all scrolling interactions.
I realize it's not supposed to be exposed directly through props, but `mapOptions` should allow it, right?
I'm currently using:
```
<StaticMap
  reuseMaps
  mapStyle={mapStyle}
  preventStyleDiffing
  mapOptions={{ scrollZoom: false }}
/>
```
but it doesn't work at the moment.
Is this not supported at all for `StaticMap`?

For reference, I'm using `react-map-gl 4.1.2`

**Comment by xintongxia** [comment]
@mathieudelvaux @ranzen 

`StaticMap` component is completely not interactive. 

`InteractiveMap` is the interactive version, however react-map-gl does not listen to Mapbox events, instead it has its own event manager [mjolnir.js](https://github.com/uber-web/mjolnir.js). You can disable by set the option [`scrollZoom`](https://github.com/uber/react-map-gl/blob/master/docs/components/interactive-map.md#scrollzoom-bool-default-true) to false.
