### ISSUE TITLE
How to add custom sources/layers on top of template styles?

### ISSUE THREAD

**Issue by nicotalus** [uber/react-map-gl#825]
I'm unable to overlay my custom sources/layers on top of a predefined style template. When passing the style prop to the map component I am able to add either the template or my custom sources/layers, but not both at once. Here's a quick example:
```
mapStyle='mapbox://styles/mapbox/streets-v9'
mapStyle={mapStyle}
```
Individually either will work when I comment out the other. Is there a way to easily extend the mapbox style with my own sources/layers? Below is the full component:

```
const Map = () => {
  const [viewport, setViewport] = React.useState({
    width: '100%',
    height: '100%',
    latitude: 37.7577,
    longitude: -122.4376,
    zoom: 8
  })

  const mapStyle = {
    version: 8,
    sources: {
      states: {
        type: 'geojson',
        data: 'https://docs.mapbox.com/mapbox-gl-js/assets/us_states.geojson'
      }
    },
    layers: [
      {
        id: 'states-fill',
        type: 'fill',
        source: 'states',
        paint: {
          'fill-color': '#627BC1'
        }
      }
    ]
  }

  return (
    <ReactMapGL
      mapboxApiAccessToken={TOKEN}

      /* Here's the problem */
      mapStyle='mapbox://styles/mapbox/streets-v9'
      // mapStyle={mapStyle}

      {...viewport}
      onViewportChange={v => setViewport(v)}
    />
  )
}
```

**Comment by Gadda27** [comment]
This sounds a lot like this [issue](https://github.com/uber/react-map-gl/issues/791).

**Comment by marek-sed** [comment]
You need to merge your mapStyle with mapboxes mapStyle.
either save the mapbox mapStyle file in your or write a listener component.

locate it as child of ReactMapGl to get access to context, after the styles are loaded you merge
on to mapbox style whatever you want. See examples for that.

```
import { BaseControl } from 'react-map-gl';
export default class StyleListener extends BaseControl {
  state = this.props.initialState;

  updateStyle = (evt) => {
    const { onChange } = this.props;
    onChange(evt.style.stylesheet);
  };

  componentDidMount() {
    // eslint-disable-next-line
    this._context.map.on('style.load', this.updateStyle);
  }

  componentWillUnmount() {
    // eslint-disable-next-line
    this._context.map.off('style.load', this.updateStyle);
  }

  /* eslint-disable */
  _render() {
    return null;
  }
```

**Comment by jovanialferez** [comment]
1. do as they did in the example here -- https://github.com/uber/react-map-gl/tree/master/examples/geojson

2. use mapbox studio, create a new style out of your preferred style (in your case `streets`), you may leave everything as is, then go to "Share" and download it. 

3. grab the content of `style.json` from that downloaded file above, and replace the content of this file `map-style-basic-v8.json` from the example in #1 above.

HTH.

**Comment by Pessimistress** [comment]
The 5.1.x release added support for `<Source>` and `<Layer>` React components.
