### ISSUE TITLE
getMap() is undefined - GEOJSON lines

### ISSUE THREAD

**Issue by stephanie-saretsky** [uber/react-map-gl#829]
Hello,

I am trying to create a GEOJSON line using the results of a shapes.txt file on my React Map GL. However, I'm having trouble using the getMap() method to let me access the Mapbox API directly.  This is my code -

`import React, { Component } from "react";
import ReactMapGL, { Marker, Popup } from "react-map-gl";
import { connect } from "react-redux";
import StopInfo from "./StopInfo.jsx";

class UnconnectedMap extends Component {
  state = {
    viewport: {
      height: "100vh",
      width: "100vw",
      latitude: 40.7081,
      longitude: -73.9571,
      zoom: 12
    },
    popupInfo: null,
  };

  renderShapes = s => {
    let map = this.ReactMapGL.getMap();
    map.on("load", () => {
      map.addLayer({
        id: "route",
        type: "line",
        source: {
          type: "geojson",
          data: s
        },
        layout: {
          "line-join": "round",
          "line-cap": "round"
        },
        paint: {
          "line-color": "#888",
          "line-width": 8
        }
      });
    });
  };
`

**Comment by Pessimistress** [comment]
@stephanie-saretsky it's hard to tell what `this.ReactMapGL` is from your code. Generally speaking you need to create a [ref](https://reactjs.org/docs/refs-and-the-dom.html) during render and then access it after the component is mounted. You can see it in [this example](https://github.com/uber/react-map-gl/blob/master/examples/heatmap/src/app.js#L158).

**Comment by marek-sed** [comment]
@stephanie-saretsky there is callback onLoad on React-Map-Gl component you do not need to subscribe to it.

in case you are using version of react with hooks. Then it is super easy.
```
function ElMapa(props) {
   const [isLoaded, setIsLoaded] .= useState(false)
   const [mapStyles, setMapStyles] = useState(mapbox://styles/mapbox/streets-v9)
   const [viewport, setViewport] = useState(props.defaultViewport)
   
   const mapRef = useRef(null)
   // this runs after mapRef was mounted
   useLayoutEffect(() => {
       const map = mapRef.current.getMap()
       if(isLoaded) { /* map.on here to whatever you want, I am handling style toggle from here */}
       
      return () => {/* map.off everything */}
   })

   function handleOnLoad(evt) {
     setMapStyles(evt.target.style.stylesheet)
     setIsLoaded(true)
   }
   return <ReactMapGl  onLoad={handleOnLoad} onViewportChange={setViewport} {...viewport } />
}
```

**Comment by mayteio** [comment]
Alternatively, less code:

```
export default function Map(){
  const mapRef = useRef();
  const onLoad = () => console.log('mapRef.current is ready for use');
  return <InteractiveMap ref={ref => mapRef.current = ref && ref.getMap()} onLoad={onLoad} />
}
```

**Comment by stephanie-saretsky** [comment]
Thank you so much!

**Comment by CSFlorin** [comment]
Thanks @mayteio and @marek-sed ! To note, this does not work with `MapGL`, only `ReactMapGL`. I wonder what the difference is between the two?
