### ISSUE TITLE
Reversing lngLat in fitBounds

### ISSUE THREAD

**Issue by daviestar** [uber/react-map-gl#83]
Is there a reason why you are accepting latLng bounds instead of lngLat bounds in `fitBounds`? https://github.com/uber/react-map-gl/blob/es6/src/fit-bounds.js#L28

I am confused as to why its breaking the convention of lngLat coordinates.

My use case:
```javascript
function extent(markers) {
  let extent = [[-Infinity, -Infinity], [Infinity, Infinity]];
  for(let lngLat of markers) {
    if(lngLat[0] > extent[0][0]) {
      extent[0][0] = lngLat[0];
    } else if(lngLat[0] < extent[1][0]) {
      extent[1][0] = lngLat[0];
    }

    if(lngLat[1] > extent[0][1]) {
      extent[0][1] = lngLat[1];
    } else if(lngLat[1] < extent[1][1]) {
      extent[1][1] = lngLat[1];
    }
  }

  // https://github.com/uber/react-map-gl/issues/83
  extent = [extent[0].reverse(), extent[1].reverse()];

  return extent;
};

const MAP_ONLOAD = MapGL.fitBounds(width, height, extent(store.markers), {padding: 50});
```
Thanks

**Comment by ibgreen** [comment]
@daviestar Good point. We are going to make a new version of fitBounds that supports perspective mode, we will fix this in the new API and deprecate this method. Given that a new method is coming, for backwards compatibility I prefer not to change the current method.
