### ISSUE TITLE
FlyToInterpolator animation

### ISSUE THREAD

**Issue by marek-sed** [uber/react-map-gl#830]
Hi, just started using this library and loving it great idea extracting mapStyle out of mapbox-gl-js 👍. But ran into an issue.

- **Current Behavior**
transitionDuration is constant, if I am 100km from target, the animation place for same time as if I am 5km away.

- **Expected Behavior**
same as mapbox.flyTo which shortens the animation the closer you are to target. 

https://github.com/mapbox/mapbox-gl-js/blob/9d5049e774d0b4cb1f82e2bcc9fbc1c1df901251/src/ui/camera.js#L942

looking at the flyTo algorithm in mapBox, they are calculating distance to fly and camera speed to make a transition snappy at various distances

**Comment by marek-sed** [comment]
nevermind transitionEasing does the trick :)

**Comment by Pessimistress** [comment]
@1chandu is there a way to expose the time needed for the flyTo animation?

**Comment by 1chandu** [comment]
`InteractiveMap`'s `transitionDuration` prop defines transition time, documentation [here](https://uber.github.io/react-map-gl/#/Documentation/api-reference/interactive-map).

Regarding the pace of transition, it should feel slower at `source` and `target` positions, but faster in between (since it will be zoomed out). 

mapbox API has more options (like curve, rho, speed etc, and duration can be calculated based on these parameters), @marek-sed can you tweek `transitionDuration` to see if that servers your needs?

**Comment by Pessimistress** [comment]
I think it's possible for us to support something like

```js
transitionDuration: 'auto',
transitionInterpolator: new FlyToInterpolater({speed})
```

**Comment by marek-sed** [comment]
Incase if someone wants more native behavior.

easing is different, this is from mapbox-gl-js code base
```
function bezierFn(p1x, p1y, p2x, p2y) {
  const bezier = new UnitBezier(p1x, p1y, p2x, p2y);
  return t => bezier.solve(t);
}

export const easing = bezierFn(0.25, 0.1, 0.25, 1);
```

to calculate time I am doing some next level mathematics.
```
function deg2rad(deg) {
  return deg * (Math.PI / 180);
}

/* eslint-disable */
function harvesine([lon1, lat1], [lon2, lat2]) {
  const R = 6371; // Radius of the earth in km
  const dLat = deg2rad(lat2 - lat1); // deg2rad below
  const dLon = deg2rad(lon2 - lon1);
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) * Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  const d = R * c; // Distance in km
  return d;
}
/* eslint-enable */

export function calculateDuration(viewport, lon, lat) {
  // some next level mathematics feel free to improve :)
  const distance = harvesine([viewport.longitude, viewport.latitude], [lon, lat]);
  if (distance > 500) {
    return 4000;
  }
  if (distance > 100) {
    return 3000;
  }
  if (distance > 40) {
    return 2000;
  }
  if (distance > 8) {
    return 1500;
  }
  if (distance > 2) {
    return 1000;
  }
  return 500;
}
```

**Comment by mayteio** [comment]
Possibly too simplistic, but could you just calculate time based on a distance multiplier?

```
import calculateDistance from "@turf/distance";

export const getTransitionDuration = (source, target, multiplier) =>
  calculateDistance(source, target) * multiplier

...

setViewState(vs => ({
  ...nextViewState,
  transitionDuration: calculateDistance(vs, nextViewState);
}))
```

**Comment by marek-sed** [comment]
@mayteio just to clarify
1. you are suggesting instead of using harvesine I import a library that uses harvesine.
2. and figuring the multiplier is the really hard part, so thats why I have `if else` block there.
// feel free to open link to mapbox-gl-js how they are doing it.

**Comment by mayteio** [comment]
You can BYO haversine/distance if you like, I just try not to re-invent the wheel. 

I see - it's tricky to extract that functionality because it's all encapsulated in the one `flyTo` method. It's a hell of a function. Since you already have the distance though, you could look into scaling speed based on distance, possibly with interpolation. It's something you'll have to fiddle with to 'feel right' though. Best of luck.

**Comment by marek-sed** [comment]
Do not want to be harsh or impolite, I appreciatte your enthusiasm and believe it comes from a good place. Take it as feedback.

But to summarize what information you provided in last 2 comments contain.
You stated what I already know and my code is doing and on part which I gave up is too difficult that is is difficult and best of luck. There is no value for people struggling with this in your comments.

**Comment by Pessimistress** [comment]
@marek-sed Please be courteous to fellow community members. @mayteio is only trying to help.

We will work on adding a constant speed option to the `FlyToInterpolator`.

**Comment by marek-sed** [comment]
Edited my responses so it makes sense for readers. :/

**Comment by mayteio** [comment]
@marek-sed just suggested turf to reduce the surface area of what you're trying to achieve. Unfortunately I wasn't able to unpack that flyTo function and I can see why the multiplier wouldn't work in all cases. Perhaps a ramp or interpolator from D3 might help? Hope you figure it out 🙂

**Comment by 1chandu** [comment]
Work in progress, this issue will be tracked here : #865 , closing.
