### ISSUE TITLE
Error when trying to execute tests: ocular-lint: line 12: jq: command not found

### ISSUE THREAD

**Issue by ReactGirl** [uber/react-map-gl#844]
The following issue is happening when try to run the tests. What I am missing?

command: 

`yarn test`

result: 
/home/alice/Documents/github/react-map-gl/node_modules/.bin/ocular-lint: line 12: jq: command not found

npm ERR! Linux 4.18.0-25-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "lint"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-map-gl@4.0.0-beta.7 lint: `ocular-lint`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-map-gl@4.0.0-beta.7 lint script 'ocular-lint'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-map-gl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ocular-lint
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-map-gl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-map-gl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alice/Documents/github/react-map-gl/npm-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Pessimistress** [comment]
On some Linux distributions you need to install jq: `sudo apt-get install jq`

We mostly work on Mac so the dev scripts are not fully tests on other platforms. /o\

**Comment by ReactGirl** [comment]
Thanks.
For MAC users you might need to do the same by;

`brew install jq`

**Comment by VictorVelarde** [comment]
This same issue happened to me within **deck.gl project**, when executing its tests for the first time. And installing jq also fixed it, so thx!
