### ISSUE TITLE
MapInteraction's _onWheel stops event propagation

### ISSUE THREAD

**Issue by kujon** [uber/react-map-gl#85]
https://github.com/uber/react-map-gl/blob/master/src/map-interactions.react.js#L114

What is the rationale behind this?

**Comment by chrisirhc** [comment]
As in the comments, it looks like the code is loosely based on https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/handler/scroll_zoom.js and there should be no need to do `stopPropagation`
