### ISSUE TITLE
Map does not show up in web-view on Samsung S10 and Android emulator

### ISSUE THREAD

**Issue by derwaldgeist** [uber/react-map-gl#851]
I'm developing an app where the web-view runs inside a Unity application, as a Unity plugin. Everything works fine so far, and the map shows up on my iPhone X and my Google Pixel 3a.

On a friend's Samsung S10, however, only my custom marker appears (showing the user's location), but not the underlying map itself. It's just empty.

I tried to debug stuff, but there are no error messages at all in the Chrome inspector. Everything seems normal, the elements and styles are visible in the elements view as they should. But the map content itself is missing.

What might cause this?

**Comment by derwaldgeist** [comment]
EDIT: The same happens in the Android emulator (Pixel 3 XL). However, if I reload the page (using Chrome's inspector), the map shows up. Same applies to the Galaxy S10 device.

So the problem only occurs on initialisation, when the component is loaded using React router.

**Comment by derwaldgeist** [comment]
EDIT: Just noticed that in fact elements are missing. While `div.mapboxgl-map` is there, its children do not show up, i.e. `div.mapboxgl-canary`, `div.mapboxgl-canvas-container` and `div.mapboxgl-control-container`.

This is how the DOM looks on first startup:

![image](https://user-images.githubusercontent.com/3984535/62005250-d31dc180-b130-11e9-8711-0543811b1cac.png)

This is how the DOM looks after a manual reload:

![image](https://user-images.githubusercontent.com/3984535/62005259-f5afda80-b130-11e9-8d63-e973e2bb62ba.png)

**Comment by Pessimistress** [comment]
The symptom is caused by failing the `StaticMap.supported()` check. If you could put a break point in there, there are two possibilities:

- `mapboxgl` is `null: your bundler does not consider the target a browser. 
- `mapboxgl.supported()` returns `false`: the browser environment is missing something that mapbox-gl depends on.

**Comment by derwaldgeist** [comment]
Thanks for your feedback.

The thing is: the map works perfectly once I reload the page in the Android web view (using the debugger). So I don't think the problem is related to the browser configuration. I will try to set a break-point as you suggested and report back.

**Comment by derwaldgeist** [comment]
I debugged it and found out that sometimes (but not always) `mapboxgl.supported()` returns `false`; Once I reload the page, it returns `true`. Where can I find the code for this function?

**Comment by derwaldgeist** [comment]
Ok, I debugged it and found out that `mapboxgl.supported()` returns `false` due to a failing WebGL check in this line:

https://github.com/mapbox/mapbox-gl-supported/blob/gh-pages/index.js#L152

`canvas.getContext('webgl', attributes)` returns null. Interestingly, this *only* happens if the web view has been loaded, but *not* been displayed to the user yet (on some devices; on others, it works).

Once a page has been displayed (it does not matter which one), `canvas.getContext('webgl', attributes)` returns a valid WebGL context.

I could workaround this problem by setting a timeout in my component that delays rendering of the map. Even a timeout of 0 was sufficient.
