### ISSUE TITLE
Delay when closing a Popup

### ISSUE THREAD

**Issue by bogdancaspar** [uber/react-map-gl#855]
Hi guys,

I've encountered this many times, in multiple projects that I've used react-map-gl and I saw that this also happens on the official example: https://uber.github.io/react-map-gl/#/Examples/markers-popups

Everytime I want to close a popup, I press the close button and there is a delay of approximately 1 second. Any of you encountered this problem, and maybe solved it?

**Comment by vincezun** [comment]
Yes, it has a delay but I dont know what's causing it.

**Comment by Pessimistress** [comment]
This is a bug -- if you are curious, the delay is 300ms, as hammer.js waits to make sure you are not double clicking the button. We should close the popup immediately after any click event.

**Comment by Pessimistress** [comment]
This should be fixed in 4.1.11/5.0.8
