### ISSUE TITLE
Events and expanding upon MapInteractions

### ISSUE THREAD

**Issue by cammanderson** [uber/react-map-gl#86]
Hi Guys, 

I just wanted to know if there is an intention to try and deal with the events that mapbox-gl-js fires internally, or whether there are plans to expose them to subscribers (importantly still in an immutable way). 

I am assuming that MapInteractions and MapGL is structured is to protect the 'map' object from being exposed and potentially mutated. I understand and agree with the principle of this as having played a lot with managing state of mapbox and it can get tricky trying to build an application reusing and managing a lot of map states across layers/states etc. 

There are a couple of requests that have shown up that I believe are pretty important, something that I would like to consider making a contribution towards as they are things that I also need. Those are 'touch' events and 'dblclick' zoom. More broadly though, I start to think about the way to capture representations of other interactions and expose those to the rest of the React application.

Reviewing the interaction around the MapInteractions class, it is currently taking on some of the responsibilities of the Mapbox "handlers". This is confirmed by things like referencing the scroll_zoom handler of mapbox to provide a scroll zoom behaviour in this class. 

The challenge I can see is that the 'handlers' that are involved in mapbox have access to the map to attach themselves to certain events being fired by mapbox. Being able to do this as well will ensure for a consistent behaviour between mapbox and this project.

Considering there is a nice way planned to handle state of the styles configuration, is there a way that we can expose the mapbox 'events' behaviour so we can still protect the mutation of the 'map' object, but allow other classes to access interaction/map events? 

Could an implementation be as simple as providing a MapGL prop function that could receive mapbox events as they are fired? Something simple and predictable obviously, maybe just a function that receives an Event style object with type? Developers could then make choices to handle observing those events.

This could allow the application upwards to handle interactions possible a little cleaner (e.g. click event maybe for the user to indicate a position on the map without it being 2 viewport change events) and also downwards to child elements such as the MapInteractions component that could effectively implement a 'dblclick' zoom behaviour.

There will likely still remain the exposure of further parts of the Mapbox GL JS API in an stateless way in order to use these events fully, but maybe this will see more interactions being achievable by the community quicker.

Hoping that I haven't missed something obvious here. If so, I apologise.

Thanks
Cameron

**Comment by vicapow** [comment]
Hey @cammanderson you touched on several solid points in your comments and I like the proposed approach you've suggested. @ibgreen is now the maintainer of the project and I'd imagine this is something he'd be interested in accepting a PR for. @ibgreen what are your thoughts?

**Comment by ibgreen** [comment]
@cammanderson 
It was a while since I looked at the mapbox code so my comments might be missing the mark:

If mapbox is already firing internal events in the current react-map-gl implementation, it should not break the current design model of react-map-gl to add a callback prop to listen those events. But if they are truly internal events, we would be exposing something that is not guaranteed to be supported when mapbox bumps version...

I'm absolutely open to a PR but at this the proposal is not clear enough to me at this point that I can guarantee that we would accept it. As a start, can you indicate what mapbox APIs you would be using to set up the handlers to help me get on the right track?

FWIW, for any work on this please look at the refactored ES6 code on the dev branch. We just added event handling support for perspective mode in the MapInteractions component on dev. Adding touch and double click support doesn't sound too onerous (especially with existing mapbox source code as a reference), so that could be another approach - it might be easier/quicker to accept a PR for that.

**Comment by cammanderson** [comment]
Thanks @vicapow and @ibgreen for considering this suggestion. 

Mapbox GL JS API offers this as a documented function and encourage the use of it in their examples. They also document all the types of events that are fired to these observers. Here is the API reference for using the 'on' event; https://www.mapbox.com/mapbox-gl-js/api/#Events

I can appreciate a hesitation with calling internal API or non-documented calls - I won't make recommendations about non-documented/private API functions. :-) I can appreciate trying to avoid that!

I will check out the ES6 branch. I appreciate that there is the opportunity for a PR to help out, I will open it to the community to jump in if someone is observing and looking for to make a contribution, but I will also look to develop a PR contribution for your consideration.

Cheers
Cameron

**Comment by cammanderson** [comment]
Hi Guys, 

I haven't forgotten about this. One of the considerations I have at the moment is what would be a nice way of interfacing and adding support. 

In the meantime, I have added a PR to add touch device pan support: https://github.com/uber/react-map-gl/pull/101

It would seem that a props based approach could be handy, as users could add something similar to "onLoaded: React.PropTypes.func". There is a full list of the standard API based events currently supported on mapbox API (there are a few...): https://www.mapbox.com/mapbox-gl-js/api/#Map.event:load

The react-map-gl main MapGL component could subscribe to all props supported methods directly to the Map instance, and then receive those events and chose how to propagate them. 

I am cautious to simply propagate the original event though, as it has a reference to 'target', being the original Map instance. Keeping in mind that we don't want to lose encapsulation to this object, I would propose that we would fire our own events. The API for the event objects and the data that is contained within them are located here; https://www.mapbox.com/mapbox-gl-js/api/#MapMouseEvent. Some events are just DOM events, so those would be safe as they have no access to the Map instance.

Any thoughts on this ahead of developing a PR? I would like to agree on an over-arching approach, likely before developing a PR. 

Thanks
Cam

**Comment by shaojingli** [comment]
Since the event handling part of react-map-gl is under a significant refactoring, I'll close this issue.
