### ISSUE TITLE
React 16.9 deprecated lifecycles

### ISSUE THREAD

**Issue by MoradiDavijani** [uber/react-map-gl#860]
**Version:** 5.0.8

**Problem:**
After updating React to the version 16.9.0 you will see this warning in browser's console:

> Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> * Move data fetching code or side effects to componentDidUpdate.
> * Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: InteractiveMa

**Comment by Pessimistress** [comment]
Published 4.0.12/5.0.9

**Comment by MoradiDavijani** [comment]
@Pessimistress I didn't check exactly why, but it seems that these changes is not in `v5.0.9`.
Changes exist in `master` branch but not in tag `v5.0.9`.

**Comment by Pessimistress** [comment]
Try 5.0.10

**Comment by itsmhuang** [comment]
I'm seeing that this message does not go away even if you are NOT using those lifecycle methods. Is that intentional? I feel they are unnecessary.
