### ISSUE TITLE
Unable to set custom attribution through the mapbox-gl customAttribution prop

### ISSUE THREAD

**Issue by peetjvv** [uber/react-map-gl#862]
**Problem**
We are using a third party map tiles provider as part of our map style and are required to attribute them on the map. The best way to do this would be to add their copyright information to the attributions section, but currently the method implemented for adding custom attributions to the AttributionControl is available in mapbox-gl, but not in react-map-gl.

**Mapbox-GL implementation example code**
This can be done in mapbox-gl by using the following code:
```javascript
let map = new mapboxgl.Map({
  container: "map",
  style: "mapbox://styles/mapbox/streets-v8",
  attributionControl: false
});

map.addControl(
  new mapboxgl.AttributionControl({
    customAttribution:
      '<a href="https://www.digitalglobe.com/">© DigitalGlobe</a>'
  })
);
```

**Proposed solution**
Expose the customAttribution prop implemented in mapbox-gl in [this PR](https://github.com/mapbox/mapbox-gl-js/pull/7033/files) - as part of [this issue](https://github.com/mapbox/mapbox-gl-js/issues/1485) - to allow users to add custom attributions to the AttributionControl.

**Comment by Pessimistress** [comment]
You can use the [mapOptions](https://uber.github.io/react-map-gl/#/Documentation/api-reference/static-map?section=initialization) prop.

**Comment by peetjvv** [comment]
Thanks for the quick response and the amazing tip! I managed to fix my issue like this:

```javascript
<InteractiveMap
    mapOptions={{
        customAttribution: '<a href="https://www.digitalglobe.com/">© DigitalGlobe</a>'
    }}
    {...otherProps}
/>
```

Not a trainsmash, but I have noticed that the `mapOptions` doesn't update when I change the `customAttribution` string in runtime (e.g. on a state change). Might be something worth looking into.

**Comment by Pessimistress** [comment]
It doesn't update because `mapOptions` is passed to the `Map` constructor. If you need to access the `AttributeControl` yourself then you'll need to get the ref of your map and call `ref.getMap().addControl()` like the mapbox-gl example.

**Comment by peetjvv** [comment]
I'm going to close this issue. Thank you for all your help. Definitely learned a lot about how to implement the lesser known mapbox-gl features that aren't part of react-map-gl. This will come in handy in the future.
I came across [this tutorial](https://docs.mapbox.com/mapbox-gl-js/example/map-tiles/) on Mapbox's site which also shows how to add attributions directly onto the source in the map style. Going with their approach as it is the best, neatest possible implementation for my use case.
