### ISSUE TITLE
onViewportChange Warning

### ISSUE THREAD

**Issue by lucdandrel** [uber/react-map-gl#872]
Hello all, 
I'm using the latest version of React-Map-GL (5.0.10), and I've an warning in devtools, from onViexportChange. 

Any idea why ? 

Thanks ! 

<img width="428" alt="Capture d’écran 2019-08-23 à 10 46 14" src="https://user-images.githubusercontent.com/17253963/63579583-4af5d500-c593-11e9-9b3d-19b0a8c5463b.png">

My component : 
![carbon](https://user-images.githubusercontent.com/17253963/63579384-d0c55080-c592-11e9-9bfd-0db55f7aceac.png)

**Comment by lucdandrel** [comment]
I've this error only in dev environnement not in production

**Comment by allenchuang** [comment]
I'm getting the same issue. Seems like `_onViewportChange` is being called on render. Is this expected behavior?

**Comment by mrnguyenpro123** [comment]
Me too. It always calls but viewport the same

**Comment by jlubeck** [comment]
Same here

**Comment by Pessimistress** [comment]
Try 5.1.6
