### ISSUE TITLE
How to detect viewport changes when viewport is changed programmatically

### ISSUE THREAD

**Issue by jarppe** [uber/react-map-gl#878]
I have attached logic to load some features from backend when onViewportChange is called. This works fine when user zoom/pan map.

When I change viewport programmatically by updating the viewport props, the map is moved and zoomed, but onViewportChange is not called.

Is there a way to detect viewport changes when viewport is moved programmatically? Or is there some better way to load features?

I'm having difficulties on loading the features in the same time I update the properties, as the features loading uses the map bounds that I get by `getMap().getBounds()`, but this is updated sometime after the viewport is changed.

**Comment by mayteio** [comment]
Store your viewport in state context and use an effect hook to listen to it:

```javascript
// ViewportContext.js
import React, {createContext, useState} from 'react';

const ViewportState = createContext();
const ViewportUpdate = createContext();

export function ViewportProvider({children}){
  const [viewport, setViewport] = useState();
  return (
    <ViewportState.Provider value={viewport}>
      <ViewportUpdate.Provder value={setViewport}>
        {children}
      </Viewport
    </ViewportState.Provider>
  )
}

export function useViewport(){
  const context = useContext(ViewportState);
  if(context === undefined) throw Error('You forgot to wrap your app in <ViewportProvider />');
  return context;
}

export function useSetViewport(){
  const context = useContext(ViewportUpdate);
  if(context === undefined) throw Error('You forgot to wrap your app in <ViewportProvider />');
  return context;
}

// App.js
export default function App(){
  return (
    <ViewportProvider>
      <Example1 />
      <Example2 />
      <Map /> 
    </ViewportProvider>
  )
}

// Map.js
export default function Map(){
  const viewport = useViewport();
  const setViewport = useSetViewport();

  // encapsulate loading login in a custom hook
  useViewportData();

  return <ReactMapGL 
    {...viewport}
    onViewportChange={viewport => setViewport}
  />
}

// Example.js - programatic change of viewport
export default function Example(){
  const setViewport = useSetViewport();
  const onClick = () => setViewport({...});
  return <button onClick={onClick}>Move map programmatically</button>
}

// useViewportData.js
export function useViewportData(){
  const viewport = useViewport();
  useEffect(() => {
    // load new data when viewport changes
  }, [viewport])
}

```

Notes;
1. This effect will run EVERY TIME the map moves, including multiple when the user pans and zooms. That seems to be OK from your description though. Use debouncing or throttling to ensure you don't call your API a zillion times a second.

2. Any component that uses the `useViewport` hook will re-render just as often as the aforementioned effect will fire. Use it sparingly and always contain usage to smaller components (i.e. don't use it in a high level parent component with many children) as this will cause a render bottleneck down the chain and abuse of `React.memo` - Been there done that!

**Comment by jarppe** [comment]
Thank you, this is just what I need. Thank you for very descriptive answer and example.
