### ISSUE TITLE
dynamically change display of map

### ISSUE THREAD

**Issue by gandhiamarnadh** [uber/react-map-gl#880]
I would like to have the map loaded all the time but be able to toggle between display: none and block

it is possible with mapbox-gl 
https://docs.mapbox.com/help/troubleshooting/blank-tiles/#mapbox-gl-js
https://jsfiddle.net/gcxq4k2a/17/

however the wrappers introduced by react-map-gl can't work this way. Once mounting map with style display: none on wrapper, changing it to block and calling the resize won't render the map.

**Comment by Pessimistress** [comment]
Use the `visible` prop?
