### ISSUE TITLE
Storing Viewport in State Non-Serializable

### ISSUE THREAD

**Issue by ctaylor4874** [uber/react-map-gl#886]
Storing the viewport in Redux store results in non-serializable values being in the store.  These values come from these items out of the box, and potentially a few others.

* transitionInterpolator
* transitionEasing

In the [`State Management Section`](https://uber.github.io/react-map-gl/#/Documentation/getting-started/state-management) of the docs under `Usage With Redux` this is what is recommended.

```
If you're using redux, it is very easy to hook this component up to store state in the redux state
tree. The simplest way is to take all properties passed to the onViewportChange function
property and add them directly into the store. This state can then be passed back to the
<ReactMapGL> component without any transformation.
```

Is there any way of updating these non-serializable objects to use string values instead of the actual class and function implementations?  [It's best practice to only store serializable values in a Redux store](https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state)

Any tips or advice is greatly appreciated!

**Comment by Pessimistress** [comment]
Are you using server-side rendering? I believe these values are simply dropped during serialization/deserialization. The transition props only indicate how to apply the new state, therefore do not matter on initial mount.

**Comment by ctaylor4874** [comment]
I'm not using server-side rendering, but worry about meaningless updates because of non-serializable values in the store.  Would it be ok to delete the `transitionEasing` and `transitionInterpolator` in my `onViewportChange` function with something like this?
```javascript
onViewportChange={viewport => {
  delete viewport.transitionInterpolator;
  delete viewport.transitionEasing;

  this.props.updateMapViewport(viewport);
}}
```
If you are using redux, you can find these non-serializable values in your redux store under the `store.viewport.transitionInterpolator` path.

**Comment by Pessimistress** [comment]
Deleting those fields should be fine.
