### ISSUE TITLE
Warning: Cannot update during an existing state transition (such as within `render`).

### ISSUE THREAD

**Issue by Jeannito** [uber/react-map-gl#892]
Hi,

I don't know why I get the warning :

> Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

I saw an issue similar, but it said that it has been resolved in 4.0.0(4) beta. But I still get it.
It comes from the _onViewPortChange call in the map render, because I do not get the warning when I remove it.

If someone can have look, it would be very nice!

Here is my code :)

```javascript

class MapFilter extends React.Component {

state = {
        showMap: true,
        viewport: {
            width: '100%',
            height: '100%',
            latitude: 0,
            longitude: 0,
            zoom: 0
        },
        mounted: false
}

_onViewPortChange = viewport => {
        if (this.state.mounted) this.setState({ viewport });
}

render = () => {
        return (
            <ReactMapGL
                mapboxApiAccessToken={'token}
                mapStyle='mapbox://styles/mapbox/streets-v9'
                {...this.state.viewport}
                onViewportChange={this._onViewPortChange}
                width={'100%'}
                height={'100%'}
            >
                {this.renderMarkers()}
            </ReactMapGL>
        );
}

export default MapFilter;

**Comment by rlueder** [comment]
One quick way to fix this is to use a functional component with a `useState` hook instead of a class component:

```
const Map = () => {
  const [state, setState] = React.useState({
    viewport: {
      latitude: 37.7577,
      longitude: -122.4376,
      zoom: 8
    }
  });

  return (
    <ReactMapGL
      {...state.viewport}
      onViewportChange={viewport => setState({ viewport })}
    />
  );
};

export default Map;
```

Docs on useState can be found here: https://reactjs.org/docs/hooks-state.html

**Comment by Jeannito** [comment]
Use it for biggest part of my components was on my plans. But I didn't had the idea for the current problem. Thx :)
