### ISSUE TITLE
stop page scroll when zooming map

### ISSUE THREAD

**Issue by laurexas** [uber/react-map-gl#894]
Hello, i'm having issue with map zooming with mouse wheel, because when i scrollZoom is not disabled when scrolling map all page is scrolling, when i disable scrollZoom then scrollZoom is not working at all.. is there any possibility to zoom only map and not whole page? i noticed that in google map when you enter with mouse on map you have to press ctrl and use wheel button to only zoom component, is there any similiar functionality in react-map-gl?

**Comment by mayteio** [comment]
(captureScroll)[https://uber.github.io/react-map-gl/#/Documentation/api-reference/canvas-overlay]

**Comment by laurexas** [comment]
@mayteio thanks for replying, i tried to implement this functionality but what i managed to get from captureScroll is only that my map stopped from zooming when component is scrolled,  i used scrollZoom ={false} for this, but all i want is to stop page scroll when zooming map not other way around

**Comment by mayteio** [comment]
[Maybe this might help?](https://github.com/uber/react-map-gl/issues/506#issuecomment-397118576)

**Comment by laurexas** [comment]
@mayteio i tried to reproduce this problem in codesandbox and in the end appears that everything works fine in sandbox environment , example how  it supposed to work here - https://codesandbox.io/s/awesome-cache-xog99 , it means property scrollZoom={true} was valid all the time, so my guess is that the problem must be somewhere in my code because i have 3rd party library that controls page scrolling which somehow messes native map scrolling functionality... well because my page is scrolling no matter scrollZoom={true} option , ill try to track this bug and ill inform if i was able to solve this solution, thanks again

**Comment by laurexas** [comment]
looks like my theory was right, my app component was wrapped around 3rd party lib called perfect-scrollbar which overwrote default browser scrolling functionality in which case  it messed my map scrolling.. thanks for your help.
