### ISSUE TITLE
Source and Layer are not exported from 'react-map-gl' issue

### ISSUE THREAD

**Issue by abigger87** [uber/react-map-gl#902]
When trying to use Source and Layer, I have an export error where npm claims Source and Layer are not defined. Attempted adding layer and source to map with getMap() function but it doesn't work...

**Comment by nijynot** [comment]
Having the same problem. Seems like the components are not exported in the latest release, as the components was added in the #896 which was 12 days ago. The latest release is 15 days ago.

**Comment by JoostKiens** [comment]
Any idea when we can expect Layer and Source to be released in a stable version?

**Comment by Pessimistress** [comment]
5.1.1
