### ISSUE TITLE
Uncaught TypeError: transitionInterpolator.getDuration is not a function

### ISSUE THREAD

**Issue by SamSamskies** [uber/react-map-gl#905]
There is a bug that causes the page to crash and render a blank white screen because of a line of code that was added in react-map-gl v4.1.15. https://github.com/uber/react-map-gl/blob/master/src/utils/transition-manager.js#L177

I wasn't able to recreate a simple example with react-map-gl alone, but I figured out how to make it happen when used in combination with deck.gl v7.2.6.

Please see my example here: https://codesandbox.io/s/react-map-gl-v4115-bug-ti94l

```js
/**
 * This demonstrates bug with react-map-gl v4.1.15
 *
 * This line of code (https://github.com/uber/react-map-gl/blob/master/src/utils/transition-manager.js#L177)
 * sometimes throws an error because getDuration doesn't always exist as a function on transitionInterpolator.
 *
 * Steps to recreate bug in this sandbox:
 * 1. double click on the map
 *
 * I've verified that the error does not occur in react-map-gl v4.1.13
 */

import React from "react";
import ReactDOM from "react-dom";
import ReactMapGL from "react-map-gl";
import DeckGL from "deck.gl";

const MAPBOX_TOKEN = "<REDACTED>";

function App() {
  return (
    <DeckGL
      initialViewState={{
        width: 400,
        height: 400,
        latitude: 37.7577,
        longitude: -122.4376,
        zoom: 8
      }}
      controller
    >
      <ReactMapGL mapboxApiAccessToken={MAPBOX_TOKEN} />
    </DeckGL>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by Pessimistress** [comment]
@SamSamskies This looks like a problem in conflicting dependencies. The react-map-gl change bumped `viewport-mercator-project` requirement to `6.2.1`, which is higher than that of deck.gl. It might help if you check the installed version (`yarn list viewport-mercator-project`) and dedup your node_modules.

**Comment by Pessimistress** [comment]
Also: it's recommended that you use `StaticMap` instead of the default export when using the map as a child of `DeckGL`.

**Comment by scy1211** [comment]
Hello, I have encountered the same problem. Have you solved it? Can you share the solution? thank you

Viewport - Mercator - project 6.2.2
The react - map - gl 5.1.3
Deck. Gl 7.3.5

**Comment by SamSamskies** [comment]
@scy1211 unfortunately, I haven't had a chance to try and fix this yet. My temporary fix was to downgrade react-map-gl to v4.1.13. I was hoping to have this problem resolve itself before it became necessary for me to upgrade react-map-gl.

**Comment by jcready** [comment]
This is causing issue in our application as well. I need to know what combination of deck.gl, react-map-gl, and viewport-mercator-project I need to specify to prevent this from crashing.

**Comment by Pessimistress** [comment]
@jcready are you also using the default export as a child of `DeckGL`? Can you try using `StaticMap` instead?

**Comment by jcready** [comment]
Not as far as I know. DeckGL is the child of InteractiveMap.

**Comment by Pessimistress** [comment]
5.1.4
