### ISSUE TITLE
Simple way to add hover effect on polygon

### ISSUE THREAD

**Issue by intelcoder** [uber/react-map-gl#906]
"react-map-gl": "^5.0.12",

Currently, I have about 200 polygons in one layer and I need to add hover and selected effect.

From my research, the only way to update a polygon style on hover or select. I need to use a hover event on the map which returns features and then loop through layer id to find the target layer.

`e.features.find(f => f.layer.id === 'layerId')`

which requires a lot of computing power

However, in the mapbox documentation hover effect can be added like this which throws error with react-map-gl

```
paint={{
  'fill-color': 'rgb(43,62,100)',
  'fill-outline-color': 'rgba(200, 100, 240, 1)',
  "fill-opacity": ["case",
    ["boolean", ["feature-state", "hover"], false],
    1,
    0
  ]
}}
```

**Comment by markjackson02** [comment]
@intelcoder How did you resolve this?

**Comment by intelcoder** [comment]
@markjackson02  
I have layer something like this with layer id.
  
```
<Layer
        id={INTERACTIVE_AREA_POLYGON_LAYER}
        type="fill"
        paint={{
          'fill-color': someColor,
          'fill-opacity': [
            'case',
            ['boolean', ['feature-state', 'hover'], false],
            0.3,
            0,
          ],
        }}
/>
```

And set state hover to true on hover.

```
this.state.mapInstance.setFeatureState({
        source: hoveredPolygon.source,
        id: hoveredPolygon.id,
}, { hover: true })

```
Hope this help.

**Comment by Tamsen1995** [comment]
Could you please elaborate on your solution? I'm not sure where you're getting setFeatureState from exactly.

**Comment by chriszrc** [comment]
@Tamsen1995 it looks like @intelcoder is storing a ref to the map instance, and calling the map.setFeatureState method:

https://docs.mapbox.com/mapbox-gl-js/api/map/#map#setfeaturestate

If that "state" is a redux store though, that's not recommended. But however you get a reference to the mapbox map instance, that is how to set the feature state, and that's what's needed to make hover layer styling work. I think it would still be very helpful if someone posted an example of the recommended way to do this

**Comment by d-vorobyov** [comment]
`const mapRef = React.useRef();`

`      <ReactMapGL
          {...viewport}
          ref={ref => mapRef.current = ref && ref.getMap()}
      >`

`mapRef.current.setFeatureState({ source: 'shapes', id: "1000000" }, { hover: true });`

**Comment by dredtrake** [comment]
beware, the id specified must be an integer or a string that can be casted (from the doc) it took me a moment to figure this out
