### ISSUE TITLE
PointEvent does not return feature's id and geometry

### ISSUE THREAD

**Issue by intelcoder** [uber/react-map-gl#907]
"react-map-gl": "^5.0.12",

I am trying to add hover/select effect to the polygon using setFeatureState. 
However, feature from PointEvent does not contain id

I am passing polygonCollection as data prop. 
I create featureCollection using turf helper

One of the features in the collection looks like this 
```
geometry: {type: "Polygon", coordinates: Array(1)}
id: "area_740"
properties: {…}
type: "Feature"
```

This is how I add layer to the map gl
```
<Source id="polygon1" type="geojson" data={polygonCollection}>
  <Layer
    id="polygon1Layer"
    type="fill"
    layout={{
      visibility: (zoom > 10 && zoom < 11.5) ? 'visible' : 'none'
    }}
    paint={{
      'fill-color': 'rgba(1, 0, 0, 0)',
      'fill-outline-color': 'rgba(10, 50, 240, 1)'
    }}
  />
</Source>
```
When I console the features from PointEvent, the object does not have id 

`
layer: {id: "polygon1Layer", type: "fill", source: "polygon1LayerSource", layout: {…}, paint: {…}}
properties: {…}
source: "polygon1LayerSource"
state: {}
type: "Feature"
_vectorTileFeature:
`

**Comment by Pessimistress** [comment]
react-map-gl gets features using mapbox's [queryRenderedFeatures](https://docs.mapbox.com/mapbox-gl-js/api/#map#queryrenderedfeatures) API. I believe Mapbox does transform your features when they are added, so any non-standard GeoJSON fields might be dropped. You can move `id` into the `properties` object for safety.
