### ISSUE TITLE
Error source cannot be removed while layer "layer" is using it on route change

### ISSUE THREAD

**Issue by intelcoder** [uber/react-map-gl#910]
I have a couple of sources like below code. It works well until map get destroyed by route change.
```
<Source id="tempCircleSource" type="geojson" data={this.state.circleFeature}>
  <Layer
    id="tempCircle"
    type="fill"
  />
</Source>
```

When I change the route, it throws "Error source cannot be removed while layer "layer" is using it on route change" and crashes the site. Is there any way to handle this problem?

**Comment by kevin-vo** [comment]
How did you fix?

**Comment by intelcoder** [comment]
@kevin-vo Sorry I closed because I found the similar issue on the board. 
#908

**Comment by Kistlak** [comment]
First of all you should remove the layer. Then you can remove the source.

```
if (map.getLayer("LayerName")){
   map.removeLayer("LayerName");
}

if (map.getSource("SourceName")){
   map.removeSource("SourceName");
}
```
