### ISSUE TITLE
geolocate-control.js error: "cannot read property '_geolocationWatchID' of null"

### ISSUE THREAD

**Issue by sudoStatus200** [uber/react-map-gl#912]
Thanks for this great library,  It's really easy to use.
I am facing the issue, related to geolocate control.
Current behaviour:
conditions:
User's geolocation is blocked.
Currently user is on page conatining map made wih react-map-gl
So when user redirects from this page to another page.
Browser gives this Error:
![uber1](https://user-images.githubusercontent.com/51601150/67327834-32278280-f536-11e9-80e3-ebe8036458b8.PNG)

![uber2](https://user-images.githubusercontent.com/51601150/67327853-3b185400-f536-11e9-9cdc-38b3407d5050.PNG)

This is how I have implemeted Geolocatecontrol:
![uber4](https://user-images.githubusercontent.com/51601150/67327967-61d68a80-f536-11e9-927f-3d3abdfb9b6d.PNG)

Browser:Chrome Version 77.0.3865.120 
Os:windows 10

I did'nt face this problem in  mozilla firefox

Expected Behaviour:
There should be no error.

Thanks,

**Comment by andrea-svaglic** [comment]
I'm having the same issue, and I've just noticed the bug can also be reproduced on the Examples page (https://uber.github.io/react-map-gl/#/Examples/). Steps:
1. Open example that asks for location, e.g. "Locate User"
2. Click "Geolocate" button
3. Block location
4. Refresh page
5. Click any other menu item

Same browser and version, OS: macOS Mojave v 10.14.6

**Comment by sudoStatus200** [comment]
@andrea-svaglic 
I have added a PR to fix this. Though it's not merged yet.
It is a problem with geolocate-control.js file in react-map-gl.
