### ISSUE TITLE
Release v5.0.11+ missing Viewport flyTo Interpolation `transitionDuraiton: auto`

### ISSUE THREAD

**Issue by liang3404814** [uber/react-map-gl#915]
Hello, I've been unable to use the `transitionDuraiton: auto` feature released in `v5.0.11` according to the changelog https://github.com/uber/react-map-gl/blob/v5.0.12/CHANGELOG.md. 

It looks like the actual code (https://github.com/uber/react-map-gl/issues/865) didn't make it into the release version. According to https://github.com/uber/react-map-gl/compare/v5.0.10...v5.0.11.  (Curiously, it looks like it did get published in `v4.1.16`.)

Thanks for this amazing library!

**Comment by Pessimistress** [comment]
This feature is scheduled for 5.1.0.

**Comment by liang3404814** [comment]
@Pessimistress Thanks for the clarification. Not sure if you want the changelog to reflect it, but I think we can close this for now.
