### ISSUE TITLE
The above error occurred in the <ProjectedLayer> component: in ProjectedLayer (created by Context.Consumer)

### ISSUE THREAD

**Issue by asmakhalfallah2018** [uber/react-map-gl#918]
i am using react-map-gl to show map and show markers on it .But the problem is that i couldn't pass the children props to ReactMapGL . I have written the map component like that :

    import React, { Component } from 'react';
    import ReactMapGL from 'react-map-gl';

     class Mapbox extends Component {
  
       state = {
          viewport: {
        width: "100%",
        position: "relative",
        height: "100vh",
        latitude:48.8534 ,
        longitude: 2.3488,
        zoom: 8
        }
          };

     render() {
            return (
             <div style={{height:"100%",width:"100%",position:"absolute",backgroundColor:"red"}}>
               <ReactMapGL
                   {...this.state.viewport}
                    height={window.innerHeight-99}
                    width="100%"
                    position= "absolute"
                   mapStyle="mapbox://styles/mapbox/outdoors-v11"
                   mapboxApiAccessToken =this.props.token
                   onViewportChange={(viewport) => this.setState({viewport})}>
               {this.props.children} 
           </ReactMapGL>
            </div>
              );
            }
         }

         export default Mapbox;

It seems like this.props.children causes this error  :
 

> Uncaught TypeError: Cannot read property 'off' of undefined
>     at ProjectedLayer.componentWillUnmount

It seems easy to solve but i didn't found how to fix it . Do you have any idea please ?

**Comment by liang3404814** [comment]
@asmakhalfallah2018 This is the wrong repo. Perhaps you meant to post in `react-mapbox-gl`? https://github.com/alex3165/react-mapbox-gl/blob/master/src/projected-layer.tsx
