### ISSUE TITLE
Convert examples to create-react-app?

### ISSUE THREAD

**Issue by RobJacobson** [uber/react-map-gl#920]
I'm new to React. I'm loving react-map-gl, but I'm running into barriers with the provided examples.

Most React tutorials today use a create-react-app project as the starting point. The official react-map-gl examples seem to be using Webpack instead.  (Or is it Browserify?  Not sure.)

When I'm running the examples using Visual Studio Code and try to make revisions, I'll often make a breaking change that causes the map to go blank. I'll then pound my head against the wall, try to guess about the source of the problem, edit the code, shut down the server, recompile, and re-launch the webpage. This is largely due to my own unfamiliarity with Webpack/Browserify, but I'm probably not the only person with this confusion.

I don't tend to have those issues with create-react-app projects. The error messages are more clear, the build logs are less verbose, and hot reloading "just works."

I'd like to propose refactoring the example projects to use create-react-app instead of Webpack/Browserify. I'd be happy to make a first pass at this myself, if there's general consensus for doing so and if someone else could volunteer to provide some help when I get stuck.

I'd also like to propose creating a basic "how to display a map in a webpage" example project for beginners.  The "controls" example is the closest to this, but that example adds some complexity by including markers and popups. A basic "getting started" example could be based on the "controls" example but without the extra material.

Would others agree or disagree with these proposals? Thanks very much.

**Comment by RobJacobson** [comment]
I created a create-react-app version of the Controls demo in a new repository here:
https://github.com/RobJacobson/react-map-gl-examples-cra/tree/master

It was relatively quick once I figured out the differences between CRA and Webpack. I made a few other modifications:

1. I created an .env file for the user to store their Mapbox token. This seems like a better practice than having the user enter it directly in the code. (Although the user can still do so if they want.)

2. I changed the font to Lato (from the default Times New Roman) so the font is closer to the Uber font used on the react-map-gl website.

3. I move the data into the /src folder. Create-react-app can't access files outside of /src.

If there's consensus for switching to create-react-app as the framework, I could do the same for the other examples and the submit a pull request.

**Comment by RobJacobson** [comment]
I also refactored the main mapping code into a separate Map class.  This is to make it easier for users to play around with the example and add other components.

**Comment by Pessimistress** [comment]
@RobJacobson The main goal of the examples is to provide small, standalone samples of working code. create-react-app is a tool for quick bootstrapping projects, but it's not for everyone. For those who choose not to use this setup, create-react-app hides the bundling configurations, while generating many other files that are unrelated to this library.

While we won't convert all examples, having an example for create-react-app users would be nice. You are welcome to open a PR to add your example to `examples/get-started/create-react-app` (a more minimalist version like [this one](https://github.com/uber/react-map-gl/tree/master/examples/get-started/hooks)).

**Comment by RobJacobson** [comment]
Thanks @Pessimistress!  (I love your handle, by the way.)  I'll submit a pull request.
