### ISSUE TITLE
TypeError: Cannot read property 'removeLayer' of undefined

### ISSUE THREAD

**Issue by intelcoder** [uber/react-map-gl#931]
I updated to 5.1.0 which has fix for Fix crash during Source component removal (#928 )

It works fine when the map destroyed the first time but when I go back to the map and destroy the map again. It throws error TypeError: Cannot read property 'removeLayer' of undefined from below code.
```
key: "componentWillUnmount",
value: function componentWillUnmount() {
    this._map.removeLayer(this.id);
}
```
this.map probably already gone by that time it try to call removeLayer

Should we add check if this._map exists?

Thanks guys.

**Comment by Pessimistress** [comment]
@intelcoder  This should be fixed in 5.1.1.
