### ISSUE TITLE
Marker position's anchor issue

### ISSUE THREAD

**Issue by Emixam23** [uber/react-map-gl#938]
Hey!

I've written a question on StackOverflow regarding the `<Marker/>` at https://stackoverflow.com/questions/58784620/change-the-anchor-of-an-image-marker-pin-css-reactjs

In fact, I would like to understand why a [Marker](https://github.com/uber/react-map-gl/blob/master/docs/components/marker.md) points its related lat/long by its center (div) instead of its bottom (center point 50/50 on width but 100 on height)?

Thanks !

**Comment by Pessimistress** [comment]
react-map-gl does not dictate what a marker looks like. Some may want their marker anchored at the center, and some may want it anchored at the top. You can use 
`offsetLeft` and `offsetTop` to adjust.

**Comment by Emixam23** [comment]
Alright thanks for the feedback :)

**Comment by RobJacobson** [comment]
I used transform: translate in my own code:

.mapboxgl-marker {
  transform: translate(-50%, -50%);
}
