### ISSUE TITLE
difference between MapGL and ReactMapGL?

### ISSUE THREAD

**Issue by kkdd** [uber/react-map-gl#947]
Hello,
What is a difference between ```MapGL``` and ```ReactMapGL```?

```
import MapGL from 'react-map-gl';
import ReactMapGL from 'react-map-gl';
```

**Comment by xintongxia** [comment]
@kkdd 

They are the same, `import something from "module-name";` basically means you can import the default export from that module.

You can name it (`something`) anything you would like to, it is as a reference to that module.

**Comment by kkdd** [comment]
Thank you for your teaching me kindly.
I have realized as: ```import [anything I would like to name it] from "module-name"```.
