### ISSUE TITLE
access mapboxgl instance without importing it

### ISSUE THREAD

**Issue by sayjeyhi** [uber/react-map-gl#950]
I want to access `mapboxgl ` without importing it, cuz this package has mapboxgl in it dependencies. 

example:
How I could call sth like :

if (!mapboxgl.hasRTLTextPlugin) {
      mapboxgl.setRTLTextPlugin(Map[mapType].RTLTextPlugin);
      mapboxgl.hasRTLTextPlugin = true;
    }
without importing 'mapbox-gl' in my component ?

**Comment by Pessimistress** [comment]
You can `import {hasRTLTextPlugin} from 'mapbox-gl'`. What is the concern about importing the package since it's already a dependency?

**Comment by Arman92** [comment]
mapbox-gl is a peer dependecy of react-map-gl, one still needs to add mapbox-gl into his own package.json, am I correct? 

> You can `import {hasRTLTextPlugin} from 'mapbox-gl'`. What is the concern about importing the package since it's already a dependency?

**Comment by Pessimistress** [comment]
It is a dependency. https://github.com/uber/react-map-gl/blob/master/package.json#L48
