### ISSUE TITLE
Control icons missing with mapbox-gl-js 1.6.0

### ISSUE THREAD

**Issue by tsibley** [uber/react-map-gl#952]
The icons for map controls are missing when using react-map-gl 5.1.3 with mapbox-gl-js 1.6.0. I expect this affects most earlier versions of react-map-gl too. The controls are functional but blank.

The 1.6.0 release of mapbox-gl-js changed the CSS and elements used for these controls from:

```html
<button class="mapboxgl-ctrl-icon mapboxgl-ctrl-fullscreen">
</button>
```

to

```html
<button class="mapboxgl-ctrl-fullscreen">
  <span class="mapboxgl-ctrl-icon" aria-hidden="true"></span>
</button>
```

with the icons now rendered into the new `<span>`s. The relevant commit is https://github.com/mapbox/mapbox-gl-js/commit/d59b3da4.

I'd be happy to submit a patch, but I wasn't sure how you'd like to handle backwards compatibility with older mapbox-gl-js versions. Something like the following combination of the old and new HTML might work, but I haven't tested the extra `<span>` for adverse effects on older versions.

```html
<button class="mapboxgl-ctrl-icon mapboxgl-ctrl-fullscreen">
  <span class="mapboxgl-ctrl-icon" aria-hidden="true"></span>
</button>
```

**Comment by andycarrell** [comment]
Hi @tsibley - Run into the same issue definitely would be ideal for the library to fix 👍 
I've managed to mitigate this by either:
Add link to 1.5.1 css to head tag:
```html
<head>
    <link rel="stylesheet" href="https://api.tiles.mapbox.com/mapbox-gl-js/v1.5.1/mapbox-gl.css" type="text/css" />
</head>
```
Or specifying the version of mapbox-gl to rely on in my app's packages:
```
"mapbox-gl": "1.5.1",
```
(Optional) And importing the css file (where I use mapbox):
```
import MapGL, { NavigationControl } from "react-map-gl";

import "mapbox-gl/dist/mapbox-gl.css";
```

**Comment by kjkurtz** [comment]
I can confirm this issue with 1.6.1 as well. I moved back to 1.5.1 per @andycarrell's suggestion and everything returned to fully functioning. The specific controls were Geolocation and NavigationControls although I suspect it would be all of them based on how the CSS was behaving in dev tools.

**Comment by Pessimistress** [comment]
`react-map-gl@5.1.6` should work with both mapbox-gl@1.6.0 and older versions.

**Comment by svirins** [comment]
rollback to 1.5.1 solved issue

**Comment by kjkurtz** [comment]
It did for me too. But if you upgrade `react-map-gl` to >1.6.0 then you shouldn't need to rollback. At least that was the case for me.

**Comment by jotapee** [comment]
Same issue here, needed to roll back to 1.5.1 to get icons displayed.

**Comment by Pessimistress** [comment]
@jotapee Please see the previous comment and update your react-map-gl.

**Comment by jotapee** [comment]
@Pessimistress I was using mapbox on vue.js not react, I was facing the same issue though. The new 1.8.0 version solved the issue for me. Thanks.

**Comment by jkarttunen** [comment]
Seeing the same thing with Mapbox-gl 1.9.0

**Comment by contis2908** [comment]
We are using `"mapbox-gl": "^1.10.0"` and still encounter this issue

**Comment by tsaiDavid** [comment]
Same here, experienced the same problem with the latest `^1.10.0`, however, rolling back to `1.5.1` allows me to see all 3 icons. using 1.10.1, I was missing the compass.

**Comment by Pessimistress** [comment]
@contis2908 @tsaiDavid This issue was fixed in 5.1.6. Open a new issue if you are still experiencing it with the latest release.

**Comment by varun2948** [comment]
Inserting This in your css/scss file does the work Try it Out and Dont Forget To Put Your Node Modules/mapbox-gl/src/svg folders file in somewhere img location To Make it Easily Accessible

.```
mapboxgl-ctrl button.mapboxgl-ctrl-zoom-out .mapboxgl-ctrl-icon{
  background-image: url('../img/svg/mapboxgl-ctrl-zoom-out.svg')
}
.mapboxgl-ctrl button.mapboxgl-ctrl-compass .mapboxgl-ctrl-icon{
  background-image: url('../img/svg/mapboxgl-ctrl-compass.svg')
}
.mapboxgl-ctrl button.mapboxgl-ctrl-zoom-in .mapboxgl-ctrl-icon{
  background-image: url('../img/svg/mapboxgl-ctrl-zoom-in.svg')
}
```

**Comment by Rvervuurt** [comment]
The above CSS is missing a period before the first `mapboxgl-ctrl`. Also made a few linter-fixes:
```
.mapboxgl-ctrl button.mapboxgl-ctrl-zoom-out .mapboxgl-ctrl-icon {
  background-image: url("#{$image-path}/svg/mapboxgl-ctrl-zoom-out.svg");
}

.mapboxgl-ctrl button.mapboxgl-ctrl-compass .mapboxgl-ctrl-icon {
  background-image: url("#{$image-path}/svg/mapboxgl-ctrl-compass.svg");
}

.mapboxgl-ctrl button.mapboxgl-ctrl-zoom-in .mapboxgl-ctrl-icon{
  background-image: url("#{$image-path}/svg/mapboxgl-ctrl-zoom-in.svg");
}
```

**Comment by midanosi** [comment]
Thanks to the previous 2 comments for providing the fix I needed.

Minor differences for me (react-mapbox-gl@6.1.13); now the css rule is:  
`.mapboxgl-ctrl button.mapboxgl-ctrl-compass.mapboxgl-ctrl-icon` (no space)  
instead of
`.mapboxgl-ctrl button.mapboxgl-ctrl-compass .mapboxgl-ctrl-icon`

and the svg files can be found at `node_modules/mapbox-gl/src/css/svg`

**Comment by danlgz** [comment]
I'm using the 3.1.2 version and I tried to import the styles file (how the previous comments say) and doesn't work.

I inspected the elements and I saw `display: none` and I override it. It's not the best, but works for me now.

<img width="884" alt="image" src="https://github.com/visgl/react-map-gl/assets/26347085/fac61fea-2656-4ffe-90b5-16bbab441cf2">
