### ISSUE TITLE
Document usage of fitBounds

### ISSUE THREAD

**Issue by RyKilleen** [uber/react-map-gl#954]
Thanks for all your work on this library!

It appears the location / usage of fitBounds has moved and changed again, and it's a bit difficult to follow (I believe it's now in the `Math.gl` library?)

Any update to the docs to reflect the new changed location, instead of the old changed location, would go a long way to making it easier to understand!

**Comment by Pessimistress** [comment]
The source for `WebMercatorViewport` is moved into the math.gl repo for maintenance reasons. The `viewport-mercator-project` module is still published, so no breaking change there.

Documentation wise, we have something in https://uber.github.io/react-map-gl/#/Documentation/api-reference/static-map?section=faq which admittedly is hard to find. I think one option is to just re-export `WebMercatorViewport` from `react-map-gl` and document it as part of this library - then you won't have to go hunt down its docs elsewhere.

**Comment by ibgreen** [comment]
Duplicating docs might be a good idea but does have the risk of the text going out of sync. 

Just as an idea, an alternative could be to enhance our website generator to include external links in the table of contents.

I.e. we could show `WebMercatorViewport` in react-map-gl's "API reference" table of contents, looking like that class is a first-class citizen in the react-map-gl API, but the link would take you to the math.gl docs.

**Comment by Pessimistress** [comment]
The react-map-gl website is still using the old website harness, which supports external doc links. I'm not sure about the state of ocular-gatsby.

**Comment by Pessimistress** [comment]
v5.2.0

https://uber.github.io/react-map-gl/#/Documentation/api-reference/web-mercator-viewport
