### ISSUE TITLE
Adding transitionDuration as a prop crashes the map

### ISSUE THREAD

**Issue by ctaylor4874** [uber/react-map-gl#957]
To reproduce, add a FlyToInterpolator with a transitionDuration.

```jsx
<ReactMapGL
    transitionDuration={500}
    transitionInterpolator={new FlyToInterpolator()}
/>
```

**Comment by Pessimistress** [comment]
Can you provide: 

- The version of react-map-gl you're using
- The error message from the console

**Comment by ctaylor4874** [comment]
I'm not able to reproduce on codesandbox. Probably something I'm doing wrong!

**Comment by VanLaerAshley** [comment]
I have the same issue @ctaylor4874 , What was the fix you have used?
I'm on : "react-map-gl": "^6.1.9",
the error message says: Error: latitude must be supplied for transition
