### ISSUE TITLE
Simplestyle markers

### ISSUE THREAD

**Issue by aidanlister** [uber/react-map-gl#962]
Is there any way to just use the https://docs.mapbox.com/help/tutorials/markers-js/#style-markers-with-simplestyle markers?

Surely I don't have to make my own marker SVG just to have numbered markers?

**Comment by Pessimistress** [comment]
You are linking to the documentation of Mapbox.js, not Mapbox GL JS. Mapbox.js is no longer being developed by Mapbox. This library is a wrapper of the latter.

If you want to use simplestyle with Mapbox GL JS, you need to ask in the Mapbox repo.
