### ISSUE TITLE
Performance on when dragging https://uber.github.io/react-map-gl/#/Examples/markers-popups is bad

### ISSUE THREAD

**Issue by jrmuizel** [uber/react-map-gl#963]
I see upward of 16ms spent handling pointermove events on desktop when profiling https://uber.github.io/react-map-gl/#/Examples/markers-popups in Chrome. The majority of the time is spent javascript.

**Comment by Pessimistress** [comment]
Merge the discussion with https://github.com/uber/react-map-gl/issues/750
