### ISSUE TITLE
Cannot figure out how to get resulting location of GeolocateControl

### ISSUE THREAD

**Issue by CSFlorin** [uber/react-map-gl#964]
How do I access that info? I tried logging the component itself but could not find lat or lon. What am I missing?

**Comment by MunifTanjim** [comment]
You can't, until this get merged https://github.com/uber/react-map-gl/pull/761

After that, you can use `onGeolocate` callback.

**Comment by CSFlorin** [comment]
Thanks. I actually have found that using `onViewportChange` in the GeolocateControl seems to work since it only acts on view changes caused by the geolocate control.

**Comment by Pessimistress** [comment]
#761 is published in 5.1.6
