### ISSUE TITLE
Add d3 scale prop to ChoroplethOverlay

### ISSUE THREAD

**Issue by Calvein** [uber/react-map-gl#97]
Hi, I'm using the ChoroplethOverlay I need to use an ordinal scale, I made a fake domain (1 = 'my first label', 2 = 'my second label', etc) but it doesn't look right.
I would rather be able to add my own scale or have a flag to use an ordinal instead of a linear scale.

**Comment by abmai** [comment]
@Calvein did you ever solve this and would you like you open a PR if so?

**Comment by Calvein** [comment]
I end up using react-leaflet

**Comment by shaojingli** [comment]
ChoroplethOverlay has been removed from the core features and moved to the examples. Closing
