### ISSUE TITLE
Source component breaks for vector tile sources

### ISSUE THREAD

**Issue by sashako** [uber/react-map-gl#984]
Hello,

I'm trying to use Source component with a custom tile server, however I believe 'vector' type is not handled probably within `<Source />` . Any time source attempts to re-render it tries to remove and re-create the specified source, which obviously breaks as it doesn't account for nested Layers' lifecycle and I get an error like `Error: Source "SourceName" cannot be removed while layer "LayerName" is using it.`

Also, looking at the source code, under what circumstances would this work? 
https://github.com/uber/react-map-gl/blob/master/src/components/source.js#L122-L125

**Comment by Pessimistress** [comment]
This condition should only be reached if some of the props changed. What props are you passing to Source?

**Comment by sashako** [comment]
I'm passing `id`, `type` and `tiles`. The problem is for `type='vector'` this condition is always being hit.

**Comment by Pessimistress** [comment]
You are probably passing `tiles` as a new array in every render. The component should perform a deep comparison on the props.

**Comment by sashako** [comment]
@Pessimistress that did the trick! thank you!

**Comment by Pessimistress** [comment]
Fixed in 5.2.1.
