### ISSUE TITLE
Popup Window is too far from the coordinates

### ISSUE THREAD

**Issue by howdyhyber** [uber/react-map-gl#988]
Greetings!

I have tried to put pop up on my marker in map but it seems like when in opens, its too far from the marker, though i provided the same coordinates as the marker.
![Screenshot from 2020-01-11 15-11-35](https://user-images.githubusercontent.com/22556130/72200487-f9d47800-3484-11ea-9a20-6398d76423f1.png)

**Comment by enzzoperez** [comment]
HI!, did you able to resolve this? I have the same problem
