### ISSUE TITLE
Line disappears and appears on Zoom out

### ISSUE THREAD

**Issue by howdyhyber** [uber/react-map-gl#991]
Greetings!

I have experienced a weird behavior on LineString, it seems like when i zoom in/out, line disappears. I want it to be intact. How to do it?
![close](https://user-images.githubusercontent.com/22556130/72334932-1547b900-36f9-11ea-869e-dfb5c1d197f5.png)
![not closed](https://user-images.githubusercontent.com/22556130/72334937-18db4000-36f9-11ea-9f26-af2e54082ecf.png)

**Comment by Pessimistress** [comment]
Map rendering issues should be reported in the mapbox-gl repo.

**Comment by lucas-dolsan** [comment]
Also having this issue
