### ISSUE TITLE
Call queryRenderedFeatures from onMouseUp event

### ISSUE THREAD

**Issue by maxwell-oroark** [uber/react-map-gl#992]
What is the best way to invoke the `queryRenderedFeatures` method on the map when inside an `onMoveEnd` callback function?  Is this method exposed somehow, or, would I need to use the method on the actual map object as obtained from `getMap()`

**Comment by Pessimistress** [comment]
What is the issue with calling it from `onMouseUp`?

**Comment by maxwell-oroark** [comment]
@Pessimistress In the README, you mention that I may need to instantiate the Map object in order to call some of the functionality _not_ mirrored in your library but that I should be wary of doing so.  I'm wondering if this is one of those use cases where I need to call `getMap()` and then call `map.queryRenderedFeatures()` inside the `onMouseUp` handler or if there is some way better way to do it with your library.

**Comment by Pessimistress** [comment]
`queryRenderedFeatures()` is mirrored by `StaticMap` and `InteractiveMap`: https://uber.github.io/react-map-gl/#/Documentation/api-reference/static-map?section=methods

You can just call `mapRef.current.queryRenderedFeatures()`.
