### ISSUE TITLE
MapState is not exported from index.js

### ISSUE THREAD

**Issue by HasanAyan** [uber/react-map-gl#996]
Hi, I would like to do various transitions from child components of InteractiveMap. 

I looked at the source code of NavigationControl and it is using `context.ViewportChange` ,`context.ViewStateChange`,` context.viewport` and `MapState`

To give you more context, I am trying to create a ClickZoomableLayer which will render Layer component with given props, bind to `anyclick` event on context.eventManager, and fly to clicked feature's position.

However, it seems MapState class is not exported from `index.js` and I can't import it from `'/utils/map-state.js'` since typecsript is complaining about it. Is there a workaround?

**Comment by HasanAyan** [comment]
I have opened a new pull request to fix this issue 

Export MapState from index.js so it is available for import by consumers #997

**Comment by Pessimistress** [comment]
What features are you trying to use on `MapState`? You can simply call `onViewStateChange` with the updated view state `{longtidue: <number>, latitude: <number>, zoom: <number>, transitionInterpolator: new FlyToInterpolator(), transitionDuration: <number>}`.

**Comment by HasanAyan** [comment]
alright @Pessimistress , I tried it and worked but I am not sure about the parameters this function takes. 
what is the use of interactionState and newViewState ?

Is this correct way to do it?

```
            <ReactMapGL
              {...viewportState}
              // onViewportChange={viewport => {
              //   setViewportState(state => ({ ...state, ...viewport }));
              // }}
              onViewStateChange={viewStateChangeInfo => {
                setViewportState(state => ({
                  ...state,
                  ...viewStateChangeInfo.viewState
                }));
              }}/>
```


and when I want to focus on something;

```
export const fly = (
  mapContext: MapContextProps,
  params: Partial<ViewportProps>
) => {
  mapContext.onViewStateChange &&
    mapContext.onViewStateChange({
      viewState: {
        ...params,
        transitionDuration: 300,
        transitionInterpolator: new FlyToInterpolator(),
        transitionInterruption: TRANSITION_EVENTS.BREAK
      }
    } as any);
};
```

**Comment by Pessimistress** [comment]
That looks fine. `interactionState` is used by some applications to determine what interaction triggered the view state change (pan, rotate, zoom, transition etc.). If your app doesn't need it then you don't have to send anything.
